Updating outline BCD for FF88 about following the shape of border-radius
mdn/browser-compat-data pull request #10035
Opened 2021-04-22 17:12 UTC by mirunacurtean

A checklist to help your pull request get merged faster:
- [x] Summarize your changes

Updating FF and FF android columns version and adding notes "From Firefox 88 onwards, the standard outline property will follow the shape of border-radius."

- [x] Data: link to resources that verify support information (such as browser's docs, changelogs, source control, bug trackers, and tests)

https://bugzilla.mozilla.org/show_bug.cgi?id=1694146

- [x] Link to related issues or pull requests, if any
- Fixes https://github.com/mdn/content/issues/3453

2021-05-12 16:01 UTC, ddbeck requested changes
Thanks for this PR, @mirunacurtean. Several suggestions for you, with explanations in `outline.json`. Let me know if you have any questions!

2021-05-12 16:01 UTC, ddbeck commented on css/properties/outline-offset.json
> +              "notes": "From Firefox 88 onwards, the standard outline property will follow the shape of border-radius."
```suggestion
              "version_added": "1.5",
              "notes": "Before Firefox 88, an outline does not follow the shape of <code>border-radius</code>."
```

2021-05-13 08:38 UTC, mirunacurtean commented on css/properties/outline-color.json
> +                "notes": "From Firefox 88 onwards, the standard outline property will follow the shape of border-radius."
Alright, At the moment I don't know how to undo just that so I'll just update those rows to contain the previous information and push this out along with all the other suggested changes for this PR. Thanks!

2021-05-13 15:33 UTC, mirunacurtean commented on css/properties/outline.json
> +                "notes": "From Firefox 88 onwards, the standard outline property will follow the shape of border-radius."
I'm taking the expert opinion here into account :) I've updated this based on the suggestions.

2021-05-13 15:34 UTC, mirunacurtean commented on css/properties/outline.json
> +                "notes": "From Firefox 88 onwards, the standard outline property will follow the shape of border-radius."
Done in next commit.

2021-05-13 15:54 UTC, mirunacurtean commented
@ddbeck I hope I incorporated all suggestions successfully after the latest corrections (initially I used the same version_added for FF desktop and android and that was incorrect, so I've updated all in all files). Checks are still running so fingers crossed. 
Sorry for the messiness of these updates!

2021-05-14 17:12 UTC, ddbeck requested changes
There are a few things left to fix here:

1. Some mis-indentation is causing CI to fail. If you run `npm run fix` and commit the results, it should correct this automatically.
2. Please delete `yarn.lock`. We don't use it.
3. I left a line comment highlight a spot I missed on the last go-around.

Thanks!

2021-05-18 08:15 UTC, mirunacurtean commented on css/properties/outline-offset.json
> +              "version_added": "88",
Applied in next commit.

2021-05-18 09:07 UTC, mirunacurtean commented
@ddbeck I think this is finally ready for another look.

2021-05-18 12:42 UTC, ddbeck approved these changes
Looks good. Thank you! 🎉

2021-05-18 12:42 UTC, merged