Update img.json to include information about Safari's implementation …
mdn/browser-compat-data pull request #10087
Opened 2021-04-26 14:27 UTC by sulliops

…of aspect_ratio_computed_from_attributes

Safari's implementation of `aspect_ratio_computed_from_attributes` currently does not work as intended with lazy-loaded images, per https://bugs.webkit.org/show_bug.cgi?id=224197. A fix has been committed and should be rolled out in a future release of Safari.

2021-04-29 16:38 UTC, ddbeck requested changes
Thanks for this PR, @sulliops. I see it's your first on the project—welcome!

I've got a suggested rewrite for the note and I'd like your opinion on it.

2021-04-29 16:38 UTC, ddbeck commented on html/elements/img.json
> +                "notes": "Safari's implementation does not yet work properly with lazy-loaded images. See: https://webkit.org/b/224197"
I misunderstood this note at first to mean that it somehow prevents lazy loading. How about we revise it somewhat to make it clear that this affects layout. What do you think of this?

```suggestion
                "notes": "Safari doesn't preserve space for images without a valid <code>src</code>, which may disrupt layouts that rely on lazy loading (see <a href='https://webkit.org/b/224197'>bug 224197</a>)."
```

2021-04-29 16:38 UTC, ddbeck commented on html/elements/img.json
> +                "notes": "Safari's implementation does not yet work properly with lazy-loaded images. See: https://webkit.org/b/224197"
```suggestion
                "notes": "Safari doesn't preserve space for images without a valid <code>src</code>, which may disrupt layouts that rely on lazy loading (see <a href='https://webkit.org/b/224197'>bug 224197</a>)."
```

2021-04-29 18:58 UTC, sulliops commented
> I've got a suggested rewrite for the note and I'd like your opinion on it.

Good suggestion! No further changes on my end. I preemptively deleted my patch repo, but I believe you can commit your suggestions on your end.

By the way, how would I go about listing the change if the Safari `version_added` were `TP` or Technical Preview? On a different commit, the checks failed because `TP` is not recognized.

2021-04-30 10:27 UTC, ddbeck commented
@sulliops! Thank you. The missing fork made applying the changes a little weird (and it's possible I used the wrong command line incantation), but ee9cbf002d8d0c1cf4f5004484ba5e44bbe5ebfd applies your PR to the main branch. 🎉

> By the way, how would I go about listing the change if the Safari `version_added` were `TP` or Technical Preview? On a different commit, the checks failed because `TP` is not recognized.

We don't have a way to do this yet. We're trying to work out a method for several browsers at once (Safari TP, Chrome Canary, Firefox Nightly). In the mean time, feel free to open issues to track the things our schema doesn't yet represent (we can flag it as blocked until we have a solution, or the feature ships).

2021-04-30 10:27 UTC, closed without merging