FF89 removal UserProximityEvent and Window.onuserproximity
mdn/browser-compat-data pull request #10103
Opened 2021-04-27 04:52 UTC by hamishwillee

This API was previously under a preference and was supposed to be removed (along with `DeviceProximityEvent`) in FF89 - see https://bugzilla.mozilla.org/show_bug.cgi?id=1699707#c15. Prior to that it was behind a preference, which effectively means that it was removed in FF79 on Android (see #9679).

However while `DeviceProximityEvent` was actually removed this was not, because it is still useful for KaiOS (only). However as per the [comment](https://bugzilla.mozilla.org/show_bug.cgi?id=1699707#c15) the INTENT is that this is off for Android and that a user will not turn it on.

So what I have done is make this match `DeviceProximityEvent` - it is shown as being removed in v89 for desktop and v79 for android. I also "rationalised" the windows event handler to match the versionining, because without the pref set you won't get an event. 

I do not mention KaiOS because we have no Firefox for KaiOS option.

Docs tracking for this is in https://github.com/mdn/content/issues/4308

2021-04-29 18:00 UTC, ddbeck requested changes
A couple of suggestions for you, @hamishwillee. Thanks!

2021-04-30 01:41 UTC, hamishwillee commented
Thanks @ddbeck - fixed as per your suggestions/explanations. All makes sense.

2021-04-30 03:45 UTC, Gulyas89 approved these changes

2021-04-30 18:10 UTC, ddbeck approved these changes
Thank you! 🎉

2021-04-30 18:11 UTC, merged