Support multiple positional arguments to mirror scripts
mdn/browser-compat-data pull request #10645
Opened 2021-05-27 09:26 UTC by foolip

#### Summary

Make it possible to run the mirror script like `npm run mirror -- firefox_android api/_mixins/SVGFilterPrimitiveStandardAttributes__SVGFE*` by supporting multiple positional arguments.

#### Test results and supporting details

No tests!

2021-06-17 12:46 UTC, foolip commented
@ddbeck or @Elchi3 for review?

2021-07-01 01:26 UTC, vinyldarkscratch approved these changes
Oh yeah, much nicer-looking and much more sensible!

2021-07-01 16:15 UTC, ddbeck requested changes

2021-07-01 16:15 UTC, ddbeck commented on scripts/mirror.js
>        .option('source', {
Doesn't quite reach within the diff, but would you mind adding a couple of usage examples (with [`.example()`](http://yargs.js.org/docs/#api-reference-examplecmd-desc)) toward the end of the yargs stuff? Two or three would be great (e.g., with a feature, with a path, with more than one of something).

2022-04-18 14:57 UTC, queengooborg commented
I'm going to go ahead and merge this PR now, but Daniel's suggestion is a great one, so I'll follow up on that shortly!

2022-04-18 14:58 UTC, merged