Add IE versions for api.Document.transition_events
mdn/browser-compat-data pull request #10821
Opened 2021-06-07 09:14 UTC by vinyldarkscratch

This PR adds real values for Internet Explorer for the `transition_events` member of the `Document` API.  These events aren't supported in Edge, and they're too new to be in Internet Explorer.

2021-06-07 10:15 UTC, foolip approved these changes

2021-06-07 10:17 UTC, foolip commented
A nit about the description:

> These events aren't supported in Edge, and they're too new to be in Internet Explorer.

These events are related to the CSS `transition` property, which actually isn't too new, that was in IE10:
https://developer.mozilla.org/en-US/docs/Web/CSS/transition#browser_compatibility

But the transitioncancel events seem to have been a later addition. Maybe it was added to the spec after IE11?

2021-06-07 10:22 UTC, foolip commented
Yep, https://github.com/w3c/csswg-drafts/commit/b18ba175d182128ca2d879555f8a17361483cbaa was in May 2015, so between IE 11 and Edge 12 release dates. It also introduced the transitionstart events.

@vinyldarkscratch perhaps you can turn this into a PR updating transitionstart too, and making the onfoo and foo_event entries match?

2021-06-10 12:05 UTC, vinyldarkscratch commented
The `transitionstart` event is already getting updated though?  There also aren't any event handlers for these events (`onfoo`).

2021-06-10 20:07 UTC, foolip commented
OK, so once again questioning everything leads to the existing data being wrong. I took the example in https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/transitionstart_event and turned it into this:
https://software.hixie.ch/utilities/js/live-dom-viewer/?saved=9408

Running that in IE11 shows the events are fired. It's just the event handler attributes that aren't supported, so some kind of notes will be needed.

The onfoo attributes for these events are in GlobalEventHandlers.json.

Do you want to update all of this in this PR, or split it up a bit? Either way is fine with me.

2021-06-12 13:35 UTC, vinyldarkscratch commented
Running that test in IE 10 reveals that those transition events _are_ supported, fixed!

2021-06-17 08:20 UTC, foolip approved these changes
Yay!

2021-06-17 08:22 UTC, foolip commented
So before this is merged I think we also need to add notes to explain that the `ontransition*` properties came later, but it's possible to listen for the events using `addEventListener`. And maybe double check that the `ontransition*` data is in fact correct so we don't just add to lies and confusion :)

2021-06-29 19:41 UTC, vinyldarkscratch commented
The event handlers are indeed not supported in IE.  Adding notes to describe as such now!

2021-07-01 10:01 UTC, foolip requested changes

2021-07-01 10:01 UTC, foolip commented on api/Document.json
> +              "notes": "This event's handler attribute (<code>ontransitionend</code>) is not supported; however, the event itself is supported since IE 10. The event can be listened to via <code>docu
Can you match the wording of the visibilitychange_event entry, or change it to match this if you think it's better like this?

2021-07-02 22:35 UTC, foolip commented
Can you also add notes to the ontransition* entries that presumably are just false now? There should be existing note wording to copy elsewhere.

2021-07-14 14:18 UTC, foolip approved these changes

2021-07-14 14:18 UTC, foolip commented on api/GlobalEventHandlers.json
> +              "notes": "The <code>ontransitionrun</code> attribute is not supported in IE. To listen to this event, use <code>document.addEventListener('transitionend', function() {});</code>."
```suggestion
              "notes": "The <code>ontransitionrun</code> attribute is not supported in IE. To listen to this event, use <code>document.addEventListener('transitionrun', function() {});</code>."
```

2021-07-14 14:18 UTC, foolip commented on api/GlobalEventHandlers.json
> +              "notes": "The <code>ontransitionstart</code> attribute is not supported in IE. To listen to this event, use <code>document.addEventListener('transitionend', function() {});</code>."
```suggestion
              "notes": "The <code>ontransitionstart</code> attribute is not supported in IE. To listen to this event, use <code>document.addEventListener('transitionstart', function() {});</code>."
```

2021-07-14 14:28 UTC, merged