Update Safari versions for AnimationEvent API
mdn/browser-compat-data pull request #10904
Opened 2021-06-10 06:07 UTC by vinyldarkscratch

This PR updates and corrects the real values for Safari (Desktop and iOS/iPadOS) for the `AnimationEvent` API, based upon results from the [mdn-bcd-collector](https://mdn-bcd-collector.appspot.com) project (v3.1.4).

Tests Used: https://mdn-bcd-collector.appspot.com/tests/api/AnimationEvent

2021-06-10 09:29 UTC, foolip requested changes

2021-06-10 13:23 UTC, vinyldarkscratch commented on api/AnimationEvent.json
> +              "version_added": "6"
Ack, my notes weren't included...  Actually, this one was me performing a manual test (though using the collector's `testConstructor` function) in each Safari version to see if/when `WebKitAnimationEvent` is a valid constructor, which led to this change.  Maybe we should add a prefix to the constructor's data?

2021-06-10 20:13 UTC, foolip commented on api/AnimationEvent.json
> +              "version_added": "6"
Yes, if there was a `WebKitAnimationEvent` constructor that worked, then we should have a prefix there too. The parent interface already has a prefix, but in the case of exposed and prefixed constructors they're needed in both places.

2021-06-11 05:00 UTC, foolip approved these changes

2021-06-11 05:00 UTC, merged