Add Safari iOS versions for api.HTMLCanvasElement.getContext.webgl_context
mdn/browser-compat-data pull request #10910
Opened 2021-06-10 06:32 UTC by vinyldarkscratch

This PR adds real values for Safari iOS/iPadOS for the `getContext.webgl_context` member of the `HTMLCanvasElement` API by mirroring the data.

2021-06-10 10:33 UTC, foolip requested changes
Per https://caniuse.com/webgl WebGL didn't ship at the same time on desktop and mobile, and I'd guess that's right, although I wouldn't blindly trust the specific versions claimed there.

Can you check what the various WebGL data we have currently says, and if it all needs updating perhaps?

2021-06-10 13:12 UTC, vinyldarkscratch commented
This should now be ready to go!  I did some further digging and found that Safari introduced the standard `webgl` value in Safari 8 (though has kept `experimental-webgl` as well).

2021-06-10 17:08 UTC, foolip commented
Did this involve testing iOS too? When WebGL first shipped in iOS is my main point of uncertainty.

2021-06-12 14:48 UTC, vinyldarkscratch commented
I just performed the testing in Safari iOS 7 and 8, and can confirm it's accurate!

2021-06-12 15:56 UTC, foolip commented
Excellent! 🙏

2021-06-12 15:56 UTC, foolip approved these changes

2021-06-12 15:57 UTC, merged

2021-06-12 15:57 UTC, foolip commented
I wonder if there's more WebGL data for iOS that should be bumped to 8?