Add Safari iOS versions for MediaStreamAudioSourceOptions API
mdn/browser-compat-data pull request #10912
Opened 2021-06-10 06:36 UTC by vinyldarkscratch

This PR adds real values for Safari iOS/iPadOS for the `MediaStreamAudioSourceOptions` API by mirroring the data.

2021-06-10 10:36 UTC, foolip requested changes
The existing data for Safari doesn't make sense together with https://developer.mozilla.org/en-US/docs/Web/API/MediaStreamAudioSourceNode#browser_compatibility, something must be wrong.

2021-06-10 13:18 UTC, vinyldarkscratch commented
Looks like the "6" came from the original wiki tables, which I corrected for `MediaStreamAudioSourceNode` in #7935.  Seems like this was left untouched.  Fixing!

2021-06-10 20:10 UTC, foolip commented
Taking another look. This dictionary is only used in the `MediaStreamAudioSourceNode` constructor, so actually it should match https://developer.mozilla.org/en-US/docs/Web/API/MediaStreamAudioSourceNode/MediaStreamAudioSourceNode#browser_compatibility.

2021-06-11 04:25 UTC, vinyldarkscratch commented
Looking through the [commit history](https://trac.webkit.org/browser/webkit/trunk/Source/WebCore/Modules/webaudio/MediaStreamAudioSourceNode.idl?rev=150924#L1), I also see that the `mediaStream` argument was around since this API was first implemented, so I'd say we can fill in the data for it as well!

2021-06-11 10:10 UTC, foolip approved these changes

2021-06-11 10:10 UTC, merged

2021-06-11 10:12 UTC, foolip commented
Merged, but just a note that this is the evidence that the `mediaStream` dictionary member was supported from the beginning:
https://trac.webkit.org/browser/webkit/trunk/Source/WebCore/Modules/webaudio/MediaStreamAudioSourceOptions.idl?rev=265342

What you found was the `MediaStreamAudioSourceNode` interface, and it's totally possible for the interface to have an attribute without a corresponding member in the constructor init dict.