Three missing WebHID specs
mdn/browser-compat-data pull request #11040
Opened 2021-06-15 14:45 UTC by rachelandrew

The three missing WebHID interfaces, these are on \chrome desktop only: https://www.chromestatus.com/feature/5172464636133376

2021-06-16 10:03 UTC, Elchi3 approved these changes
Looks good to me. Just one question on status:

https://github.com/mdn/browser-compat-data/blob/main/api/HID.json is marked as experimental and non-standard. Is that wrong or should the data here be marked as such, too?

2021-06-16 10:04 UTC, Elchi3 commented
Same for navigator.hid in https://github.com/mdn/browser-compat-data/blob/main/api/Navigator.json#L1274

2021-06-16 20:26 UTC, foolip commented
@Elchi3, that is wrong, those are both in this spec: https://wicg.github.io/webhid/#enumeration

2021-06-16 20:35 UTC, foolip approved these changes
I can confirm this data using https://github.com/foolip/mdn-bcd-collector#updating-bcd-using-the-results.

I replaced all the values with false and ran the script, and that put back exactly the same data for Chrome and Edge. I didn't use results from Opera but running the mirroring script confirms it. That also revealed one entry not mirrored, left as a suggestion.

2021-06-16 20:35 UTC, foolip commented on api/HIDDevice.json
> +              "version_added": false
```suggestion
              "version_added": "75"
```

2021-06-16 20:40 UTC, foolip requested changes

2021-06-16 20:40 UTC, foolip commented on api/HIDConnectionEvent.json
> +          "experimental": false,
Per https://github.com/mdn/browser-compat-data/blob/main/docs/data-guidelines.md#choosing-an-experimental-status the experimental bits should be set to true.

2021-06-16 20:41 UTC, foolip commented on api/HIDConnectionEvent.json
> +          "experimental": false,
I've sent https://github.com/mdn/browser-compat-data/pull/11069 to make the existing entries match.

2021-06-17 07:54 UTC, rachelandrew commented
Updated these to mark as experimental, thanks both!

2021-06-17 07:57 UTC, foolip approved these changes
Thanks Rachel, looks great!

2021-06-17 07:58 UTC, merged