Add missing spec_url & mdn_url to TextTrack*.json
mdn/browser-compat-data pull request #11064
Opened 2021-06-16 13:12 UTC by teoli2003

A few spec_url and mdn_url were missing.

2021-06-16 19:45 UTC, foolip requested changes

2021-06-16 19:45 UTC, foolip commented on api/TextTrackList.json
> +          "mdn_url": "https://developer.mozilla.org/docs/Web/API/TextTrackList/onchange",
This URL is wrong.

2021-06-16 19:53 UTC, teoli2003 commented on api/TextTrackList.json
> +          "mdn_url": "https://developer.mozilla.org/docs/Web/API/TextTrackList/onchange",
oops. Fixed in next commit

2021-06-17 07:09 UTC, Elchi3 approved these changes

2021-06-17 07:09 UTC, merged