Updates edge to version 92
mdn/browser-compat-data pull request #11727
Opened 2021-07-24 16:30 UTC by lucalves

According to the [release notes](https://docs.microsoft.com/en-us/deployedge/microsoft-edge-relnote-stable-channel#version-92090255-july-22), Edge has been updated to version 92.

This PR keeps the `browsers/edge.json` file up to date.

Closes #11726.

2021-07-24 23:20 UTC, foolip commented on browsers/edge.json
> +        "94": {
Looks like checks are failing because this isn't closed.

2021-07-25 02:08 UTC, vinyldarkscratch requested changes
It appears a closing bracket was accidentally removed, but otherwise, this PR looks all good to me!

2021-07-25 02:08 UTC, vinyldarkscratch commented on browsers/edge.json
> +          "engine_version": "94"
```suggestion
          "engine_version": "94"
        }
```

2021-07-25 10:29 UTC, foolip approved these changes

2021-07-25 10:29 UTC, merged