Add Chrome/Safari versions for HTMLMediaElement API
mdn/browser-compat-data pull request #11745
Opened 2021-07-25 16:11 UTC by vinyldarkscratch

This PR adds real values for Chrome and Safari for the `HTMLMediaElement` API.  The data was copied from their event handler counterparts in `GlobalEventHandlers`.

2021-07-26 07:17 UTC, foolip commented
Copying data from `GlobalEventHandlers` isn't reliable if there are multiple events by that name, which is the case for "error" and probably others here.

Most of this is probably supported since the initial support for media elements, can you test the events manually to check?

2021-09-28 10:42 UTC, queengooborg commented
These are actually already set to the first browser editions when `HTMLMediaElement` was present!

2021-09-28 14:34 UTC, foolip commented
Only some of the data matches api.HTMLMediaElement itself. I'll leave a few comments as an example.

2021-09-28 14:40 UTC, foolip requested changes

2021-09-28 14:40 UTC, foolip commented on api/HTMLMediaElement.json
> +              "version_added": "10"
I doubt this is correct. The `MediaError` data says Chrome 1, and even though having `mediaElement.error` (which is a `MediaError`) without the "error" event is possible, I'm pretty sure they went together from the very start.

2021-09-28 14:40 UTC, foolip commented on api/HTMLMediaElement.json
> +              "version_added": "6"
This too doesn't seem plausible.

2021-09-28 14:40 UTC, foolip commented on api/HTMLMediaElement.json
> +              "version_added": "32"
I'm sure the "loadstart" was supported earlier than this just from memory.

2021-09-28 14:40 UTC, foolip commented on api/HTMLMediaElement.json
> +            "opera": [
This should be simplified if the right version for Chrome is found. No gap in support here.

2021-09-28 14:40 UTC, foolip commented on api/HTMLMediaElement.json
> +              "version_added": "32"
This also seems too late.

2021-09-30 17:06 UTC, foolip reviewed
"loadstart" event tracked down

2021-09-30 17:06 UTC, foolip commented on api/HTMLMediaElement.json
> +              "version_added": "32"
https://trac.webkit.org/changeset/36893/webkit is the patch that introduced the "loadstart" event. That was before the release of Chrome 1 by a few months, so let's assume:

```suggestion
              "version_added": "1"
```

2021-09-30 17:06 UTC, foolip commented on api/HTMLMediaElement.json
> +              "version_added": "32"
```suggestion
              "version_added": "1"
```

2021-09-30 17:06 UTC, foolip commented on api/HTMLMediaElement.json
> +              "version_added": "9"
```suggestion
              "version_added": "4"
```

Based on WebKit trunk version 528.4:
https://trac.webkit.org/changeset/36893/webkit
https://trac.webkit.org/browser/webkit/trunk/WebCore/Configurations/Version.xcconfig?rev=36893

2021-09-30 17:06 UTC, foolip commented on api/HTMLMediaElement.json
> +              "version_added": "9"
```suggestion
              "version_added": "3"
```

2021-09-30 17:10 UTC, foolip reviewed
"error" event researched...

2021-09-30 17:10 UTC, foolip commented on api/HTMLMediaElement.json
> +              "version_added": "≤4"
The "error" event was in the initial media element support in WebKit:
https://trac.webkit.org/browser/webkit/trunk/WebCore/html/HTMLMediaElement.cpp?rev=27277#L337

So:

```suggestion
              "version_added": "1.3"
```

2021-09-30 17:10 UTC, foolip commented on api/HTMLMediaElement.json
> +              "version_added": "≤3"
```suggestion
              "version_added": "1"
```

2021-09-30 17:12 UTC, foolip reviewed
And finally, "progress" event pinned down

2021-09-30 17:12 UTC, foolip commented on api/HTMLMediaElement.json
> +              "version_added": "32"
Yep, it was in the initial WebKit support:
https://trac.webkit.org/browser/webkit/trunk/WebCore/html/HTMLMediaElement.cpp?rev=27277#L452

```suggestion
              "version_added": "1"
```

2021-09-30 17:12 UTC, foolip commented on api/HTMLMediaElement.json
> +              "version_added": "32"
```suggestion
              "version_added": "18"
```

2021-09-30 17:12 UTC, foolip commented on api/HTMLMediaElement.json
> +            "opera": [
This should be simplified to just `"version_added": "≤12.1"`

2021-09-30 17:12 UTC, foolip commented on api/HTMLMediaElement.json
> +              "version_added": "9"
```suggestion
              "version_added": "1.3"
```

2021-09-30 17:12 UTC, foolip commented on api/HTMLMediaElement.json
> +              "version_added": "9"
```suggestion
              "version_added": "1"
```

2021-09-30 17:12 UTC, foolip commented on api/HTMLMediaElement.json
> +              "version_added": "2.0"
```suggestion
              "version_added": "1.0"
```

2021-09-30 17:12 UTC, foolip commented on api/HTMLMediaElement.json
> +              "version_added": "4.4.3"
```suggestion
              "version_added": "1"
```

2021-09-30 17:13 UTC, foolip commented on api/HTMLMediaElement.json
> +              "version_added": "2.0"
```suggestion
              "version_added": "1"
```

2021-09-30 17:14 UTC, foolip commented on api/HTMLMediaElement.json
> +              "version_added": "4.4.3"
```suggestion
              "version_added": "1"
```

2021-09-30 17:14 UTC, foolip commented on api/HTMLMediaElement.json
> +              "version_added": "≤37"
```suggestion
              "version_added": "1"
```

2021-09-30 17:18 UTC, foolip approved these changes

2021-09-30 17:18 UTC, foolip commented on api/HTMLMediaElement.json
> +              "version_added": "≤37"
```suggestion
              "version_added": "1"
```

2021-09-30 17:20 UTC, merged