Add Safari versions for api.NodeList.length
mdn/browser-compat-data pull request #11866
Opened 2021-08-01 16:34 UTC by vinyldarkscratch

This PR adds real values for Safari (Desktop and iOS/iPadOS) for the `length` member of the `NodeList` API, based upon results from the [mdn-bcd-collector](https://mdn-bcd-collector.appspot.com) project (v3.2.2).

Tests Used: https://mdn-bcd-collector.appspot.com/tests/api/NodeList/length

2021-08-02 01:49 UTC, lucalves approved these changes

2021-08-03 06:19 UTC, foolip requested changes

2021-08-03 06:19 UTC, foolip commented on api/NodeList.json
> +              "version_added": "≤4"
Can you set this to 1 to match the parent feature? This interface makes no sense without the `length` property.

2021-08-04 08:25 UTC, foolip approved these changes

2021-08-04 08:25 UTC, merged