Add Chrome/Safari versions for HashChangeEvent API
mdn/browser-compat-data pull request #11883
Opened 2021-08-02 15:40 UTC by vinyldarkscratch

This PR adds real values for Chrome and Safari for the `HashChangeEvent` API, based upon manual testing.

Test Code Used: ```js
if (location.hash === '#foobar') {
	location.hash = '#foo';
} else {
	location.hash = '#foobar';
}

window.addEventListener('hashchange', function(event) {
	alert(event.oldURL);
	alert(event.newURL);
});
```

2021-08-03 06:16 UTC, foolip requested changes

2021-08-03 06:16 UTC, foolip commented on api/HashChangeEvent.json
> +              "version_added": "≤15"
Can you test Presto while you have the test handy?

2021-08-10 12:32 UTC, foolip requested changes

2021-08-10 12:32 UTC, foolip commented on api/HashChangeEvent.json
> +              "version_added": "15"
Support for the event interface but none of the properties seemed suspect so I tested Opera 12.16 a bit. `document.createEvent('HashChangeEvent').newURL` is the empty string meaning this was supported in Presto.

2021-08-10 12:35 UTC, foolip commented on api/HashChangeEvent.json
> +              "version_added": "15"
Oh, and actually https://staging-dot-mdn-bcd-collector.appspot.com/tests/api/HashChangeEvent can test this now with your recent custom test additions.

2021-08-12 19:18 UTC, foolip commented on api/HashChangeEvent.json
> +              "version_added": "5.1"
This also doesn't quite match `onhashchange` data. Can you make bring them into alignment?

2021-08-21 11:45 UTC, vinyldarkscratch commented on api/HashChangeEvent.json
> +              "version_added": "8"
It was just a plain `Event` beforehand; same with Safari.

2021-08-22 06:13 UTC, foolip approved these changes

2021-08-22 06:13 UTC, merged