Fixes https://github.com/mdn/browser-compat-data/issues/11994
mdn/browser-compat-data pull request #11995
Opened 2021-08-13 16:56 UTC by ZhangYiJiang

#### Summary

Add partial implementation notes for Safari `InputEvent()` constructor 

#### Test results and supporting details

In Safari's console - 

```
> e = new InputEvent('beforeinput', { inputType: 'insertText' }) 
< InputEvent {isTrusted: false, inputType: "", data: null, dataTransfer: null, getTargetRanges: function, …}
> e.inputType
< ""
```

Compared to in Firefox 

``` 
> e = new InputEvent('beforeinput', { inputType: 'insertText' })
< beforeinput { target: null, isTrusted: false, isComposing: false, inputType: "insertText", detail: 0, layerX: 0, layerY: 0, which: 0, rangeOffset: 0, SCROLL_PAGE_UP: -32768, … }
> e.inputType
< "insertText"
``` 

https://bugs.webkit.org/show_bug.cgi?id=170416

#### Related issues

Fixes https://github.com/mdn/browser-compat-data/issues/11994

2021-08-18 13:23 UTC, ddbeck requested changes
Hi @ZhangYiJiang and thank your for this PR. I see that it's your first to the project—welcome!

I've got a few suggestions for you.

- Most important: this appears to apply to safari_ios as well. Can you copy your changes to that browser too?
- In a line comment, I've suggested some formatting changes.
- Optionally: if you prefer to help make this data richer, you could create an `inputEventInit_parameter` subfeature and report this in that subfeature. [See our parameter features guideline for more information](https://github.com/mdn/browser-compat-data/blob/main/docs/data-guidelines.md#parameters-and-parameter-object-features). This is optional, but if you'd like to do it, I'm happy to review the expansion to the data.

CI is failing with a couple of suggestions too (to use the preferred URL format and to use a string rather than array of strings for the note).

Thanks again for your help!

2021-08-18 13:24 UTC, ddbeck commented on api/InputEvent.json
> +                "Does not support inputEventInit parameter, see <a href='https://bugs.webkit.org/show_bug.cgi?id=170416'>bug 170416</a>"
```suggestion
                "The <code>inputEventInit</code> parameter is not supported. See <a href='https://bugs.webkit.org/show_bug.cgi?id=170416'>bug 170416</a>."
```

2021-08-22 21:50 UTC, ZhangYiJiang commented
I believe I've fixed the issues. I've opted not to create a subfeature because the `inputEventInit` is fairly integral to the feature itself - without it the constructor is almost entirely useless since the properties defined in `inputEventInit` are readonly and cannot be set on the object after initialization

2021-08-23 12:23 UTC, ddbeck approved these changes
Makes sense. Thank you, @ZhangYiJiang! 🎉

2021-08-23 12:23 UTC, merged