Bug 1614919 browser.identity.launchWebAuthFlow() exposes redirect_url
mdn/browser-compat-data pull request #12016
Opened 2021-08-16 19:07 UTC by rebloor

#### Summary
Added notes to:
* getRedirectURL regarding the use of a loopback address
* launchWebAuthFlow  noting the need for redirect_uri to be set to the URL returned by identity.getRedirectURL()

#### Test results and supporting details

Ran npm test, no issues found

#### Related issues
[Bug 1614919](https://bugzilla.mozilla.org/show_bug.cgi?id=1614919)

2021-08-17 18:37 UTC, Rob--W requested changes

2021-08-17 18:37 UTC, Rob--W commented on webextensions/api/identity.json
> +                  "notes": "The loopback address http://127.0.0.1/mozoauth2/[subdomain of URL returned by identity.getRedirectURL()] can be used as the redirect URL to enable the use of Google OAuth
This level of detail is too much. Let's refer to the inline documentation instead, like this:

```html
The <code>redirect_url</code> parameter now supports a loopback address, see <a href="https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/identity#getting_the_redirect_url">Getting the redirect URL</a>.
```

2021-09-01 20:58 UTC, Rob--W requested changes

2021-09-01 20:58 UTC, Rob--W commented on webextensions/api/identity.json
> +                  "notes": "The <code>redirect_url</code> parameter now supports a loopback address, see <a href='https://developer.mozilla.org/docs/Mozilla/Add-ons/WebExtensions/API/identity#getting
The `redirect_url` property belongs to the `launchWebAuthFlow` method, not here.

2021-09-01 20:58 UTC, Rob--W commented on webextensions/api/identity.json
>                    "version_removed": "63",
This is rendered incorrectly, as "Removed in 63 and later": https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/identity/launchWebAuthFlow#browser_compatibility

Could you change this to `"version_added": 63",` and note that the parameter is optional? It has the same meaning and would be rendered correctly.

2021-09-01 20:58 UTC, Rob--W commented on webextensions/api/identity.json
> +                  "notes": "The <code>redirect_uri</code> URL parameter must be set to the URL returned by <code>identity.getRedirectURL()</code>."
With the lot of comments about `redirect_url`, how about adding a new row? `redirect_url`.

Note that Chrome, Opera and Edge does not support the property; their documentation is at https://developer.chrome.com/docs/extensions/reference/identity/#type-WebAuthFlowDetails

2021-09-02 17:18 UTC, rebloor commented
@Rob--W Thanks for the feedback, would you like to confirm the changes are expected?

2021-09-02 20:08 UTC, Rob--W approved these changes
Looks great, thanks! In this form, it is very apparent that the `redirect_url` parameter has gone through several revisions.

2021-09-03 16:54 UTC, merged