Bug-1669566-Add-cookieStoreId-to-browser.downloads
mdn/browser-compat-data pull request #12069
Opened 2021-08-20 00:02 UTC by rebloor

Adds details of support for cookieStoreId to download.download, downloads.DownloadQuery, and downloads.DownloadItem. In addition, adds the missing properties for downloads.DownloadQuery. This provides compatibility data for [Bug 1669566](https://bugzilla.mozilla.org/show_bug.cgi?id=1669566).

npm test run and passed

Corresponding changes to MDN documentation are in [Bug 1669566 add cookie store id to browser.downloads #8106](https://github.com/mdn/content/pull/8106)

2021-08-25 11:04 UTC, Rob--W requested changes
We do generally not list each individual property of an API, but list one type (e.g. `DownloadsQuery`) and treat that as the baseline, followed by individual properties that have been added later. For example, the `cookies.Cookie` type has several properties, but the BCD only lists three entries: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/cookies/Cookie#browser_compatibility

I was hesitant to include lots of additional properties in the BCD for the downloads API, but after looking closer I figured that the state of support is very confusing, so individual entries are fine.

In terms of "support", there is a slight difference between unsupported and ignored.
When a parameter is not supported at all, the browser does not recognize the property and throws an error when used. E.g.:
- `browser.downloads.search({ unrecognizedProp: "dummy" });` would throw.
- `chrome.downloads.download({ url: "xxx", cookieStoreId: "0" })` would throw in Chrome and in older Firefox versions.

When a parameter is ignored, it may have a definition in the JSON schema that declares the API (https://searchfox.org/mozilla-central/rev/c8ea016b87997574e1ca9127a4c370032aa6ee79/toolkit/components/extensions/schemas/downloads.json), but the implementation may be missing. Despite the missing implementation, some basic validation may still be performed (e.g. if declared as `"type": "number"` and a non-number is passed, an error is thrown). For clarity, it may make sense to add a note to unsupported properties that the parameter is ignored, to distinguish it from completely unsupported types.

To make the distinction, use `partial_implementation` instead of `support: false`, as described in https://github.com/mdn/browser-compat-data/blob/main/docs/data-guidelines.md#partial_implementation-requires-a-note

2021-08-25 16:57 UTC, rebloor commented on webextensions/api/downloads.json
> +                  "version_added": "47"
Thanks, done

2021-08-25 16:57 UTC, rebloor commented on webextensions/api/downloads.json
> +                  "version_added": "47"
Thanks, done

2021-08-25 16:57 UTC, rebloor commented on webextensions/api/downloads.json
> +                  "notes": "Always given as 'safe'.",
Thanks, done

2021-08-30 19:09 UTC, rebloor commented
@Rob--W Do you want to do another review, or am I OK to merge?

2021-09-02 19:21 UTC, Rob--W approved these changes
Looks good, thanks.

2021-09-03 16:38 UTC, merged