Node.js SubtleCrypto does not require Secure context
mdn/browser-compat-data pull request #12154
Opened 2021-08-23 15:56 UTC by jasnell

#### Summary
Updates various Node.js Web API compatibilities

#### Test results and supporting details

#### Related issues

2021-08-23 16:30 UTC, lucacasonato reviewed
Ooh nice! Didn't know Node has WHATWG streams now. Such a great win for compat. I do think it is worth adding `"notes"` that the interfaces need to imported from "streams/web" + that they are marked as experimental in Node docs.

2021-08-23 16:30 UTC, lucacasonato commented on api/BroadcastChannel.json
> +            "version_added": "15.4.0",
I suggest you add a note that this needs to be imported from "worker_threads" and that it is experimental. That would align with how api.MessageChannel was documented prior to being available as a global.

2021-11-16 16:12 UTC, ddbeck requested changes
Thanks for this PR, @jasnell. Also, I see it's your first to the project—welcome!

I've got a few consistency suggestions in line comments, but no major concerns heree. Let me know if there are any questions. Thanks again!

2021-11-16 16:12 UTC, ddbeck commented on api/Blob.json
> +            "notes": "Experimental implementation. Must be imported using require('buffer').Blob or import { Blob } from 'buffer'."
It's not true everywhere, but often structure this information with `"alternative_name"`.

Additionally, notes can be an array. I'd suggest two separate notes here, for consistency with similar cases:

- `"Experimental implementation."`
- `"Must be imported from the <code>buffer</code> module."`

```suggestion
            "version_added": "15.7.0",
            "alternative_name": "buffer.Blob",
            "notes": "Experimental implementation. Must be imported using require('buffer').Blob or import { Blob } from 'buffer'."
```

2021-12-07 12:54 UTC, ddbeck commented
Hi @jasnell, sorry for the delay on the original review. Let me know if you plan to come back to this. If not, we can take over getting these changes merged. Thank you!

2021-12-07 22:49 UTC, jasnell commented
Yes, sorry, I do want to get this going! I missed the questions that were there.

2021-12-08 12:42 UTC, ddbeck approved these changes
Looks good. Thank you! 🎉

2021-12-08 12:43 UTC, merged