Include api.Share compatibility on Opera 77
mdn/browser-compat-data pull request #12223
Opened 2021-08-30 18:40 UTC by lucalves

#### Summary

According to #11989, Opera has version 77 compatibility for `api.Navigator.share`.

In this PR, compatibility for the version has been included.

#### Related issues

Fixes #11989.

2021-09-01 08:22 UTC, Elchi3 commented
Chrome support is version 89 which would map to Opera 75. https://github.com/mdn/browser-compat-data/blob/main/browsers/opera.json#L585. Can anyone confirm it is 75 instead of 77?

2021-09-04 06:54 UTC, vinyldarkscratch requested changes
Running some tests in BrowserStack, it looks like Opera Desktop implemented support the same time as Chrome Desktop has (confirmed by testing Opera 74, 75, and 76).  Let's change the version number to "75" accordingly!

2021-09-04 06:55 UTC, vinyldarkscratch commented on api/Navigator.json
> +              "version_added": "77"
```suggestion
              "version_added": "75"
```

2021-09-12 15:26 UTC, queengooborg approved these changes
Thanks for the quick fix, LGTM!  👍

2021-09-12 15:27 UTC, merged