HTTP WWW-Authenticate - add scheme and algorithm info
mdn/browser-compat-data pull request #12446
Opened 2021-09-17 04:55 UTC by hamishwillee

[WWW-Authenticate](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/WWW-Authenticate) and [Authorization](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Authorization) together are the HTTP headers used in the general [HTTP authentication framework](https://developer.mozilla.org/en-US/docs/Web/HTTP/Authentication). Note, compatibility for these should mirror each other.

Thing is, this is a framework, not a specific implementation. So saying that Firefox or whatever supports this in version X tells you very little. The useful compatibility information is 
- which authentication methods are supported - basic, digest, kerberos etc.
- within some authentication methods, which algorithms are supported.

What I have done here is a draft that attempts to start adding that information. I really don't want to go all the way with this, but I'd like to at least cover the methods supported by Firefox and Chrome, down to algorithm level. Right now this just starts the job for Firefox, since there is not much point me chasing this too far if BCD team disagree with this approach. 

What I know. 
- Firefox supports:  basic, digest (on all platforms), and ntlm and negotiate (kerberos) depending on whether OS support is available ([from here](https://bugzilla.mozilla.org/show_bug.cgi?id=472823#c49))
   - Firefox supports digest authentication with MD5 and SHA256 (from FF93). Not SHA 512.
   - Basic doesn't use any algorithms. I don't know about the other ones. 
- Chrome supports the same set, but it isn't clear what algorithms: https://www.chromium.org/developers/design-documents/http-authentication , and no OS restrictions other than Chrome OS are noted. 
- In addition to those schemes above [there are more listed here](https://developer.mozilla.org/en-US/docs/Web/HTTP/Authentication#authentication_schemes) - including HOBA, Mutual, Bearer, AWS4-HMAC-SHA256. I propose not to add info about support for those until yet, but people could add that if they knew something was supported.

Questions
- Is this approach acceptable? Should I keep going?
- The specs are giving me errors. How can I fix this?
- [Authorization](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Authorization) should mirror this. OK to just copy this when we're done?

Fixes #12370. Actually, it's a draft to help test whether the approach is reasonable.

2021-09-20 07:23 UTC, hamishwillee commented
@ddbeck If you could push this to someone that would be great.

2021-09-21 05:44 UTC, ashnicdill commented
NO please do not this isn't me!!!! This is not Ashley Dill that requested
this. I'm Ashley Dill. I don't know what any of this is. I only use my
Motorola phone with Google and Chrome. With my old phone and now probably
this one, that he hacked it and recorded Everytime I talked. This is a
major invasion of privacy. Please help. He could even record my screen and
may see these emails. My husband is very smart, knows how to build apps,
and I need to figure out how to make it stop. We have been separated for
months. He has never had permission to use my phone and I do believe has
access to 100% of it. I can't even change some settings. I bought this new
Motorola because he did the same thing to my last phone. Can someone help
me? Please? He owns a Windows computer and Samsung phone

On Fri, Sep 17, 2021, 12:56 AM Hamish Willee ***@***.***>
wrote:

> WWW-Authenticate
> <https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/WWW-Authenticate>
> and Authorization
> <https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Authorization>
> together are the HTTP headers used in the general HTTP authentication
> framework
> <https://developer.mozilla.org/en-US/docs/Web/HTTP/Authentication>. Note,
> compatibility for these should mirror each other.
>
> Thing is, this is a framework, not a specific implementation. So saying
> that Firefox or whatever supports this in version X tells you very little.
> The useful compatibility information is
>
>    - which authentication methods are supported - basic, digest, kerberos
>    etc.
>    - within some authentication methods, which algorithms are supported.
>
> What I have done here is a draft that attempts to start adding that
> information. I really don't want to go all the way with this, but I'd like
> to at least cover the methods supported by Firefox and Chrome, down to
> algorithm level. Right now this just starts the job for Firefox, since
> there is not much point me chasing this too far if BCD team disagree with
> this approach.
>
> What I know.
>
>    - Firefox supports: basic, digest (on all platforms), and ntlm and
>    negotiate (kerberos) depending on whether OS support is available (from
>    here <https://bugzilla.mozilla.org/show_bug.cgi?id=472823#c49>)
>       - Firefox supports digest authentication with MD5 and SHA256 (from
>       FF93). Not SHA 512.
>       - Basic doesn't use any algorithms. I don't know about the other
>       ones.
>    - Chrome supports the same set, but it isn't clear what algorithms:
>    https://www.chromium.org/developers/design-documents/http-authentication
>    , and no OS restrictions other than Chrome OS are noted.
>    - In addition to those schemes above there are more listed here
>    <https://developer.mozilla.org/en-US/docs/Web/HTTP/Authentication#authentication_schemes>
>    - including HOBA, Mutual, Bearer, AWS4-HMAC-SHA256. I propose not to add
>    info about support for those until yet, but people could add that if they
>    knew something was supported.
>
> Questions
>
>    - Is this approach acceptable? Should I keep going?
>    - The specs are giving me errors. How can I fix this?
>    - Authorization
>    <https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Authorization>
>    should mirror this. OK to just copy this when we're done?
>
> Fixes #12370 <https://github.com/mdn/browser-compat-data/issues/12370>.
> Actually, it's a draft to help test whether the approach is reasonable.
> ------------------------------
> You can view, comment on, or merge this pull request online at:
>
>   https://github.com/mdn/browser-compat-data/pull/12446
> Commit Summary
>
>    - WWW-Authenticate - add scheme and algorithm info
>
> File Changes
>
>    - *M* http/headers/www-authenticate.json
>    <https://github.com/mdn/browser-compat-data/pull/12446/files#diff-d9bf72366ec2cf6e18b07a6917e8ab5b434f08044641181b4c4ab2b9f4105a6d>
>    (340)
>
> Patch Links:
>
>    - https://github.com/mdn/browser-compat-data/pull/12446.patch
>    - https://github.com/mdn/browser-compat-data/pull/12446.diff
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/mdn/browser-compat-data/pull/12446>, or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AVNSNBSQ2NY4QZGTRV2RPYTUCLC65ANCNFSM5EGFWWCA>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>
>

2021-09-21 11:53 UTC, ddbeck commented
> * Is this approach acceptable? Should I keep going?

Yeah, this makes sense. A couple things to keep in mind: `partial_implementation` will probably apply to OS-specific limitations (e.g., some auth supported on Windows but not macOS or what have you). Notes will be needed.

One additional question at the end here, however.

> * The specs are giving me errors. How can I fix this?

The immediate cause of the failures is that URLs are missing fragments, for deep linking to the relevant portion of the spec.

That said, we typically use the https://datatrack.ietf.org/ URLs. And I didn't check whether the linked specs would validate. Also, the URL will need to be in [w3c/browser-specs](https://github.com/w3c/browser-specs) (there's a separate test for that at the end, after you've cleared the schema validation).

> * [Authorization](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Authorization) should mirror this. OK to just copy this when we're done?

I'm not decided on this yet, but why both? On initial reading, I was thinking, should this be on `Authorization` only, as that's the request header? I'm not sure what browsers are obligated to do with `WWW-Authenticate` responses. It might be easier to overlook these features on `WWW-Authenticate` and centralize what we know about browser behavior on `Authorization`. (That said, you're way ahead of me on how this stuff works, so if you say it's relevant to both, I'll defer to that.)

2021-11-01 01:34 UTC, hamishwillee commented
@ddbeck OK, I have created https://github.com/w3c/browser-specs/pull/420 to add specs for the https://www.rfc-editor.org/ cases.

Also created https://github.com/w3c/browser-specs/pull/421 for the Microsoft spec for [NTLM authentication](https://docs.microsoft.com/en-us/windows/win32/secauthn/microsoft-ntlm). Let's see how that goes.

2021-11-17 18:05 UTC, ddbeck requested changes

2021-11-17 18:05 UTC, ddbeck commented on http/headers/www-authenticate.json
> +            "spec_url": "https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-ntht/#published-version",
OK, it looks like we need to omit this here. See https://github.com/mdn/browser-compat-data/pull/13383#issuecomment-971825712.

We can still link to this spec from the MDN page if you like (e.g., from the specification section or see also section), but it's probably best to highlight that it's not a standard, exactly.

```suggestion
```

2021-11-19 04:21 UTC, hamishwillee commented
@ddbeck Happy days. NTLM spec removed and I have mirrored the WWW-authenticate to the Authorization header (changing the main spec url only).

Should be good to merge. 
After that, I'll update https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Authorization to use the spec_url.

2021-11-30 11:57 UTC, ddbeck approved these changes
Thank you! 🎉

2021-11-30 11:57 UTC, merged