Move the performance attribute to api.performance (in _globals)
mdn/browser-compat-data pull request #12462
Opened 2021-09-17 08:10 UTC by foolip

This was missed in https://github.com/mdn/browser-compat-data/pull/11518.

This is defined using WindowOrWorkerGlobalScope in the spec:
https://w3c.github.io/hr-time/#the-performance-attribute

None of the data was validated or changed, just moved.

2021-09-17 08:12 UTC, foolip commented
@Elchi3 could I tempt you into preparing the content-side change for this, since you already did a whole lot of these and know all the bits to update?

2021-09-17 08:52 UTC, Elchi3 commented
I'm happy to help with the content work on this one but it runs into the problem that I ran into with `crypto`: The namespace is already occupied. (see https://github.com/mdn/browser-compat-data/pull/11518#issuecomment-906336064)

Here, `performance` also conflicts with the interface: https://developer.mozilla.org/en-US/docs/Web/API/Performance

2021-09-17 08:53 UTC, Elchi3 commented on api/_globals/performance.json
> +        "mdn_url": "https://developer.mozilla.org/docs/Web/API/performance",
This MDN URL is already taken. Can't move this global there.

2021-09-17 08:56 UTC, foolip commented
Oh, I didn't realize this would happen, that MDN URLs are case-insensitive... any ideas for how to resolve this?

2021-09-17 09:00 UTC, Elchi3 commented
> Oh, I didn't realize this would happen, that MDN URLs are case-insensitive... any ideas for how to resolve this?

No yet. One could have an MDN URL like `performance_global`. Other ideas?

2021-09-17 09:25 UTC, foolip commented
Could we disambiguate "Performance (interface)" and "performance (property)" Wikipedia-style? One of them should probably be very minimal and just link to the other.

2021-09-17 12:00 UTC, Elchi3 commented
I'm not a big fan of disambiguation pages. I think the current Performance (interface) page is great and having a disambiguation in its place wouldn't be ideal, imo. Or where do you propose that such disambiguation would happen?

2021-09-17 12:48 UTC, foolip commented
I agree the page with all the `Performance` members is the best place to land. How about https://developer.mozilla.org/en-US/docs/Web/API/Performance stays the same but https://developer.mozilla.org/en-US/docs/Web/API/performance_property is added?

Perhaps more radical would be to just have one page and not use the BCD for `api.performance` at all, since it should match `api.Performance`.

2021-09-17 13:14 UTC, Elchi3 commented
> I agree the page with all the `Performance` members is the best place to land. How about https://developer.mozilla.org/en-US/docs/Web/API/Performance stays the same but https://developer.mozilla.org/en-US/docs/Web/API/performance_property is added?

I think this is a good idea.

2021-09-20 14:50 UTC, Elchi3 requested changes

2021-09-20 14:50 UTC, Elchi3 commented on api/_globals/performance.json
> +        "mdn_url": "https://developer.mozilla.org/docs/Web/API/performance",
```suggestion
        "mdn_url": "https://developer.mozilla.org/docs/Web/API/performance_property",
```

2021-09-21 05:34 UTC, ashnicdill commented
I never requested this either. I only use my Motorola phone. I think he
somehow copied my sim card and that's how he is controlling everything.
I've changed it before, got a new phone. This is a major invasion of
privacy and this needs to stop. My husband is very smart, knows how to
build apps, and I need to figure out how to make it stop. We have been
separated for months. He has never had permission to use my phone and I do
believe has access to 100% of it. I can't even change some settings. I
bought this new Motorola because he did the same thing to my last phone.
Can someone help me? Please? Also, can I please get some type of proof
where this is coming from because it isn't me!!

On Fri, Sep 17, 2021, 4:11 AM Philip Jägenstedt ***@***.***>
wrote:

> This was missed in #11518
> <https://github.com/mdn/browser-compat-data/pull/11518>.
>
> This is defined using WindowOrWorkerGlobalScope in the spec:
> https://w3c.github.io/hr-time/#the-performance-attribute
>
> None of the data was validated or changed, just moved.
> ------------------------------
> You can view, comment on, or merge this pull request online at:
>
>   https://github.com/mdn/browser-compat-data/pull/12462
> Commit Summary
>
>    - Move the performance attribute to api.performance (in _globals)
>
> File Changes
>
>    - *M* api/Window.json
>    <https://github.com/mdn/browser-compat-data/pull/12462/files#diff-0af204b45434f45eda843193144af2351b8c5ff07903ac29ba5aae047195ba25>
>    (52)
>    - *M* api/WorkerGlobalScope.json
>    <https://github.com/mdn/browser-compat-data/pull/12462/files#diff-c78cc8160c2d062b94b0d0328ea14a10a2060f39753acad1aa16038ea46e65bb>
>    (52)
>    - *A* api/_globals/performance.json
>    <https://github.com/mdn/browser-compat-data/pull/12462/files#diff-1407dea7f82ccfa0f9ee7987feb7c4f9dec71a0a5487a6899019794b8bd94e58>
>    (107)
>
> Patch Links:
>
>    - https://github.com/mdn/browser-compat-data/pull/12462.patch
>    - https://github.com/mdn/browser-compat-data/pull/12462.diff
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/mdn/browser-compat-data/pull/12462>, or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AVNSNBXLN3II2XPQ54HZP73UCLZ3FANCNFSM5EGOQSRQ>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>
>

2021-09-24 14:28 UTC, foolip commented
@Elchi3 do you think this change would be trivial on the MDN side, or is something novel needed for the first some_property page?

2021-09-27 08:28 UTC, Elchi3 commented
I've exercised the change in https://github.com/mdn/content/pull/9279. I think it could work as proposed.

2021-09-29 07:28 UTC, Elchi3 approved these changes
Content work was merged. Lets do this

2021-09-29 07:28 UTC, merged