Mark Safari iOS 15 as current version
mdn/browser-compat-data pull request #12499
Opened 2021-09-20 18:49 UTC by lukewarlow

#### Summary

iOS 15 has been released which includes Safari 15. This MR sets 15 as the current Safari iOS version.

#### Test results and supporting details

2021-09-20 20:08 UTC, lukewarlow commented
The release notes unfortunately haven't been updated yet, and still refer to it as beta.

2021-09-21 07:46 UTC, queengooborg commented on browsers/safari.json
> +          "engine_version": "612.1.29.41.4"
```suggestion
          "engine_version": "612.1.29"
```

2021-09-21 07:47 UTC, queengooborg requested changes
Thanks for taking care of this!  Can we simplify the engine version to just the major, minor, and patch versions?  (I know Safari 14.1 has the micro and nano versions, but this is actually causing problems with our mirroring script.)

2021-09-21 07:47 UTC, queengooborg commented on browsers/safari.json
> +          "engine_version": "612.1.29.41.4"
```suggestion
          "engine_version": "612.1.29"
```

2021-09-21 07:47 UTC, queengooborg commented on browsers/safari_ios.json
> +          "engine_version": "612.1.29.41.4"
```suggestion
          "engine_version": "612.1.29"
```

2021-09-21 08:41 UTC, queengooborg approved these changes

2021-09-21 08:41 UTC, merged