Add MediaTrackConstraints.resizeMode
mdn/browser-compat-data pull request #12563
Opened 2021-09-24 12:01 UTC by valkum

#### Summary

This PR adds the MediaTrackConstraint resizeMode to the compat data.
It also updates the supported constraints entry for chrome (https://www.chromestatus.com/feature/6206218032906240)

#### Test results and supporting details

https://www.chromestatus.com/feature/6206218032906240
https://bugzilla.mozilla.org/show_bug.cgi?id=1433480
https://wpt.fyi/results/mediacapture-streams/MediaStreamTrack-getSettings.https.html?label=experimental&label=master&aligned

#### Related issues

Fixes #12562

2021-11-30 17:07 UTC, ddbeck requested changes
Hi @valkum and thanks for this PR. I see it's your first to the project—welcome!

It's very likely these changes extend to the Chrome-derived browsers. On the first file, I've made some line comments illustrating the mapping from Chrome to the other browsers. If you wouldn't mind applying those changes to the other files, then we could merge this.

Thank you again!

2021-11-30 17:07 UTC, ddbeck commented on api/MediaTrackConstraints.json
> +              "version_added": false
```suggestion
              "version_added": "60"
```

2021-11-30 17:07 UTC, ddbeck commented on api/MediaTrackConstraints.json
> +              "version_added": false
```suggestion
              "version_added": "51"
```

2021-11-30 17:07 UTC, ddbeck commented on api/MediaTrackConstraints.json
> +              "version_added": false
```suggestion
              "version_added": "11.0"
```

2021-11-30 17:07 UTC, ddbeck commented on api/MediaTrackConstraints.json
> +              "version_added": false
```suggestion
              "version_added": "72"
```

2021-11-30 17:07 UTC, ddbeck commented on api/MediaTrackConstraints.json
> +              "version_added": false
```suggestion
              "version_added": "72"
```

2021-12-07 15:54 UTC, valkum commented
I included your changes. For opera_android I could not find any release notes so I just need to take that for granted. I verified the rest of the release notes for the chromium engine version. The first chromium edge version was 79, I changed that accordingly.

2022-01-29 08:23 UTC, queengooborg approved these changes
Awesome, thank you for applying the changes!  This is LGTM to me -- welcome to BCD!  🎉

2022-01-29 08:23 UTC, merged