Add entry for `input-security` CSS property
mdn/browser-compat-data pull request #12822
Opened 2021-10-12 18:03 UTC by lukewarlow

#### Summary

Added an entry for the [`input-security`](https://drafts.csswg.org/css-ui/#input-security) CSS property.

#### Test results and supporting details

https://webkit.org/blog/11975/release-notes-for-safari-technology-preview-133/#:~:text=Added%20support%20for%20input-security - Safari TP ~~supposedly supports this property but I and someone else haven't been able to get it working so have left as false for now.~~ As of TP 134 this is now working so I've added it.

WebKit bug (implemented): https://webkit.org/b/184510

Firefox bug (in progress): https://bugzil.la/1735384

Chromium bug: https://crbug.com/1253732

#### Related issues

Fixes https://github.com/mdn/browser-compat-data/issues/12664

Related to mdn/content#9422

2021-11-15 11:42 UTC, Elchi3 requested changes
This PR should remove the -webkit-text-security file (and add it to input-security as and old alias).
https://github.com/mdn/browser-compat-data/blob/main/css/properties/-webkit-text-security.json

See also https://github.com/mdn/content/issues/10438

2021-11-15 12:09 UTC, lukewarlow commented
It's not actually an alias of that property, as can be seen by its WebKit implementation.

2021-11-22 08:21 UTC, Elchi3 commented
I asked in https://github.com/mdn/content/issues/10438 if we want one feature page here or if we should keep them separate.

2022-01-18 10:02 UTC, Elchi3 commented
Removing my review request. Need info as requested in https://github.com/mdn/content/issues/10438#issuecomment-1014710035

2022-01-29 08:20 UTC, queengooborg commented
Marking as "not ready" since this seems to be blocked on info needed for the content PR.

2022-03-27 13:04 UTC, lukewarlow commented
Looks like Safari has put this behind a flag for now https://github.com/WebKit/WebKit/commit/bed3cc8a73bd94b0061e87ba313baa5506a136ac

2022-03-27 13:05 UTC, lukewarlow commented
And sounds like the CSSWG might drop the property from the spec entirely. https://github.com/w3c/csswg-drafts/issues/6788

2022-03-27 13:05 UTC, lukewarlow commented
Given the above two points, and the lack of movement on the blocking discussion for this PR, I'm gonna go ahead and close it for now.

2022-03-27 13:05 UTC, closed without merging