Add insertable stream interfaces.
mdn/browser-compat-data pull request #13126
Opened 2021-10-26 19:15 UTC by jpmedley

#### Summary
Adds data for [MediaStreamTrack Insertable Streams (a.k.a. Breakout Box)](https://www.chromestatus.com/feature/5499415634640896)

#### Test results and supporting details

Evidence of Chrome's support is in the link above. I ran this through [BCD Collector](https://github.com/foolip/mdn-bcd-collector) and found no additional results.

#### Related issues
Addresses: https://github.com/mdn/content/issues/9852

2021-11-03 20:00 UTC, queengooborg requested changes
Looking good, thank you!  Just got a couple of changes to request (these apply to every member in both files), and then I'd say this will be ready to go!

2021-12-05 15:35 UTC, queengooborg commented
Hey @jpmedley, do you plan to return to this PR?

2021-12-06 15:25 UTC, jpmedley commented
I'm stuck. The spec got moved to a private repo. They keep telling me they're moving it back, but it keeps getting delayed.

2021-12-06 16:12 UTC, queengooborg commented
We can skip over adding a spec URL for the time being until it's been moved, and just focus on the version data for now!

2021-12-06 20:28 UTC, jpmedley commented
Sounds good to me.

2021-12-07 13:00 UTC, ddbeck commented
One additional request here: if the spec is unpublished, we should set `standard_track` to `false` until there's something public. Mostly to encourage good behavior on the part of spec authors. 😈

2021-12-07 20:38 UTC, jpmedley commented
Done.

2021-12-08 04:09 UTC, Ansexysoso commented
Hi please help me

ในวันที่ พ. 8 ธ.ค. 2021 03:38 Joe Medley ***@***.***>
เขียนว่า:

> Done.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/mdn/browser-compat-data/pull/13126#issuecomment-988247930>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AWGYMAYWVMCVU7YXSSV673DUPZWGBANCNFSM5GYRZ2AQ>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>
>

2021-12-08 18:16 UTC, queengooborg commented on api/MediaStreamTrackGenerator.json
> +            "version_added": false
The data for Edge and Opera also need to be mirrored to all of the subfeatures.  :)

2021-12-08 20:12 UTC, jpmedley commented
Done. Sorry about that.

2021-12-14 12:48 UTC, queengooborg requested changes
Just two last little changes, and this'll be ready to go!

2021-12-14 12:48 UTC, queengooborg commented on api/MediaStreamTrackProcessor.json
> +              "version_added": false
```suggestion
              "version_added": "94"
```

2021-12-14 12:48 UTC, queengooborg commented on api/MediaStreamTrackProcessor.json
> +              "version_added": false
```suggestion
              "version_added": "80"
```

2021-12-15 00:38 UTC, queengooborg approved these changes
LGTM, thanks!

2021-12-15 00:38 UTC, merged