adding at layer rule
mdn/browser-compat-data pull request #13137
Opened 2021-10-27 10:21 UTC by Rumyra

#### Summary

Adding the `@layer` rule for CSS which is available under a flag in both Chrome (97) and Firefox (94)

#### Test results and supporting details

It doesn't like the spec url I have added - I'm not sure how to resolve this

The only thing I got is this https://bugzilla.mozilla.org/show_bug.cgi?id=1699217 - but I've written some code which works in both browsers with the flags turned on

#### Related issues

https://github.com/mdn/content/issues/9369

2021-12-05 15:48 UTC, queengooborg requested changes
Thanks for your PR, apologies for the delay before reviewing!  Let's use the track release spec to make the browser spec linter happy.

2021-12-05 15:48 UTC, queengooborg commented on css/at-rules/layer.json
> +          "spec_url": "https://drafts.csswg.org/css-cascade-5/#layering",
```suggestion
          "spec_url": "https://www.w3.org/TR/css-cascade-5/#layering",
```

2021-12-05 15:48 UTC, queengooborg commented on css/at-rules/layer.json
> +                  "name": "enable-cascade-layers",
```suggestion
                  "name": "#enable-cascade-layers",
```

Can we also copy this flag data over to Chrome Android, Edge, and Opera?

2021-12-05 15:51 UTC, queengooborg commented
Wait, actually, I just noticed this is a duplicate of #12489.  I'm going to close this in favor of that PR.

2021-12-05 15:51 UTC, closed without merging

2021-12-06 12:05 UTC, Rumyra commented
OK that's brill :D thanks @queengooborg