menus.OnClickedData.srcUrl returned post-redirect URL
mdn/browser-compat-data pull request #13259
Opened 2021-11-02 16:00 UTC by rebloor

#### Summary

Add details for the `srcUrl` property to `menus.OnClickedData` including a note that between versions 59 and 94 it incorrectly returned the post-redirect URL rather than the `<img src>` value.

#### Test results and supporting details

`npm test` executed with no errors

#### Related issues

Provide complementary browser compatibility data for [menus.OnClickedData.srcUrl returns <img src> #10214](https://github.com/mdn/content/pull/10214) which addresses the documentation requirements for [Bug 1659155](https://bugzilla.mozilla.org/show_bug.cgi?id=1659155).

2021-11-02 16:55 UTC, Rob--W requested changes

2021-11-02 16:55 UTC, Rob--W commented on webextensions/api/menus.json
> +                    "notes": "Returns a post-redirect URL rather than the raw <code>&lt;img src&gt;<code> value."
Not limited to `<img src>`, please make this more generic. See https://github.com/mdn/content/pull/10214#pullrequestreview-795673940

2021-11-03 16:10 UTC, Rob--W approved these changes
Once merged, double-check on MDN (after a week?) whether the rendered compat table matches with the intended message. I vaguely recall that the use of `version_removed` used to render as something different than what I meant.

2021-11-03 17:46 UTC, rebloor commented
@Rob--W I have a similar recollection, will check

2021-11-03 17:47 UTC, merged

2021-11-26 15:37 UTC, rebloor commented
@Rob--W 
> Once merged, double-check on MDN (after a week?) whether the rendered compat table matches with the intended message. I vaguely recall that the use of version_removed used to render as something different than what I meant.
There is still an inconsistency:
<img width="1534" alt="image" src="https://user-images.githubusercontent.com/7352080/143603834-dda351bb-d4da-48c8-b0d8-05b8ab6b803b.png">
but confirm there is a Yari issue for this (Feature removals in BCD use a misleading version range [#3971](https://github.com/mdn/yari/issues/3971).)