Add Safari for iOS WebExtensions Tab API data
mdn/browser-compat-data pull request #13441
Opened 2021-11-10 19:56 UTC by jdatapple

#### Summary
Includes Safari for iOS support of WebExtensions Tab API.

#### Test results and supporting details
Reviewed internally with Safari engineers.

See ["Web Extensions" section in the Safari 15 Release Notes](https://developer.apple.com/documentation/safari-release-notes/safari-15-release-notes#Web-Extensions).

2021-11-10 20:02 UTC, jdatapple commented
I believe the linter failure here may be a bug in the linter.

2021-11-12 14:42 UTC, Elchi3 requested changes
The linting error isn't helpful at all. I don't really get it.

However, if you add the missing safari_ios to PageSettings.marginTop (line 468) the error is gone.

2021-11-16 19:23 UTC, jdatapple commented
@

> The linting error isn't helpful at all. I don't really get it.
> 
> However, if you add the missing safari_ios to PageSettings.marginTop (line 468) the error is gone.

I got lost in the file and couldn't find the missing entry. Thank you!

2021-11-17 11:53 UTC, Elchi3 approved these changes

2021-11-17 11:53 UTC, merged