Performance.measure() - subfeature for old spec return value
mdn/browser-compat-data pull request #13478
Opened 2021-11-12 04:59 UTC by hamishwillee

Fixes #13418

Performance.measure() had a spec change from returning `undefined` to returning a `PerformanceMeasure` object. Firefox still returns old value, Chrome 95 and Safari 15 have been updated - according to #13418.

This handles the case in the same way as  #13236 - it created a subfeature for the deprecated behaviour called `undefined`. Note that Opera for Android and samsunginternet_android are still on version 92 so have not been updated. 
I DO NOT know about deno.

2021-11-14 22:02 UTC, hamishwillee commented
@ddbeck FYI, this is just like the spec change we recently did for `SpeechSynthesisEvent.elapsedTime` - so handled in the same way - with a subfeature for the old behaviour that is version removed as the browsers are updated.

2021-11-18 07:43 UTC, hamishwillee commented
Thanks. I'll remember that for next time. I definitely prefer "returns"

2021-11-18 11:15 UTC, ddbeck requested changes
Sorry, Hamish. I goofed on the Deno question.

2021-11-18 11:15 UTC, ddbeck commented on api/Performance.json
> +                "version_added": "1.2"
Oh wait, I got this completely backwards. Deno _always_ returned a `PerformanceMeasure`, not the other way around.

```suggestion
                "version_added": false
```

2021-11-18 23:39 UTC, hamishwillee commented on api/Performance.json
> +                "version_added": "1.2"
I was a bit confused by that :-). Accepted

2021-11-30 11:54 UTC, ddbeck approved these changes
Looks good. Thank you! 🎉

2021-11-30 11:54 UTC, merged