Update supported platforms for BarcodeDetector in Chrome
mdn/browser-compat-data pull request #13805
Opened 2021-11-29 18:49 UTC by reillyeon

#### Summary
As of Chrome 98 the BarcodeDetector interface will be supported on all desktop platforms.

The implementation on these platforms is not part of the Chromium project and so support in other Chromium-based browsers is unchanged.

#### Test results and supporting details
https://chromium-review.googlesource.com/c/chromium/src/+/3290206

#### Related issues
Fixes #13752.

2021-11-30 18:29 UTC, ddbeck requested changes
Thanks for this PR, @reillyeon. I see it's your first to the project. Welcome!

A couple thoughts on this one:

1. The structure here will need to change. Rather than changing the note, we'll need to show the change with two support statements, as in this form:

   ```json
   [
     {
       "version_added": "98"
     },
     {
       "version_added": "83",
       "version_removed": "98",
       "partial_implementation": true,
       "notes": "Supported on macOS only."
     }
   ]
   ```

1. It's probably just a little early to land this PR. Historically, there's been a little reluctance to land Chrome Canary data, while beta tends to have a better track record of shipping as expected.

2022-01-29 08:19 UTC, queengooborg commented
Hi @reillyeon!  We haven't heard from you in a while -- do you plan to update this PR based upon the suggestions above?

2022-01-29 08:24 UTC, reillyeon commented
Yes, I was a little early in posting this change but plan to update it soon.

2022-02-02 07:35 UTC, foolip approved these changes
Thanks @reillyeon!

2022-02-02 07:36 UTC, foolip commented
I'll hold off merging and defer to @ddbeck since he requested changes in an earlier review.

2022-02-15 18:14 UTC, ddbeck approved these changes
Looks good. Thank you! 🎉

2022-02-15 18:14 UTC, merged