FF96 webp supported for Canvas todataurl/blob
mdn/browser-compat-data pull request #13897
Opened 2021-12-07 01:12 UTC by hamishwillee

FF96 adds support for a webp encoder https://bugzilla.mozilla.org/show_bug.cgi?id=1511670
This can be used in [HTMLCanvasElement.toDataURL()](https://developer.mozilla.org/en-US/docs/Web/API/HTMLCanvasElement/toDataURL) and [HTMLCanvasElement.toBlob()](https://developer.mozilla.org/en-US/docs/Web/API/HTMLCanvasElement/toBlob) to putput webp.

The spec requires support only for the png format (used by default and as a fallback). Nothing in the spec that says a browser must support any other format. 

However it is useful to know about what formats are supported. So this PR is a test to see the gods of BCD will allow reporting supported types as a subfeature and help me update this. 
- I know chrome supports toDataUrl , and I think from M17 https://bugs.chromium.org/p/chromium/issues/detail?id=63221 - Note that this is pre-Blink engine, which makes mapping to other versions hard.
- FF96 supports
- IE does not.
- Current Opera and Edge do too. However not clear when this would have gone in.
- No idea about the others

For toBlob, I know that support went in for Chrome 50 for the method, by which time webp was supported. So we can assume Blink mappings for the others.

Thoughts?

PS, my test html page for toDataURL support is
```html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Canvas - toData</title>
  </head>
  <body>
  <p>Canvas toDataURL</p>
<canvas id="canvas"></canvas>
<script>
lets ctx = canvas.getContext("2d");
ctx.fillStyle = "red";
ctx.fillRect(0, 0, 8, 8);

const webp = canvas.toDataURL("image/webp"); // Chrome only?
const png  = canvas.toDataURL("image/png");
const jpg  = canvas.toDataURL("image/jpeg");

console.log(webp.length, webp); //  263 byte
console.log(png.length, png);   // 1918 byte
console.log(jpg.length, jpg);   // 1938 byte

document.body.appendChild(new Image).src = webp;
document.body.appendChild(new Image).src = png;
document.body.appendChild(new Image).src = jpg;
</script>
  </body>
</html>
```

2021-12-07 01:13 UTC, hamishwillee commented on api/HTMLCanvasElement.json
> +              "standard_track": true,
Not sure about this. The standard says nothing about the use of particular image formats other than png

2021-12-09 09:01 UTC, ddbeck requested changes
Thanks, Hamish. Several suggestions for you. Happy to see this stuff follow to the other methods.

2021-12-09 09:01 UTC, ddbeck commented on api/HTMLCanvasElement.json
> +            "description": "<code>type</code> parameter <code>image/webp</code>",
```suggestion
            "description": "<code>type</code> parameter supports <code>\"image/webp\"</code>",
```

2021-12-10 01:42 UTC, hamishwillee commented
thanks very much @ddbeck . I've accepted all your changes and rolled out the same/similar pattern to the other two methods. Ready for your re-review.

2021-12-14 17:00 UTC, ddbeck approved these changes
Looks good. Thank you! 🎉

2021-12-14 17:00 UTC, merged