HTTP Clear-Site-Data cache is behind pref
mdn/browser-compat-data pull request #13974
Opened 2021-12-13 00:10 UTC by hamishwillee

Fixes #13942

The `cache` was removed behind a pref in FF94: https://bugzilla.mozilla.org/show_bug.cgi?id=1671182

The fix marks versions support as partial. It also removes the old version and adds a (partial) support behind a pref for FF94.
Note that the reasons why support is partial were not detailed so I have not added notes about that. Might reasonably add bug link if you wished?

2021-12-14 17:06 UTC, ddbeck requested changes
Thanks, Hamish. One nit in a line comment.

 I think for the partials here, either we need to specify what's incomplete about the implementation. Looking at things you've linked to (and the BCD bug besides), I'm not sure there's anything obviously incomplete about it, so maybe just get rid of the partial here?

2021-12-14 17:06 UTC, ddbeck commented on http/headers/clear-site-data.json
> +                      "name": "#privacy.clearsitedata.cache.enabled",
Firefox doesn't use the hash notation

```suggestion
                      "name": "privacy.clearsitedata.cache.enabled",
```

2021-12-14 21:42 UTC, hamishwillee commented
Thanks! I've made the change you suggested. You're right that it is not clear why this is "partial" or not. The bugs do mention that this is moved behind the preference because the spec is unclear and perhaps they went too early with the implementation. From which I infer our implementation is "somewhat complete". Anyway, as we can't characterise that, happy to remove the markup.

2021-12-16 08:00 UTC, ddbeck approved these changes
Looks good. Thank you! 🎉

2021-12-16 08:00 UTC, merged

2024-11-30 21:14 UTC, KakaNguyen86vn approved these changes