CSS hyphenate-character property - add
mdn/browser-compat-data pull request #14488
Opened 2022-01-10 06:17 UTC by hamishwillee

FF97 adds support for the CSS `hyphenate-character` property https://bugzilla.mozilla.org/show_bug.cgi?id=1746187 behind a preference. I've added that for FF97, but not for FF97 on android.

Now Chrome supports this with a -webkit extension, so I added that as well. BUT I am not sure exactly what versions to put. 
I found it works fine to specify a value (`=`) say for back to Chrome 45, but in Chrome 44 the CSS doesn't seem to understand the "=" char - so the rendered character appears as a box. In other words it isn't clear if it doesn't work or if = just doesn't work.

![image](https://user-images.githubusercontent.com/5368500/148724761-5420f02d-ea9d-40cf-95b5-5e91eac8cf64.png)

Anyway, Safari has the same problem on current versions as the very old chrome, so I put that as false.

I just extended the other things to match chrome versions if appropriate. 

Thoughts on next steps?

2022-01-10 07:35 UTC, hamishwillee commented on css/properties/hyphenate-character.json
> +            "experimental": false,
False because of the webkit prefix thingy

2022-01-11 16:15 UTC, ddbeck commented
Is the character oddity from the example in https://github.com/mdn/content/pull/11875? I think it might be an issue with the character, not the CSS. See https://github.com/mdn/content/pull/11875/files#r782305961

2022-01-14 01:09 UTC, hamishwillee commented
@ddbeck Yes it is. With the * instead of = char it works back to Chrome v37, which is as far as browserstack will let me go back. I've put v37 and associated versions in place, but not sure what to do now if we can't test earlier?

I won't get to this again until back from holiday.

2022-01-18 13:30 UTC, ddbeck requested changes

2022-01-18 13:30 UTC, ddbeck commented on css/properties/hyphenate-character.json
> +              "version_added": "37"
Finally, a chance to exercise my ancient browser research skills. Here's how I did it:

1. If you switch operating systems, you can go back to Chrome 15 or so on BrowserStack. It works there, which gets us in the range of Chromium releases which used WebKit (before Blink emerged). Range narrowed to Chrome 1-15.
2. I tested it in older Safaris to rough things out a little more. It shows up in Safari 5.1 (WebKit ~534.48). This puts us in the range of Chrome 1-12, based on WebKit version mapping (i.e., it wouldn't have shown up any later than the Chrome that ships WebKit 534.48 or greater).
3. I searched [webkit/webkit](https://github.com/webkit/webkit) to find the changset that added it: https://trac.webkit.org/changeset/61548/webkit. This dates the change to circa June 2010, narrowing things to Chrome 6-12.
4. A comment in [the associated WebKit bug](https://bugs.webkit.org/show_bug.cgi?id=10228) mentions a Chromium performance regression. This suggests that Chrome was updating WebKit versions pretty promptly. Based on the date, I think we can safely assume Chrome 6. But just to be sure, the we can compare [WebKit tags](https://trac.webkit.org/browser/webkit/tags) to the revision number, which places this around WebKit 534.1, which also aligns with Chrome 6.

```suggestion
              "version_added": "6"
```

Updating the rest of the values is an exercise in version mapping.

2022-01-18 13:30 UTC, ddbeck commented on css/properties/hyphenate-character.json
> +              "version_added": "37"
```suggestion
              "version_added": "18"
```

2022-01-18 13:30 UTC, ddbeck commented on css/properties/hyphenate-character.json
> +              "prefix": "-webkit-"
```suggestion
              "prefix": "-webkit-",
              "version_added": "15"
```

2022-01-18 13:30 UTC, ddbeck commented on css/properties/hyphenate-character.json
> +              "version_added": "24"
```suggestion
              "version_added": "14"
```

2022-01-18 13:30 UTC, ddbeck commented on css/properties/hyphenate-character.json
> +              "version_added": false
```suggestion
              "prefix": "-webkit-",
              "version_added": "5.1"
```

2022-01-18 13:30 UTC, ddbeck commented on css/properties/hyphenate-character.json
> +              "version_added": false
```suggestion
              "prefix": "-webkit-",
              "version_added": "5"
```

2022-01-18 13:30 UTC, ddbeck commented on css/properties/hyphenate-character.json
> +              "version_added": "3.0"
```suggestion
              "version_added": "1.0"
```

2022-01-18 13:30 UTC, ddbeck commented on css/properties/hyphenate-character.json
> +              "version_added": "37"
```suggestion
              "version_added": "≤37"
```

2022-01-31 01:52 UTC, hamishwillee commented
Thanks @ddbeck - useful research tips. I'm going to hope the versions are always in current browserstack test versions :-)

I accepted all your changes.

2022-02-08 11:51 UTC, ddbeck approved these changes
Looks good. Thank you! 🎉

2022-02-08 11:51 UTC, merged