FF97 SVGPathElement.getPathSegAtLength() behind pref
mdn/browser-compat-data pull request #14497
Opened 2022-01-10 23:25 UTC by hamishwillee

FF97 puts some SVGPathX.. elements behind a preference in [bug 1388931](https://bugzilla.mozilla.org/show_bug.cgi?id=1388931) on path to removal. 

This just adds pref to existing [SVGPathElement.getPathSegAtLength()](https://developer.mozilla.org/en-US/docs/Web/API/SVGPathElement). The other elements that are also behind pref are `SVGPathSegList` (including `.numberOfItems`, `getItem()` and `length`) and `SVGAnimatedPathData` `.pathSegList` and `.animatedPathSegList`. These are not in MDN or BCD - I have chosen not to add them as this API is clearly "on the way out".

Other docs work for this can be tracked in https://github.com/mdn/content/issues/11597#issuecomment-1009447802

2022-01-11 16:18 UTC, ddbeck requested changes
One minor issue here

2022-01-11 16:18 UTC, ddbeck commented on api/SVGPathElement.json
> +              },
On Android there are no user serviceable parts inside. I think we just need the removal here

2022-01-14 00:55 UTC, hamishwillee commented
Doh! I removed the android flag thanks. Ready to re-review.

2022-01-18 13:32 UTC, ddbeck approved these changes
Looks good. Thank you! 🎉

2022-01-18 13:32 UTC, merged