Change Firefox version number supporting scrollbar-gutter
mdn/browser-compat-data pull request #14496
Opened 2022-01-10 22:09 UTC by aethanyc

scrollbar-gutter is shipped in Firefox 97 in
https://bugzilla.mozilla.org/show_bug.cgi?id=1715112

2022-01-11 18:10 UTC, ddbeck requested changes
Thanks for this PR, @aethanyc! A couple of suggestions for you. First, we ought to remove the now uninteresting bug link. Also, since there are two implementations, I suggest that you set `experimental: false`. Thanks again!

2022-01-11 18:10 UTC, ddbeck commented on css/properties/scrollbar-gutter.json
>                "notes": "See <a href='https://bugzil.la/1715112'>bug 1715112</a>."
```suggestion
              "version_added": "97"
```

2022-01-11 18:10 UTC, ddbeck commented on css/properties/scrollbar-gutter.json
>                "notes": "See <a href='https://bugzil.la/1715112'>bug 1715112</a>."
```suggestion
              "version_added": "97"
```

2022-01-11 19:19 UTC, aethanyc commented
@ddbeck Thank you for the review. I updated the commit to address your comments.

2022-01-13 11:06 UTC, ddbeck approved these changes
Looks good. Thank you! 🎉

2022-01-13 11:06 UTC, merged