Add a note of `Option` before IE 10
mdn/browser-compat-data pull request #14503
Opened 2022-01-11 06:02 UTC by aleen42

#### Summary

To describe the behaviour of elements constructed with `Option` before IE10.

#### Test results and supporting details

I have tested under IE8 / IE9 with the following snippet:

```js
console.log(new Option('text', 'value').outerHTML); /** => "<OPTION value=value></OPTION>" */
```

2022-01-11 18:27 UTC, ddbeck commented
Hi @aleen42. Thanks for opening this PR. Unfortunately, I wasn't able to reproduce this issue in IE9 (and if it occurs earlier that makes it something of an obscurity). I don't think we need to add a note, but I appreciate that you took the time to open a PR nonetheless.

2022-01-13 02:07 UTC, aleen42 commented
@ddbeck I do reproduce it and the output of `outerHTML` does miss 'text'.

- IE9:

![image](https://user-images.githubusercontent.com/9573300/149252842-48e68185-337e-4bce-9aa6-f7b8cfbeeba4.png)

- IE8:

![image](https://user-images.githubusercontent.com/9573300/149253018-1fcbfe13-f6bc-496d-852a-1c177b58a8fd.png)

2022-01-19 01:35 UTC, aleen42 commented
@ddbeck Please review this.

2022-01-26 14:35 UTC, ddbeck requested changes
Hi @aleen42. I still could not reproduce your screenshot in IE9, though I was able to reproduce it in IE8.

Using [this test case](https://gist.github.com/ddbeck/b303cbe5fa8e1aae29e00ef472cddb64), the `Option` constructor seemed to work as expected in IE9.

![bs_win7_IE_9 0(1)](https://user-images.githubusercontent.com/64103/151181839-56369b37-3ea1-4a5d-a3fd-76016aa4437a.jpg)

That said, the actual HTML `<option>` element works in IE8. To move this PR forward, you'll need to move the note to the `api/HTMLOptionElement.json` file, where it needs to be documented on the `Option` constructor feature, and revise the note so it only covers IE 8.

2022-01-29 08:00 UTC, queengooborg requested changes
Slight grammatical fix, as well as trying to make it slightly clearer that we're talking about a constructor -- otherwise, this looks good to me!

2022-02-07 01:16 UTC, aleen42 commented on api/HTMLOptionElement.json
> +              "notes": "Before Internet Explorer 9, the <code>outerHTML</code> of elements constructed with <code>Option</code> loses their text."
`loses` is used to describe the outer HTML.

2022-02-07 11:02 UTC, queengooborg requested changes
LGTM!  Just a small grammatical fix and we're good to go!

2022-02-07 11:02 UTC, queengooborg commented on api/HTMLOptionElement.json
> +              "notes": "Before Internet Explorer 9, the <code>outerHTML</code> of elements loses their text when constructing with <code>new Option()</code>."
```suggestion
              "notes": "Before Internet Explorer 9, the <code>outerHTML</code> of elements lose their text when constructing with <code>new Option()</code>."
```

2022-02-08 08:56 UTC, queengooborg approved these changes
Thanks for the quick fix!

2022-02-08 08:56 UTC, merged