Fix version_added of `isIntersecting`
mdn/browser-compat-data pull request #14638
Opened 2022-01-22 16:34 UTC by MoyuScript

#### Summary

Actually, `IntersectionObserverEntry.isIntersecting` was added after Chrome/58

See: <https://github.com/Fyrd/caniuse/blob/main/features-json/intersectionobserver.json#L222>

#### Test results and supporting details

I only test this feature on Chrome/55

![image](https://user-images.githubusercontent.com/45550579/149893881-de468cc6-314e-46a1-9f94-c9cabc538792.png)

#### Related issues

2022-01-25 18:26 UTC, ddbeck requested changes
Thanks for this PR, @MoyuScript. I see it's your first to the project—welcome!

I confirmed this (via https://mdn-bcd-collector.appspot.com/tests/api/IntersectionObserverEntry/isIntersecting in Chrome 57 and 58). Happy to have this corrected.

It's likely that the other Chromium-derived browsers are impacted, however. I'd suggest the following changes:

Opera: 45
Opera for Android: 43
Samsung Internet: 7
WebView Android: 58

2022-01-29 06:59 UTC, queengooborg requested changes
Thanks for the quick updates!  Just got a small change to make, and this'll be all ready!

2022-01-29 06:59 UTC, queengooborg commented on api/IntersectionObserverEntry.json
> +              "version_added": "7"
```suggestion
              "version_added": "7.0"
```

2022-01-31 06:06 UTC, queengooborg approved these changes
Thank you, looking good to me now!

2022-01-31 06:06 UTC, merged