Adding scroll-timeline css at rule
mdn/browser-compat-data pull request #14662
Opened 2022-01-25 17:44 UTC by Rumyra

#### Summary

This is available in Firefox 97 - see https://bugzilla.mozilla.org/show_bug.cgi?id=1676791 or/and https://bugzilla.mozilla.org/show_bug.cgi?id=1676782 

This is available in Chrome, but I'm unsure of the version it was first available in. If anyone points me in the right direction I'm happy to add

#### Test results and supporting details

Passes tests

#### Related issues

Part of https://github.com/mdn/content/issues/9368

2022-02-01 16:46 UTC, ddbeck commented
It looks like Chrome is behind a flag and not yet finished: https://bugs.chromium.org/p/chromium/issues/detail?id=1074052

2022-02-01 16:54 UTC, ddbeck requested changes
A few suggestions for you, Ruth.

2022-02-01 16:54 UTC, ddbeck commented on css/at-rules/scroll-timeline.json
> +            "mdn_url": "https://developer.mozilla.org/docs/Web/CSS/@scroll-timeline",
If the URL is not different from the parent feature, I'd omit it.

```suggestion
```

2022-02-01 16:54 UTC, ddbeck commented on css/at-rules/scroll-timeline.json
> +            "mdn_url": "https://developer.mozilla.org/docs/Web/CSS/@scroll-timeline",
```suggestion
```

2022-02-01 16:54 UTC, ddbeck commented on css/at-rules/scroll-timeline.json
> +            "mdn_url": "https://developer.mozilla.org/docs/Web/CSS/@scroll-timeline",
```suggestion
```

2022-02-01 16:54 UTC, ddbeck commented on css/at-rules/scroll-timeline.json
> +            "experimental": false,
These are all single-implementation right now, so let's set `experimental` to true. See the [_Choosing an experimental status_ data guideline](https://github.com/mdn/browser-compat-data/blob/main/docs/data-guidelines.md#choosing-an-experimental-status) for details.

```suggestion
            "experimental": true,
```

2022-02-01 16:54 UTC, ddbeck commented on css/at-rules/scroll-timeline.json
> +              "experimental": false,
```suggestion
              "experimental": true,
```

2022-02-03 14:40 UTC, Rumyra commented
Thanks loads @ddbeck 👍

2022-02-03 16:01 UTC, merged