Updates Web Share support in macOS for Edge 93.
mdn/browser-compat-data pull request #14871
Opened 2022-02-07 20:14 UTC by diekus

Updates Web Share support in macOS for Edge 93.

#### Summary
Updates Web Share support in macOS for Edge 93.

#### Test results and supporting details
https://docs.microsoft.com/en-gb/microsoft-edge/progressive-web-apps-chromium/whats-new/pwa#support-for-the-share-api-on-macos

2022-02-16 18:49 UTC, ddbeck requested changes
Thanks for this PR, @diekus. There's two things that need to happen to cover this correctly:

1. The structure of the data will need to change to look more like this:

    ```
    "edge": [
      {
        "version_added": "93"
      },
      {
        "version_added": "89",
        "version_removed": "93",
        "partial_implementation": true,
        "notes": "Not supported on macOS."
      }
    ]
    ```

1. It looks this affects more than just the parameter object's `files` property. I suspect we also need to modify the parent feature (`share`), the sibling feature (`data_text_parameter`), and their counterparts in the `canShare()` feature tree, in the way described above.

2022-03-19 17:34 UTC, queengooborg commented
Hey @diekus!  Do you plan to return to this PR?

2022-04-01 12:17 UTC, Elchi3 commented
I made the changes for @diekus. 

@ddbeck can you re-review?

2022-04-07 17:51 UTC, ddbeck approved these changes
Looks good. Thank you @diekus and @Elchi3! 🎉

2022-04-07 17:51 UTC, merged