Adapt api.MediaKeySession.onmessage to new events structure
mdn/browser-compat-data pull request #15167
Opened 2022-02-28 08:23 UTC by queengooborg

This PR adapts the message event of the MediaKeySession API to conform to the new events structure.

2022-03-08 11:26 UTC, foolip requested changes
https://source.chromium.org/chromium/chromium/src/+/6e3647df59a9b8a2c77d49ce5681e2a5b3ab7d17 shows that the event handler attributes were added after the events themselves. Can you add `partial_implementation` ranges?

2022-03-11 06:01 UTC, queengooborg commented
I actually don't know how to track down support for the events themselves in the source code!  Would you be willing/able to provide me some assistance there?

2022-03-28 12:27 UTC, Elchi3 commented
I think the following is needed here:

```
"chrome": [
  {
    "version_added": "55"
  },
  {
    "version_added": "42",
    "version_removed": "55",
    "partial_implementation": true,
    "notes": "The <code>onkeystatuseschange</code> event handler property is not supported."
  }
],
```

And 

```
"chrome": [
  {
    "version_added": "55"
  },
  {
    "version_added": "42",
    "version_removed": "55",
    "partial_implementation": true,
    "notes": "The <code>onmessage</code> event handler property is not supported."
  }
],
```

(same structure [with different versions] for other chromium based browsers)

2022-03-29 07:25 UTC, foolip approved these changes

2022-03-29 07:25 UTC, foolip commented on api/MediaKeySession.json
> +                "version_added": "55"
Confirmed by https://storage.googleapis.com/chromium-find-releases-static/6e3.html#6e3647df59a9b8a2c77d49ce5681e2a5b3ab7d17

2022-03-29 07:29 UTC, foolip approved these changes

2022-03-29 07:29 UTC, merged