Adapt ShadowRoot API to new events structure
mdn/browser-compat-data pull request #15201
Opened 2022-03-01 01:07 UTC by queengooborg

This PR adapts the ShadowRoot API to conform to the new events structure.

Note: there are no MDN pages associated with this event, so there will be no corresponding content PR. Any broken MDN URLs in BCD have been removed.

2022-03-04 15:23 UTC, foolip requested changes
Per https://groups.google.com/a/chromium.org/g/blink-dev/c/cagoIboJ6Oo/m/aCjiL_FBAgAJ this was a case of missing event handler property, while the event was supported earlier. This will require testing and `partial_implementation` ranges, possibly in Firefox and Safari too.

2022-04-01 09:00 UTC, Elchi3 commented
https://developer.mozilla.org/en-US/docs/Web/API/HTMLSlotElement/slotchange_event#browser_compatibility probably has the versions we want in the range here.

2022-04-01 09:13 UTC, Elchi3 commented
```
"slotchange_event": {
    "__compat": {
        "description": "<code>slotchange</code> event",
        "spec_url": "https://dom.spec.whatwg.org/#dom-shadowroot-onslotchange",
        "support": {
            "chrome": [
              {
                "version_added": "97"
              },
              {
                "version_added": "53",
                "version_removed": "97",
                "partial_implementation": true,
                "notes": "The <code>onslotchange</code> event handler property is not supported."
              }
            ],
            "chrome_android": [
              {
                "version_added": "97"
              },
              {
                "version_added": "53",
                "version_removed": "97",
                "partial_implementation": true,
                "notes": "The <code>onslotchange</code> event handler property is not supported."
              }
            ],
            "edge": [
              {
                "version_added": "97"
              },
              {
                "version_added": "53",
                "version_removed": "97",
                "partial_implementation": true,
                "notes": "The <code>onslotchange</code> event handler property is not supported."
              }
            ],
            "firefox": [
                {
                  "version_added": "93"
                },
                {
                  "version_added": "63",
                  "version_removed": "93",
                  "partial_implementation": true,
                  "notes": "The <code>onslotchange</code> event handler property is not supported."
                }
              ],
            "firefox_android": [
                {
                  "version_added": "93"
                },
                {
                  "version_added": "79",
                  "version_removed": "97",
                  "partial_implementation": true,
                  "notes": "The <code>onslotchange</code> event handler property is not supported."
                }
              ],
            "ie": {
                "version_added": false
            },
            "opera": [
                {
                  "version_added": "xx"
                },
                {
                  "version_added": "40",
                  "version_removed": "xx",
                  "partial_implementation": true,
                  "notes": "The <code>onslotchange</code> event handler property is not supported."
                }
              ],
            "opera_android": [
                {
                  "version_added": "68"
                },
                {
                  "version_added": "41",
                  "version_removed": "68",
                  "partial_implementation": true,
                  "notes": "The <code>onslotchange</code> event handler property is not supported."
                }
              ],
            "safari": [
                {
                  "version_added": "14.1"
                },
                {
                  "version_added": "10.1",
                  "version_removed": "14.1",
                  "partial_implementation": true,
                  "notes": "The <code>onslotchange</code> event handler property is not supported."
                }
              ],
            "safari_ios": [
                {
                  "version_added": "14.5"
                },
                {
                  "version_added": "10.3",
                  "version_removed": "14.5",
                  "partial_implementation": true,
                  "notes": "The <code>onslotchange</code> event handler property is not supported."
                }
              ],
            "samsunginternet_android": {
              "version_added": "6.0",
              "partial_implementation": true,
              "notes": "The <code>onslotchange</code> event handler property is not supported."
            },
            "webview_android": [
                {
                  "version_added": "97"
                },
                {
                  "version_added": "53",
                  "version_removed": "97",
                  "partial_implementation": true,
                  "notes": "The <code>onslotchange</code> event handler property is not supported."
                }
              ],
        },
        "status": {
            "experimental": false,
            "standard_track": true,
            "deprecated": false
        }
    }
}
```

2022-04-02 12:34 UTC, foolip approved these changes

2022-04-02 12:34 UTC, merged