Throw a better-worded error when duplicate features found
mdn/browser-compat-data pull request #15479
Opened 2022-03-22 21:49 UTC by queengooborg

In `index.js`, an error is thrown when attempting to run the `extend()` function on non-objects.  This error also unintentionally catches duplicate entries found in BCD, when attempting to merge their `mdn_url` properties.

However, in the context of duplicate entries, the error message is unhelpful at best.  It is not clear to the contributor that this means a feature's compat data was found twice in BCD.  This PR attempts to resolve that by throwing a more helpful error, stating that a duplicate entry was found.

2022-03-23 20:37 UTC, queengooborg commented
I opened this PR after running into the error message whilst working on both #15480 and #15477.  In those PRs, I did a mass conversion of event handlers (`onfoo`) to events (`foo_event`), and I knew there would be some duplicate entries to work out.  However, with the `extend()` function the way it is now, I didn't have an easy way to find the duplicated features as I had no clue _which_ feature was duplicated.  So, during the first of the PRs, I wrote this tweak to nail down which feature was causing problems, thus eliminate the duplicate much quicker.

I updated the PR description to include a "steps to reproduce" section as well!

2022-03-23 22:22 UTC, lucalves approved these changes

2022-03-24 17:17 UTC, ddbeck requested changes
OK, having had another look at this, a suggestion in a line comment.

Also, can you please include an actual before and after traceback in this issue? It'll serve as documentation for what changed and make it easier for other reviewers to understand what you're trying to achieve here.

2022-03-24 17:17 UTC, ddbeck commented on index.js
> +        throw new Error(
It might be nice to subclass `Error` (e.g., `DuplicateCompatError`) instead of throwing a generic `Error`.

2022-04-13 12:02 UTC, ddbeck requested changes
A couple more suggestions for you

2022-04-13 12:02 UTC, ddbeck commented on index.js
> +    super(message);
Error text suggestions:

- Put the message text template in the constructor, so it's not possible to have inconsistent message text (should this ever be reused elsewhere)
- Avoid "please" in the case of operator error ([example style guide](https://docs.microsoft.com/en-us/style-guide/a-z-word-list-term-collections/p/please))
- The count's not knowable here (there could be a third as-yet-unprocessed duplicate)

```suggestion
    super(`${feature} already exists! Remove duplicate entries.`);
```

2022-04-13 12:02 UTC, ddbeck commented on index.js
> +        );
```suggestion
        throw new DuplicateCompatError(feature);
```

2022-04-13 16:45 UTC, ddbeck approved these changes
Thank you! 🎉

2022-04-13 16:45 UTC, merged