Release 99 Intl.Locale Chromium adds support for some new properties
mdn/browser-compat-data pull request #15505
Opened 2022-03-25 02:27 UTC by hamishwillee

From https://v8.dev/blog/v8-release-99#javascript

> [Intl.Locale API](https://v8.dev/blog/v8-release-74#intl.locale). With v9.9, we added seven new properties to the Intl.Locale object: calendars, collations, hourCycles, numberingSystems, timeZones, textInfo, and weekInfo.

This adds the versions. Previously these were behind flags. Note however that the flag info hadn't been extended to Opera, so I have added that too.

Fixes #15174

2022-03-27 05:51 UTC, queengooborg requested changes
Thanks Hamish!  This is mostly LGTM, but Opera Android actually doesn't support flags.  Can we remove flagged data from Opera Android?

2022-03-27 23:53 UTC, hamishwillee commented on javascript/builtins/intl/Locale.json
> +                  "version_added": "65",
```suggestion
                  "version_added": false
```

2022-03-27 23:54 UTC, hamishwillee commented on javascript/builtins/intl/Locale.json
> +                  ]
```suggestion
                  "version_added": false
```

2022-03-27 23:55 UTC, hamishwillee commented on javascript/builtins/intl/Locale.json
> +                  ]
```suggestion
                  "version_added": "65"
```

2022-03-27 23:56 UTC, hamishwillee commented on javascript/builtins/intl/Locale.json
> +                  ]
```suggestion
                  "version_added": false
```

2022-03-27 23:56 UTC, hamishwillee commented on javascript/builtins/intl/Locale.json
> +                  ]
```suggestion
                  "version_added": false
```

2022-03-27 23:57 UTC, hamishwillee commented on javascript/builtins/intl/Locale.json
> +                  ]
```suggestion
                  "version_added": false
```

2022-03-27 23:57 UTC, hamishwillee commented on javascript/builtins/intl/Locale.json
> +                  ]
```suggestion
                  "version_added": false
```

2022-03-27 23:57 UTC, hamishwillee commented on javascript/builtins/intl/Locale.json
> +                  ]
```suggestion
                  "version_added": false
```

2022-03-28 00:01 UTC, hamishwillee commented
Thanks @queengooborg - Fixed!

2022-03-28 00:02 UTC, queengooborg approved these changes
Thank you, LGTM!

2022-03-28 00:02 UTC, merged