updating inert
mdn/browser-compat-data pull request #16046
Opened 2022-04-27 08:19 UTC by rachelandrew

Updating `HTMLElement.inert` as Chrome is shipping in 102. Also added `inert` as a global attribute. 

https://chromestatus.com/feature/5703266176335872

2022-04-27 11:37 UTC, nt1m commented
Not sure with safari_ios is set to false, but this is also supported on iOS (same version as desktop).

2022-04-27 11:38 UTC, nt1m commented
Also, Firefox recently enabled it by default only on Nightly/early betas: https://bugzilla.mozilla.org/show_bug.cgi?id=1764134 in version 101, but keeps it disabled for release versions, not sure how to reflect that.

2022-04-27 12:41 UTC, rachelandrew commented
@nt1m I've update iOS, as far as Firefox goes I think the extra level of detail isn't that useful as in the stable version it's behind a flag, which is probably what people think of looking at  this.

2022-04-27 17:15 UTC, queengooborg requested changes
Thanks for your PR!  Just a small detail, but this is LGTM otherwise!

2022-04-27 17:15 UTC, queengooborg commented on html/global_attributes.json
> +            },
Firefox Android actually doesn't have flag support anymore!

```suggestion
            "firefox_android": {
              "version_added": false
            },
```

2022-04-27 17:20 UTC, queengooborg commented
@nt1m If the feature is available in nightly but disabled in beta/stable, we use ["preview" for the version](https://github.com/mdn/browser-compat-data/blob/main/docs/data-guidelines.md#choosing-preview-values).  I'd be happy to review a separate PR to make those changes, or if you'd like to make the changes here @rachelandrew, I'm also happy to merge them!

2022-04-28 06:53 UTC, rachelandrew commented
@queengooborg I've committed your change and also made the preview update.

2022-04-28 07:03 UTC, queengooborg approved these changes
Thank you, this is LGTM!

2022-04-28 07:03 UTC, merged