Add missing api.Element.requestPointerLock.options_unadjustedMovement_parameter feature
mdn/browser-compat-data pull request #16060
Opened 2022-04-28 22:48 UTC by queengooborg

This PR adds the missing `requestPointerLock.options_unadjustedMovement_parameter` member of the Element API, populating the results using data from ChromeStatus (https://chromestatus.com/feature/5723553087356928).  I couldn't find any bugs or information for Firefox or Safari.

2022-05-05 20:34 UTC, foolip requested changes

2022-05-05 20:34 UTC, foolip commented on api/Element.json
> +                "version_added": "81"
Per https://bugs.chromium.org/p/chromium/issues/detail?id=1215235 this was accidentally not shipped, and per https://storage.googleapis.com/chromium-find-releases-static/a21.html#a21641ea63a9abcdc06670adf58ccb6a0fb2905a it seems like it finally happened in 92.

2022-05-17 10:58 UTC, foolip commented
@queengooborg are you planning to do the content work too?

2022-05-17 10:59 UTC, foolip approved these changes

2022-05-17 11:01 UTC, queengooborg commented
I'd prefer if someone else who is more knowledgeable about pointer locks handle the content PR, but if no one else takes it then I'd be happy to research it and write a PR!

(Also down to merge this PR now and forego content updates for the time being.  :P)

2022-05-17 12:39 UTC, foolip commented
Right, I wouldn't consider content updates blocking for BCD additions, but you added the label 😄

Feel free to merge if you like!

2022-05-17 12:48 UTC, queengooborg commented
Let's go ahead and merge this now then, and content updates can follow in a galaxy far, far away...  :P

2022-05-17 12:48 UTC, merged