Remove irrelevant notes for api.MediaDevices.getDisplayMedia
mdn/browser-compat-data pull request #16071
Opened 2022-04-30 07:49 UTC by queengooborg

This PR removes the now-irrelevant notes for Firefox Android and WebView Android regarding availability of MediaDevices.getUserMedia().  The method was removed entirely in Chromium 88 and Firefox Android 79, so it isn't separated into multiple support statements to reflect the method's history (especially since it always rejected).  Fixes #8821.

2022-05-05 10:11 UTC, foolip requested changes
These entries should be `partial_implementation` with a `version_added`.

2022-05-31 08:39 UTC, queengooborg commented
Since these have been removed though, is it really worth it to try and research a `version_added` for when the method was first added despite it never being supported?

2022-06-03 11:20 UTC, foolip commented
@queengooborg the collector is going to want to add back support for this since the API is present, right? When that happens, it's likely we'll have forgotten about this and won't add `partial_implementation` as we should.

2022-06-20 04:24 UTC, queengooborg commented
Alright, in that case, I'm going to close this PR.  I won't be able to get results for all older Android browsers just yet.

2022-06-20 04:25 UTC, closed without merging