Update Chromium versions for api.IDBRequest.error
mdn/browser-compat-data pull request #16221
Opened 2022-05-10 06:20 UTC by queengooborg

This PR updates and corrects the real values for Chromium (Chrome, Opera, Samsung Internet, WebView Android) for the `error` member of the `IDBRequest` API, based upon results from the [mdn-bcd-collector](https://mdn-bcd-collector.appspot.com) project (v6.0.1).

Tests Used: https://mdn-bcd-collector.appspot.com/tests/api/IDBRequest/error

_Check out the [collector's guide on how to review this PR](https://github.com/foolip/mdn-bcd-collector#reviewing-bcd-changes)._

2022-05-16 11:49 UTC, foolip reviewed
This now doesn't match the error event. Probably the property and the event were introduced at the same time, can you double check? Note that the `onerror` property might have been missing even if the event was fired.

2022-07-19 16:36 UTC, foolip requested changes
Turns out the property and the event wasn't added together, but two properties were:
https://github.com/WebKit/WebKit/commit/9a1cbdcd827306c4483ba767e4241a51e334f49d

Can you test `IDBTransaction` and if the collector doesn't update that one investigate why?

2022-08-23 18:56 UTC, queengooborg commented
The tests for `IDBTransaction` are not custom tests, so it's set all the features to `43`, and thus I've been discarding them.  I can update this PR manually to set `IDBTransaction.error` to the same version number while a custom test is in the works!

2022-09-13 14:09 UTC, foolip commented
Poking around a bit more, it seems like there's plenty wrong with the IndexedDB data for Chrome. BCD currently has all of the transaction-related stuff marked as Chrome 23, but http://mdn-bcd-collector.appspot.com/tests/api/IDBRequest/transaction shows support in Chrome 15.

BCD doesn't reflected support for the prefixed indexedDB.

I think that minor changes to the data here aren't worthwhile, better to review the overall state of things and ensure it's consistent and useful, or leave it alone.

2023-01-11 11:50 UTC, Elchi3 commented
Closing this stuck PR. Please open an issue if you think BCD should do pre-2020 data correction for IndexedDB in Chrome.

2023-01-11 11:50 UTC, closed without merging