Add Chrome & Edge support for AudioContext outputLatency
mdn/browser-compat-data pull request #16426
Opened 2022-05-25 12:13 UTC by beaufortfrancois

This PR adds Chrome and Edge support for AudioContext `outputLatency`. 
Source: https://chromiumdash.appspot.com/commit/8866a84d12e96c5fbb85ab8258f6fa80cb833843

FYI @hoch

2022-05-25 14:36 UTC, hoch commented
Looks great! 👍

2022-05-25 18:41 UTC, queengooborg requested changes
Thank you for your PR!  We recently introduced a new feature in BCD that allows us to easily mirror the data.  We should probably take advantage of it here, like so:

```json
"chrome": {
  "version_added": "102"
},
"chrome_android": "mirror",
```

(Mirroring should be applied to Chrome Android, Edge, Opera, Opera Android, Samsung Internet, and WebView.)

2022-05-26 05:19 UTC, beaufortfrancois commented
@queengooborg I've updated PR based on your feedback. Please take another look

2022-05-26 19:04 UTC, queengooborg approved these changes
Thank you, LGTM!

2022-05-26 19:04 UTC, merged

2022-05-30 07:11 UTC, beaufortfrancois commented
It has been 4 days since this PR has been merged but https://developer.mozilla.org/en-US/docs/Web/API/AudioContext/outputLatency still shows previous data. @queengooborg Is that expected?

<img width="848" alt="image" src="https://user-images.githubusercontent.com/634478/170936978-b0a26b5f-3ddc-4c23-a54c-c378f32c06c9.png">

2022-05-30 07:22 UTC, queengooborg commented
This is expected, yes -- BCD is released nearly every Tuesday, and then updated on MDN web docs every Wednesday.  A new version of BCD will be releasing soon though, don't worry!

2022-05-30 07:29 UTC, beaufortfrancois commented
Thank you @queengooborg!