Convert BCD to TypeScript
mdn/browser-compat-data pull request #16593
Opened 2022-06-08 03:39 UTC by queengooborg

This PR fixes #16333 by converting all of BCD's scripts over to TypeScript.

2022-06-09 02:10 UTC, queengooborg commented
This PR depends on https://github.com/TypeStrong/ts-node/pull/1792 to fix a small bug in `ts-node`.

2022-06-09 06:56 UTC, bershanskiy commented
This patch makes this PR pass tests. I can split out some changes into a separate PR focused entirely on minor bug fixes.

```diff
diff --git a/scripts/lib/compare-statements.test.ts b/scripts/lib/compare-statements.test.ts
index ca1f50f40..2bbcdd5f2 100644
--- a/scripts/lib/compare-statements.test.ts
+++ b/scripts/lib/compare-statements.test.ts
@@ -98,7 +98,7 @@ const tests: { input: Identifier; output: Identifier }[] = [
       },
     },
   },
-];
+] as any;
 
 function orderStatements(key: string, value: CompatStatement): CompatStatement {
   if (key === '__compat') {
diff --git a/scripts/migrations/002-remove-webview-flags.test.ts b/scripts/migrations/002-remove-webview-flags.test.ts
index bbd36f380..5102decb8 100644
--- a/scripts/migrations/002-remove-webview-flags.test.ts
+++ b/scripts/migrations/002-remove-webview-flags.test.ts
@@ -120,7 +120,7 @@ const tests: { input: Identifier; output: Identifier }[] = [
       },
     },
   },
-];
+] as any;
 
 describe('migration scripts', () => {
   it('`removeWebViewFlags()` works correctly', () => {
diff --git a/scripts/migrations/002-remove-webview-flags.ts b/scripts/migrations/002-remove-webview-flags.ts
index c9e304efa..1fcb5efd3 100644
--- a/scripts/migrations/002-remove-webview-flags.ts
+++ b/scripts/migrations/002-remove-webview-flags.ts
@@ -1,7 +1,7 @@
 /* This file is a part of @mdn/browser-compat-data
  * See LICENSE file for more information. */
 
-import { CompatStatement } from '../../types/types.js';
+import { CompatStatement, SimpleSupportStatement } from '../../types/types.js';
 
 import fs from 'node:fs';
 import path from 'node:path';
@@ -28,7 +28,7 @@ export const removeWebViewFlags = (
   if (key === '__compat') {
     if (value.support.webview_android !== undefined) {
       if (Array.isArray(value.support.webview_android)) {
-        const result = [];
+        const result: SimpleSupportStatement[] = [];
         for (let i = 0; i < value.support.webview_android.length; i++) {
           if (value.support.webview_android[i].flags === undefined) {
             result.push(value.support.webview_android[i]);
diff --git a/scripts/migrations/007-experimental-false.test.ts b/scripts/migrations/007-experimental-false.test.ts
index dd258c829..9efd2c2e5 100644
--- a/scripts/migrations/007-experimental-false.test.ts
+++ b/scripts/migrations/007-experimental-false.test.ts
@@ -30,7 +30,7 @@ describe('fixExperimental()', () => {
           },
         },
       },
-    };
+    } as any;
     assert.equal(bcd.api.fetch.__compat.status.experimental, true);
     fixExperimental(bcd);
     assert.equal(bcd.api.fetch.__compat.status.experimental, false);
@@ -60,7 +60,7 @@ describe('fixExperimental()', () => {
           },
         },
       },
-    };
+    } as any;
     assert.equal(bcd.api.fetch.__compat.status.experimental, true);
     fixExperimental(bcd);
     assert.equal(bcd.api.fetch.__compat.status.experimental, false);
@@ -90,7 +90,7 @@ describe('fixExperimental()', () => {
           },
         },
       },
-    };
+    } as any;
     assert.equal(bcd.api.fetch.__compat.status.experimental, true);
     fixExperimental(bcd);
     assert.equal(bcd.api.fetch.__compat.status.experimental, true);
@@ -126,7 +126,7 @@ describe('fixExperimental()', () => {
           },
         },
       },
-    };
+    } as any;
     assert.equal(bcd.api.fetch.__compat.status.experimental, true);
     fixExperimental(bcd);
     assert.equal(bcd.api.fetch.__compat.status.experimental, false);
diff --git a/scripts/release/mirror.ts b/scripts/release/mirror.ts
index 27d84656f..e6aa76fb3 100644
--- a/scripts/release/mirror.ts
+++ b/scripts/release/mirror.ts
@@ -358,7 +358,7 @@ export const bumpSupport = (
   sourceData: SupportStatement | null,
   destination: BrowserName,
 ): SupportStatement | null => {
-  let newData = null;
+  let newData: SupportStatement | null = null;
 
   if (sourceData == null) {
     return null;
diff --git a/test/linter/test-consistency.ts b/test/linter/test-consistency.ts
index fa7d2af7f..14f990edd 100644
--- a/test/linter/test-consistency.ts
+++ b/test/linter/test-consistency.ts
@@ -92,7 +92,7 @@ export class ConsistencyChecker {
    * @return {string[]}
    */
   getSubfeatures(data: Identifier): string[] {
-    const subfeatures = [];
+    const subfeatures: string[] = [];
     const keys = Object.keys(data).filter((key) => key != '__compat');
     for (const key of keys) {
       if ((data as any)[key] === undefined) continue;
@@ -362,13 +362,13 @@ export class ConsistencyChecker {
     }
 
     // Handle array support statements
-    let selectedValue = null;
+    let selectedValue: string | boolean | null = null;
     for (const statement of supportStatement) {
       const resolvedValue = resolveVersionAddedValue(statement);
 
       if (resolvedValue === null) {
         // We're not going to get a more specific version, so bail out now
-        continue;
+        return null;
       }
 
       if (selectedValue !== null) {
diff --git a/test/linter/test-obsolete.test.ts b/test/linter/test-obsolete.test.ts
index 92c6d0a2d..3c5305458 100644
--- a/test/linter/test-obsolete.test.ts
+++ b/test/linter/test-obsolete.test.ts
@@ -9,7 +9,7 @@ describe('neverImplemented', function () {
   it('returns false for features which were implemented', () => {
     assert.equal(
       neverImplemented({
-        browser: { version_added: '1' },
+        chrome: { version_added: '1' },
       }),
       false,
     );
@@ -33,7 +33,7 @@ describe('neverImplemented', function () {
   it('returns true for features which were not implemented', () => {
     assert.equal(
       neverImplemented({
-        browser: { version_added: null },
+        chrome: { version_added: null },
       }),
       true,
     );
diff --git a/test/linter/test-obsolete.ts b/test/linter/test-obsolete.ts
index e94a9d93c..b9cc21375 100644
--- a/test/linter/test-obsolete.ts
+++ b/test/linter/test-obsolete.ts
@@ -5,7 +5,7 @@ import { Linter, Logger, LinterMessageLevel } from '../utils.js';
 import {
   BrowserName,
   CompatStatement,
-  SimpleSupportStatement,
+  SupportBlock,
 } from '../../types/types.js';
 
 import chalk from 'chalk-template';
@@ -37,7 +37,7 @@ const exceptions = [
   'svg.elements.view.zoomAndPan',
 ];
 
-export function neverImplemented(support: SimpleSupportStatement) {
+export function neverImplemented(support: SupportBlock) {
   for (const data of Object.values(support)) {
     for (const d of Array.isArray(data) ? data : [data])
       if (d.version_added) return false;
@@ -51,11 +51,11 @@ errorTime.setFullYear(errorTime.getFullYear() - 2.5);
 warningTime.setFullYear(warningTime.getFullYear() - 2);
 
 /**
- * @param {SimpleSupportStatement} support
+ * @param {SupportBlock} support
  * @returns LinterMessageLevel | false
  */
 function implementedAndRemoved(
-  support: SimpleSupportStatement,
+  support: SupportBlock,
 ): LinterMessageLevel | false {
   let result: LinterMessageLevel = 'error';
   for (const [browser, data] of Object.entries(support) as [BrowserName, any]) {
@@ -91,29 +91,27 @@ function processData(
     const { support, status } = data;
     const shouldFail = exceptions.includes(path);
 
-    for (const statement of Array.isArray(support) ? support : [support]) {
-      const abandoned = status && status.standard_track === false;
-      const rule1Fail = abandoned && neverImplemented(statement);
-      if (rule1Fail && !shouldFail) {
-        logger.error(
-          chalk`feature was never implemented in any browser and the specification has been abandoned.`,
-        );
-        return;
-      }
+    const abandoned = status && status.standard_track === false;
+    const rule1Fail = abandoned && neverImplemented(support);
+    if (rule1Fail && !shouldFail) {
+      logger.error(
+        chalk`feature was never implemented in any browser and the specification has been abandoned.`,
+      );
+      return;
+    }
 
-      const rule2Fail = implementedAndRemoved(statement);
-  [...]

2022-06-09 06:58 UTC, bershanskiy requested changes

2022-06-09 06:58 UTC, bershanskiy commented on test/linter/test-consistency.ts
> +        continue;
This change is causing a test failure. Specifically this test is failing after this change:
https://github.com/mdn/browser-compat-data/blob/0cfbcaa1d2b66f0a8637bdb4953daf29afb56fa1/test/linter/test-consistency.test.js#L32-L38

I think we might actually have two bugs here:
 - this should be a `continue`
 - code below should filter out all entries with `flags`

2022-06-09 07:17 UTC, bershanskiy commented on test/linter/test-consistency.ts
> +        continue;
I fixed this bug and got more linting errors. I'll file a separate PR for this too. Specifically:
```
Consistency - 3 problems (3 errors, 0 warnings):
 ✖ api.MediaMetadata - Error → Basic support in firefox was declared implemented in a later version (82) than the following sub-feature(s):
        → api.MediaMetadata.MediaMetadata: 71
        → api.MediaMetadata.album: 71
        → api.MediaMetadata.artist: 71
        → api.MediaMetadata.artwork: 71
        → api.MediaMetadata.title: 71
 ✖ api.Worker - Error → Basic support in nodejs was declared implemented in a later version (11.7.0) than the following sub-feature(s):
        → api.Worker.Worker: 10.5.0
        → api.Worker.message_event: 10.5.0
        → api.Worker.postMessage: 10.5.0
        → api.Worker.terminate: 10.5.0
 ✖ javascript.statements.export - Error → Basic support in nodejs was declared implemented in a later version (13.2.0) than the following sub-feature(s):
        → javascript.statements.export.namespace: 12.0.0
```

2022-06-09 08:27 UTC, bershanskiy commented on test/linter/test-consistency.ts
> +        continue;
I filed a split-out PR for this #16614.

2022-06-10 05:22 UTC, bershanskiy commented on test/linter/test-consistency.ts
> +        continue;
This concern was resolved when #16614 was merged into `main` and then into this branch.

2022-06-10 05:37 UTC, bershanskiy commented
We are getting very close!

One more patch:
```diff
diff --git a/scripts/release/mirror.ts b/scripts/release/mirror.ts
index e6aa76fb3..235e5556b 100644
--- a/scripts/release/mirror.ts
+++ b/scripts/release/mirror.ts
@@ -5,9 +5,11 @@ import {
   BrowserName,
   SimpleSupportStatement,
   SupportStatement,
-  SupportBlock,
 } from '../../types/types.js';
-import { InternalSupportStatement } from '../../types/index.js';
+import {
+  InternalSupportBlock,
+  InternalSupportStatement,
+} from '../../types/index.js';
 
 type Notes = string | string[] | null;
 
@@ -402,7 +404,7 @@ export const bumpSupport = (
 
 const mirrorSupport = (
   destination: BrowserName,
-  data: SupportBlock,
+  data: InternalSupportBlock,
 ): SupportStatement | null => {
   const upstream: BrowserName | undefined = browsers[destination].upstream;
   if (!upstream) {
@@ -411,7 +413,7 @@ const mirrorSupport = (
     );
   }
 
-  let upstreamData: InternalSupportStatement = data[upstream];
+  let upstreamData: InternalSupportStatement | null = data[upstream] || null;
 
   if (!upstreamData) {
     throw new Error(
diff --git a/test/lint.ts b/test/lint.ts
index bcf25f86f..cee157e6e 100644
--- a/test/lint.ts
+++ b/test/lint.ts
@@ -25,7 +25,9 @@ const dirname = fileURLToPath(new URL('.', import.meta.url));
  * @param {string[]} files The files to test
  * @returns {DataType?}
  */
-const loadAndCheckFiles = async (...files: string[]): DataType | undefined => {
+const loadAndCheckFiles = async (
+  ...files: string[]
+): Promise<DataType | undefined> => {
   const data = {};
 
   for (let file of files) {
diff --git a/test/linter/test-versions.ts b/test/linter/test-versions.ts
index 2afbf3e6f..762027225 100644
--- a/test/linter/test-versions.ts
+++ b/test/linter/test-versions.ts
@@ -6,10 +6,12 @@ import {
   BrowserName,
   CompatStatement,
   SimpleSupportStatement,
-  SupportBlock,
   VersionValue,
 } from '../../types/types.js';
-import { InternalSupportStatement } from '../../types/index.js';
+import {
+  InternalSupportBlock,
+  InternalSupportStatement,
+} from '../../types/index';
 
 import compareVersions from 'compare-versions';
 import chalk from 'chalk-template';
@@ -152,7 +154,7 @@ function addedBeforeRemoved(statement: SimpleSupportStatement): boolean | null {
  * @returns {void}
  */
 function checkVersions(
-  supportData: SupportBlock,
+  supportData: InternalSupportBlock,
   category: string,
   logger: Logger,
 ): void {
diff --git a/types/index.d.ts b/types/index.d.ts
index 143420dff..d2da597f9 100644
--- a/types/index.d.ts
+++ b/types/index.d.ts
@@ -5,6 +5,10 @@ import { SupportStatement } from '../types';
 
 export type InternalSupportStatement = SupportStatement | 'mirror';
 
+export type InternalSupportBlock = Partial<
+  Record<BrowserName, InternalSupportStatement>
+>;
+
 export type DataType =
   | CompatData
   | BrowserStatement
diff --git a/utils/walk.ts b/utils/walk.ts
index 1a921bc8b..522d353ba 100644
--- a/utils/walk.ts
+++ b/utils/walk.ts
@@ -11,12 +11,7 @@ import {
 import { DataType } from '../types/index.js';
 
 import bcd from '../index.js';
-import {
-  isBrowser,
-  isFeature,
-  descendantKeys,
-  joinPath,
-} from './walkingUtils.js';
+import { isBrowser, descendantKeys, joinPath } from './walkingUtils.js';
 import query from './query.js';
 
 type WalkOutput = {
```

2022-06-11 10:10 UTC, bershanskiy commented
Here is a tiny refactoring patch that removes unnecessary casts to `any` and uses stricter types. We can include it in this PR or just postpone it till later.

```diff
diff --git a/scripts/diff-features.ts b/scripts/diff-features.ts
index 8dcd06f90..bb6519662 100644
--- a/scripts/diff-features.ts
+++ b/scripts/diff-features.ts
@@ -8,7 +8,7 @@ import esMain from 'es-main';
 import yargs from 'yargs';
 import { hideBin } from 'yargs/helpers';
 
-function main(opts: any): void {
+function main(opts): void {
   const { ref1, ref2, format, github } = opts;
   const results = diff({ ref1, ref2, github });
 
@@ -19,7 +19,7 @@ function main(opts: any): void {
   }
 }
 
-export default function diff(opts: any): {
+export default function diff(opts): {
   added: string[];
   removed: string[];
 } {
@@ -63,7 +63,7 @@ function enumerate(ref: string, skipGitHub: boolean): Set<string> {
   return new Set(enumerateFeatures(ref));
 }
 
-function getEnumerationFromGithub(ref: string): any {
+function getEnumerationFromGithub(ref: string) {
   const ENUMERATE_WORKFLOW = '15595228';
   const ENUMERATE_WORKFLOW_ARTIFACT = 'enumerate-features';
   const ENUMERATE_WORKFLOW_FILE = 'features.json';
@@ -71,8 +71,8 @@ function getEnumerationFromGithub(ref: string): any {
   const unlinkFile = () => {
     try {
       fs.unlinkSync(ENUMERATE_WORKFLOW_FILE);
-    } catch (err) {
-      if ((err as any).code == 'ENOENT') {
+    } catch (err: any) {
+      if (err.code == 'ENOENT') {
         return;
       } else {
         throw err;
@@ -105,7 +105,7 @@ function getEnumerationFromGithub(ref: string): any {
   }
 }
 
-function enumerateFeatures(ref = 'HEAD'): any {
+function enumerateFeatures(ref = 'HEAD') {
   // Get the short hash for this ref.
   // Most of the time, you check out named references (a branch or a tag).
   // However, if `ref` is already checked out, then `git worktree add` fails. As
diff --git a/scripts/diff.ts b/scripts/diff.ts
index e4fa2d63e..83b10efe0 100644
--- a/scripts/diff.ts
+++ b/scripts/diff.ts
@@ -54,7 +54,7 @@ function doMirror(diff, contents, path, direction) {
 
 /**
  * @param {Diff<string, string>} diffItem
- * @param {Contents<any>} contents
+ * @param {Contents} contents
  */
 function describeByKind(
   diffItem: Diff<string, string>,
@@ -130,7 +130,7 @@ function mergeAsMap(
  * @param {string} head
  */
 function getDiffs(base: string, head = ''): Map<string, string> {
-  const namedDescriptions: any = [];
+  const namedDescriptions: { name: string; description: string }[] = [];
   for (const status of getGitDiffStatuses(base, head)) {
     if (!status.headPath.endsWith('.json') || !status.headPath.includes('/')) {
       continue;
diff --git a/scripts/enumerate-features.ts b/scripts/enumerate-features.ts
index 4bcacbcb5..7cc9c9734 100644
--- a/scripts/enumerate-features.ts
+++ b/scripts/enumerate-features.ts
@@ -10,13 +10,13 @@ import { hideBin } from 'yargs/helpers';
 
 import { lowLevelWalk } from '../utils/walk.js';
 
-async function main(argv: any) {
+async function main(argv) {
   const { dest, dataFrom } = argv;
   fs.writeFileSync(dest, JSON.stringify(await enumerateFeatures(dataFrom)));
 }
 
 async function enumerateFeatures(dataFrom: string) {
-  const feats = [];
+  const feats: string[] = [];
 
   const walker = dataFrom
     ? lowLevelWalk(
diff --git a/scripts/fix/feature-order.ts b/scripts/fix/feature-order.ts
index f8067c728..530a207bd 100644
--- a/scripts/fix/feature-order.ts
+++ b/scripts/fix/feature-order.ts
@@ -24,7 +24,7 @@ export function orderFeatures(key: string, value: Identifier): Identifier {
     value = Object.keys(value)
       .sort(compareFeatures)
       .reduce((result: { [index: string]: any }, key: string) => {
-        result[key] = (value as any)[key];
+        result[key] = value[key];
         return result as Identifier;
       }, {});
   }
diff --git a/scripts/fix/property-order.ts b/scripts/fix/property-order.ts
index 5c284b5c7..f6bd392d4 100644
--- a/scripts/fix/property-order.ts
+++ b/scripts/fix/property-order.ts
@@ -26,7 +26,7 @@ function doOrder(
   order: string[],
 ): CompatStatement | StatusBlock {
   return order.reduce((result: { [index: string]: any }, key: string) => {
-    if (key in value) result[key] = (value as any)[key];
+    if (key in value) result[key] = value[key];
     return result;
   }, {}) as CompatStatement | StatusBlock;
 }
diff --git a/scripts/lib/extend.ts b/scripts/lib/extend.ts
index 26322a45c..4dcaf0f0e 100644
--- a/scripts/lib/extend.ts
+++ b/scripts/lib/extend.ts
@@ -8,11 +8,11 @@ class DuplicateCompatError extends Error {
   }
 }
 
-function isPlainObject(v: any): v is object {
+function isPlainObject(v): v is object {
   return typeof v === 'object' && v !== null && !Array.isArray(v);
 }
 
-export default function extend(target: any, source: any, feature = ''): void {
+export default function extend(target, source, feature = ''): void {
   if (!isPlainObject(target) || !isPlainObject(source)) {
     throw new Error('Both target and source must be plain objects');
   }
@@ -25,13 +25,9 @@ export default function extend(target: any, source: any, feature = ''): void {
         // If attempting to merge __compat, we have a double-entry
         throw new DuplicateCompatError(feature);
       }
-      extend(
-        (target as any)[key],
-        value,
-        feature + `${feature ? '.' : ''}${key}`,
-      );
+      extend(target[key], value, feature + `${feature ? '.' : ''}${key}`);
     } else {
-      (target as any)[key] = value;
+      target[key] = value;
     }
   }
 }
diff --git a/scripts/migrations/007-experimental-false.test.ts b/scripts/migrations/007-experimental-false.test.ts
index 9efd2c2e5..164054dbf 100644
--- a/scripts/migrations/007-experimental-false.test.ts
+++ b/scripts/migrations/007-experimental-false.test.ts
@@ -2,12 +2,13 @@
  * See LICENSE file for more information. */
 
 import assert from 'node:assert/strict';
+import { CompatStatement } from '../../types/types.js';
 
 import { fixExperimental } from './007-experimental-false.js';
 
 describe('fixExperimental()', () => {
   it('chrome + firefox + safari', () => {
-    const bcd = {
+    const bcd: any = {
       api: {
         fetch: {
           __compat: {
@@ -30,14 +31,14 @@ describe('fixExperimental()', () => {
           },
         },
       },
-    } as any;
+    };
     assert.equal(bcd.api.fetch.__compat.status.experimental, true);
     fixExperimental(bcd);
     assert.equal(bcd.api.fetch.__compat.status.experimental, false);
   });
 
   it('just chrome + firefox', () => {
-    const bcd = {
+    const bcd: any = {
       api: {
         fetch: {
           __compat: {
@@ -57,10 +58,10 @@ describe('fixExperimental()', () => {
               standard_track: true,
               deprecated: false,
             },
-          },
+          } as CompatStatement,
         },
       },
-    } as any;
+    };
     assert.equal(bcd.api.fetch.__compat.status.experimental, true);
     fixExperimental(bcd);
     assert.equal(bcd.api.fetch.__compat.status.experimental, false);
diff --git a/scripts/release/mirror.ts b/scripts/release/mirror.ts
index 235e5556b..38a6cffaa 100644
--- a/scripts/release/mirror.ts
+++ b/scripts/release/mirror.ts
@@ -153,7 +153,7 @@ const copyStatement = (
 ): SimpleSupportStatement => {
   const newData: { [index: string]: any } = {};
   for (const i in data) {
-    newData[i] = (data as any)[i];
+    newData[i] = data[i];
   }
 
   return newData as SimpleSupportStatement;
diff --git a/scripts/release/pulls.ts b/scripts/release/pulls.ts
index 74284f166..a7e1509d5 100644
--- a/scripts/release/pulls.ts
+++ b/scripts/release/pulls.ts
@@ -26,7 +26,7 @@ function appendLabel(query: string): string {
   return `${query} label:${releaseNotesLabels.map((l) => `"${l}"`).join(',')}`;
 }
 
-function main(args: any): void {
+function main(args): void {
   const {
     startVersionTag: start,
     endVersionTag: end,
diff --git a/scripts/release/utils.ts b/scripts/relea [...]

2022-06-14 10:21 UTC, merged