Update Edge versions for RTCDtlsTransport API
mdn/browser-compat-data pull request #16941
Opened 2022-07-12 10:17 UTC by queengooborg

This PR updates and corrects the real values for Microsoft Edge for the `RTCDtlsTransport` API, based upon results from the [mdn-bcd-collector](https://mdn-bcd-collector.appspot.com) project (v6.0.8).

Tests Used: https://mdn-bcd-collector.appspot.com/tests/api/RTCDtlsTransport

_Check out the [collector's guide on how to review this PR](https://github.com/foolip/mdn-bcd-collector#reviewing-bcd-changes)._

2022-07-12 14:49 UTC, foolip requested changes

2022-07-12 14:49 UTC, foolip commented on api/RTCDtlsTransport.json
> +                "alternative_name": "transport"
Should there be a `version_removed` for this, or is it really still in Edge, but not in Chrome?

2022-07-13 00:03 UTC, lucalves approved these changes

2022-07-13 10:51 UTC, foolip requested changes

2022-07-13 10:51 UTC, foolip commented on api/RTCDtlsTransport.json
> +                "alternative_name": "dtlsstatechange"
`version_removed`?

2022-07-13 11:52 UTC, merged