Update MediaSession setActionHandler for Safari
mdn/browser-compat-data pull request #17044
Opened 2022-07-19 21:08 UTC by TranquilMarmot

https://w3c.github.io/mediasession/#enumdef-mediasessionaction

`togglemicrophone`, `togglecamera`, and `hangup` are all listed as possible actions but using any of them in Safari 15 results in the following error:

> TypeError: Argument 1 ('action') to MediaSession.setActionHandler must be one of: "play", "pause", "seekbackward", "seekforward", "previoustrack", "nexttrack", "skipad", "stop", "seekto", "settrack"

#### Summary

#### Test results and supporting details

#### Related issues

2022-07-21 19:00 UTC, Ep262626 commented
Why r u sending me this

Eric
________________________________
From: Nate Moore ***@***.***>
Sent: Tuesday, July 19, 2022 4:09:22 PM
To: mdn/browser-compat-data ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [mdn/browser-compat-data] Update MediaSession setActionHandler for Safari (PR #17044)


https://w3c.github.io/mediasession/#enumdef-mediasessionaction

togglemicrophone, togglecamera, and hangup are all listed as possible actions but using any of them in Safari 15 results in the following error:

TypeError: Argument 1 ('action') to MediaSession.setActionHandler must be one of: "play", "pause", "seekbackward", "seekforward", "previoustrack", "nexttrack", "skipad", "stop", "seekto", "settrack"

Summary
Test results and supporting details
Related issues
________________________________
You can view, comment on, or merge this pull request online at:

  https://github.com/mdn/browser-compat-data/pull/17044

Commit Summary

  *   b073407<https://github.com/mdn/browser-compat-data/pull/17044/commits/b0734071e74d1dcafbbf87ab2ead9717ec34c077> Update MediaSession setActionHandler for Safari

File Changes

(1 file<https://github.com/mdn/browser-compat-data/pull/17044/files>)

  *   M api/MediaSession.json<https://github.com/mdn/browser-compat-data/pull/17044/files#diff-da4ef19f7deaf15d57d0e32cb725cd3fac053cec7472c8e871cda30e9562e92c> (4)

Patch Links:

  *   https://github.com/mdn/browser-compat-data/pull/17044.patch
  *   https://github.com/mdn/browser-compat-data/pull/17044.diff

—
Reply to this email directly, view it on GitHub<https://github.com/mdn/browser-compat-data/pull/17044>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AZ4MCPJPGG4HMGYU6VRNSZ3VU4KQFANCNFSM54BK3QKQ>.
You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

2022-07-26 13:15 UTC, queengooborg commented
Hey @TranquilMarmot, thank you for your PR, and welcome to BCD!

Do you have example code or links to the WebKit source code, to help verify this?

2022-07-26 16:12 UTC, TranquilMarmot commented
Sure! On Safari version `15.5 (17613.2.7.1.8)` all of the following fail:

```js
navigator.mediaSession.setActionHandler('togglemicrophone', () => {});
navigator.mediaSession.setActionHandler('togglecamera', () => {});
navigator.mediaSession.setActionHandler('hangup', () => {});
```

They all fail with the same error message:

> TypeError: Argument 1 ('action') to MediaSession.setActionHandler must be one of: "play", "pause", "seekbackward", "seekforward", "previoustrack", "nexttrack", "skipad", "stop", "seekto", "settrack"

---

Testing this, it looks like they also all fail in Firefox verison `103.0b9 (64-bit)` with this error:

> Uncaught TypeError: MediaSession.setActionHandler: 'togglemicrophone' (value of argument 1) is not a valid value for enumeration MediaSessionAction.

I will update the compatibility for Firefox as well.

2022-07-30 20:51 UTC, queengooborg requested changes
Thank you!  I can confirm that neither Firefox or Safari have support for those three action types.  This is LGTM, we just need to update the notes to use HTML formatting (we're debating converting to Markdown) and we'll be good to go!

2022-07-30 20:51 UTC, queengooborg commented on api/MediaSession.json
> +                "notes": "Firefox exposes the API, but does not allow for the `togglemicrophone`, `togglecamera`, and `hangup` action types."
```suggestion
                "notes": "Firefox exposes the API, but does not allow for the <code>togglemicrophone</code>, <code>togglecamera</code>, and <code>hangup</code> action types."
```

2022-07-30 20:51 UTC, queengooborg commented on api/MediaSession.json
> +              "notes": "Safari exposes the API, but does not allow for the `togglemicrophone`, `togglecamera`, and `hangup` action types."
```suggestion
              "notes": "Safari exposes the API, but does not allow for the <code>togglemicrophone</code>, <code>togglecamera</code>, and <code>hangup</code> action types."
```

2022-08-01 22:15 UTC, queengooborg requested changes
Thanks!  Re-reading the notes, I think that we could simplify them a little bit, like so:

2022-08-01 22:15 UTC, queengooborg commented on api/MediaSession.json
> +                "notes": "Firefox exposes the API, but does not allow for the <code>togglemicrophone</code>, <code>togglecamera</code>, and <code>hangup</code> action types."
```suggestion
                "notes": "Firefox does not support the <code>togglemicrophone</code>, <code>togglecamera</code>, and <code>hangup</code> action types."
```

2022-08-01 22:15 UTC, queengooborg commented on api/MediaSession.json
> +              "notes": "Safari exposes the API, but does not allow for the <code>togglemicrophone</code>, <code>togglecamera</code>, and <code>hangup</code> action types."
```suggestion
              "notes": "Safari does not support for the <code>togglemicrophone</code>, <code>togglecamera</code>, and <code>hangup</code> action types."
```

2022-08-02 16:26 UTC, queengooborg approved these changes
Thanks, LGTM!

2022-08-02 16:26 UTC, merged