Fix error in MediaQueryList.addEventListener note
mdn/browser-compat-data pull request #17246
Opened 2022-08-04 09:18 UTC by 36degrees

#### Summary

`MediaQueryList.addEventListener` was **not** based on EventTarget before Safari 14, otherwise it would inherit the `addEventListener` and `removeEventListener` methods and so you would not need to use `addListener`.

It looks like [this might have been accidentally flipped in code review](https://github.com/mdn/browser-compat-data/pull/6403#discussion_r463062928) ('is not' => 'was not' => 'is').

#### Test results and supporting details

N/A

#### Related issues

N/A

2022-08-04 10:35 UTC, foolip requested changes
I think we should remove these notes instead. There's already a "EventTarget_inheritance" subfeature that captures this, and *all* browsers have gone through this change, not just Safari.

2022-08-19 16:32 UTC, 36degrees commented
As requested, I've revised this PR to remove the incorrect notes instead, and updated the PR title.

I've force-pushed which means the original edit has been lost, but have tried to capture the history in the commit message instead.

2022-08-19 16:34 UTC, 36degrees commented
Rebased again to bring up to date with changes in the `main` branch.

2022-09-13 08:24 UTC, foolip approved these changes

2022-09-13 08:24 UTC, merged

2022-09-13 08:25 UTC, foolip commented
Thanks @36degrees, and sorry this was left sitting for so long!

2022-09-13 12:31 UTC, 36degrees commented
No worries! Thanks for approving and merging 🎉