Update Safari versions for MerchantValidationEvent API
mdn/browser-compat-data pull request #17386
Opened 2022-08-15 13:12 UTC by queengooborg

This PR updates and corrects the real values for Safari (Desktop and iOS/iPadOS) for the `MerchantValidationEvent` API, based upon results from the [mdn-bcd-collector](https://mdn-bcd-collector.appspot.com) project (v6.1.0).

Tests Used: https://mdn-bcd-collector.appspot.com/tests/api/MerchantValidationEvent

_Check out the [collector's guide on how to review this PR](https://github.com/foolip/mdn-bcd-collector#reviewing-bcd-changes)._

2022-08-23 16:54 UTC, foolip requested changes
This should match https://developer.mozilla.org/docs/Web/API/PaymentRequest/merchantvalidation_event, can you update that data too?

2022-08-23 16:55 UTC, foolip commented
But also confirm if the merchantvalidation event is actually supported, not just assume that the interface data is correct.

2022-08-31 16:25 UTC, foolip requested changes

2022-08-31 16:25 UTC, foolip commented on api/PaymentRequest.json
> +              "version_added": "12.1"
I've confirmed support with https://mdn-bcd-collector.appspot.com/tests/api/PaymentRequest/merchantvalidation_event in Safari 11.1 on BrowserStack. Making an edit like this which is contradicted by collector results will likely result in it surfacing again later, and likely making the change without noticing it's inconsistent with `MerchantValidationEvent`.

2022-08-31 16:27 UTC, foolip commented
> But also confirm if the merchantvalidation event is actually supported, not just assume that the interface data is correct.

This turned out to be important in this case. This is a case of the interface not being exposed even though the event was:
https://github.com/WebKit/WebKit/commit/90a5b4d7316500b38d277d8bca709b33d6ec027e

The event and interface was originally prefixed with `apple`/`Apple` and that's something we could optionally record as well:
https://github.com/WebKit/WebKit/commit/7678653a3cb439d11074cbe8c5b7d47aa31d1905

2023-06-23 07:42 UTC, queengooborg commented
This is for pre-2020 browser releases, so I'm going to close this and worry about it another time.

2023-06-23 07:42 UTC, closed without merging