Add data for Intl.[[FallbackSymbol]]
mdn/browser-compat-data pull request #17410
Opened 2022-08-17 12:23 UTC by Josh-Cena

#### Summary

This is something I wish to document. To do this we first need compat data.

#### Test results and supporting details

I shamelessly stole the data from here: https://github.com/ljharb/intl-fallback-symbol

I've confirmed the Node versions myself.

I think the description looks a bit awful. Let me know if there're any concerns.

#### Related issues

2022-08-20 10:14 UTC, queengooborg commented
Hey @Josh-Cena, thanks for adding this in!  Would you mind describing to me what it this feature is used for?

2022-08-20 11:23 UTC, Josh-Cena commented
Sure, here's my draft for the content update:

> ### Return value
> 
> A new `Intl.DateTimeFormat` object.
> 
> > **Note:** The text below describes behavior that is marked by the specification as "optional". It may not work in all environments. Check the [browser compatibility table](#browser_compatibility).
> 
> Normally, `Intl.DateTimeFormat()` can be called with or without [`new`](/en-US/docs/Web/JavaScript/Reference/Operators/new), and a new `Intl.DateTimeFormat` instance is returned in both cases. However, if the [`this`](/en-US/docs/Web/JavaScript/Reference/Operators/this) value is an object that is [`instanceof`](/en-US/docs/Web/JavaScript/Reference/Operators/instanceof) `Intl.DateTimeFormat` (doesn't necessarily mean it's created via `new Intl.DateTimeFormat`; just that it has `Intl.DateTimeFormat.prototype` in its prototype chain), then the value of `this` is returned instead, with the newly created `Intl.DateTimeFormat` object hidden in a `[Symbol(IntlLegacyConstructedSymbol)]` property.
> 
> ```js
> const formatter = Intl.DateTimeFormat.call(
>   { __proto__: Intl.DateTimeFormat.prototype },
>   "en-US",
>   { dateStyle: "full" },
> );
> console.log(Object.getOwnPropertyDescriptors(formatter));
> // {
> //   [Symbol(IntlLegacyConstructedSymbol)]: {
> //     value: DateTimeFormat [Intl.DateTimeFormat] {},
> //     writable: false,
> //     enumerable: false,
> //     configurable: false
> //   }
> // }
> ```
> 
> Note that there's only one actual `Intl.DateTimeFormat` instance here: the one hidden in `[Symbol(IntlLegacyConstructedSymbol)]`. When calling the [`format()`](/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/DateTimeFormat/format) and [`resolvedOptions()`](/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/DateTimeFormat/resolvedOptions) methods on `formatter`, it would correctly use the options stored in that instance, but calling all other methods (e.g. [`formatRange()`](/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/DateTimeFormat/formatRange)) would fail: "TypeError: formatRange method called on incompatible Object", because those methods don't consult the hidden instance's options.
> 
> This behavior does not happen when `Intl.DateTimeFormat()` is called without `new` but with `this` set to anything else that's not an `instanceof Intl.DateTimeFormat`. If you call it directly as `Intl.DateTimeFormat()`, the `this` value is [`Intl`](/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl), and a new `Intl.DateTimeFormat` instance is created normally.

2022-08-27 02:44 UTC, queengooborg requested changes
Alright, thank you for the info!  Just got a couple of small tweaks, and this'll be LGTM!

2022-08-27 02:44 UTC, queengooborg commented on javascript/builtins/Intl/DateTimeFormat.json
> +                "description": "Supports normative optional ChainDateTimeFormat behavior",
```suggestion
                "description": "Supports normative optional <code>ChainDateTimeFormat</code> behavior",
```

2022-08-27 02:44 UTC, queengooborg commented on javascript/builtins/Intl/NumberFormat.json
> +                "description": "Supports normative optional ChainNumberFormat behavior",
```suggestion
                "description": "Supports normative optional <code>ChainNumberFormat</code> behavior",
```

2022-08-28 21:13 UTC, queengooborg approved these changes
Whoops, look like we're missing Firefox Android here...which the linter should have caught?  🤔

2022-08-28 21:13 UTC, queengooborg commented on javascript/builtins/Intl/DateTimeFormat.json
> +                  },
```suggestion
                  },
                  "firefox_android": "mirror",
```

2022-08-28 21:13 UTC, queengooborg commented on javascript/builtins/Intl/NumberFormat.json
> +                  },
```suggestion
                  },
                  "firefox_android": "mirror",
```

2022-08-28 21:27 UTC, queengooborg approved these changes
Thanks, LGTM!

2022-08-28 21:29 UTC, queengooborg requested changes
Ah, wait, almost there -- it looks like Firefox Android support came a little bit later for this feature!

2022-08-28 21:29 UTC, queengooborg commented on javascript/builtins/Intl/DateTimeFormat.json
> +                  "firefox_android": "mirror",
```suggestion
                  "firefox_android": {
                    "version_added": "56"
                  },
```

2022-08-28 21:29 UTC, queengooborg commented on javascript/builtins/Intl/NumberFormat.json
> +                  "firefox_android": "mirror",
```suggestion
                  "firefox_android": {
                    "version_added": "56"
                  },
```

2022-08-28 21:35 UTC, Josh-Cena commented
Ah, I think I removed it because I have no idea when it was introduced...

2022-08-28 22:06 UTC, queengooborg approved these changes
I don't know why the linter isn't verifying the presence of the browser here, because it definitely should be, hmm...  I'll look into it later, thank you for your PR!

2022-08-28 22:06 UTC, merged