Update bgcolor HTML attribute
mdn/browser-compat-data pull request #17478
Opened 2022-08-19 11:19 UTC by queengooborg

This PR updates the data for the `bgcolor` HTML attribute, which fixes #17310.  The version numbers come from other instances of the property, and confirmed by testing the oldest possible browsers in BrowserStack.

2022-08-23 07:38 UTC, foolip commented on html/elements/body.json
> +                "version_added": "1.2"
The `bgcolor` attribute is in the initial revision of WebKit:
https://github.com/WebKit/WebKit/blob/a063c2b75ddebd1edfe9c54c428d762bdb61f794/WebCore/khtml/misc/htmlattrs.in#L13

```suggestion
                "version_added": "1"
```

2022-08-23 07:38 UTC, foolip commented on html/elements/col.json
> +                "version_added": "1.2"
```suggestion
                "version_added": "1"
```

2022-08-23 07:39 UTC, foolip commented on html/elements/col.json
>                "opera": "mirror",
This is probably wrong, can you fix?

2022-08-23 07:39 UTC, foolip commented on html/elements/colgroup.json
> +                "version_added": "1.2"
```suggestion
                "version_added": "1"
```

2022-08-23 07:39 UTC, foolip commented on html/elements/table.json
> +              "opera": "mirror",
Probably wrong.

2022-08-23 07:39 UTC, foolip commented on html/elements/table.json
> +                "version_added": "1.2"
```suggestion
                "version_added": "1"
```

2022-08-23 07:39 UTC, foolip commented on html/elements/tbody.json
> +                "version_added": "1.2"
```suggestion
                "version_added": "1"
```

2022-08-23 07:39 UTC, foolip commented on html/elements/td.json
> +                "version_added": "1.2"
```suggestion
                "version_added": "1"
```

2022-08-23 07:40 UTC, foolip commented on html/elements/tfoot.json
> +                "version_added": "1.2"
```suggestion
                "version_added": "1"
```

2022-08-23 07:40 UTC, foolip commented on html/elements/th.json
> +                "version_added": "1.2"
```suggestion
                "version_added": "1"
```

2022-08-23 07:40 UTC, foolip commented on html/elements/thead.json
> +                "version_added": "1.2"
```suggestion
                "version_added": "1"
```

2022-08-23 07:40 UTC, foolip commented on html/elements/tr.json
> +                "version_added": "1.2"
```suggestion
                "version_added": "1"
```

2022-08-23 07:47 UTC, foolip commented
> This PR updates the data for the `bgcolor` HTML attribute, which fixes #17310. The version numbers come from other instances of the property, and confirmed by testing the oldest possible browsers in BrowserStack.

Can you describe the testing done, with links to the tests where possible? If "other instances of the property" means trusting the data from api.HTML*Element.bgcolor, then it would be good to spell out this assumption. It will often be the case that the content attribute is supported before the script property.

2022-09-11 21:39 UTC, queengooborg commented
> Can you describe the testing done, with links to the tests where possible?

The test code is actually in the issue description!

2022-09-12 11:54 UTC, foolip commented
I see, https://codepen.io/estelle/pen/PoRdJaO then? That's only testing `<thead bgcolor>` and doesn't lend support to most of the changes being made then.

2022-10-13 16:30 UTC, queengooborg commented
Here's an updated example that shows the attribute working on other elements: https://codepen.io/queengooborg/pen/QWrYaXg

2022-10-14 08:06 UTC, foolip requested changes

2022-10-14 08:06 UTC, foolip commented on html/elements/body.json
> +                "version_added": "≤12.1"
The codepen doesn't load in Opera 12.16, but I pasted it into http://software.hixie.ch/utilities/js/live-dom-viewer/?saved=10877 and it's not supported on all elements.

2022-10-24 13:59 UTC, foolip commented
OK, so given http://software.hixie.ch/utilities/js/live-dom-viewer/?saved=10877 some of the data could be set to Opera 12.1, but the current data isn't _wrong_, so let's go.

2022-10-24 14:00 UTC, foolip approved these changes

2022-10-24 14:00 UTC, merged