Add missing features for CanvasRenderingContext2D API
mdn/browser-compat-data pull request #17486
Opened 2022-08-19 12:25 UTC by queengooborg

This PR is a part of a project to add missing interfaces and interface features to BCD that are from an active spec (including WICG specs) and is supported in at least one browser.  This particular PR adds the missing features of the CanvasRenderingContext2D API, populating the results using data from the [mdn-bcd-collector](https://mdn-bcd-collector.appspot.com) project (v6.1.0).

Tests Used: https://mdn-bcd-collector.appspot.com/tests/api/CanvasRenderingContext2D

_Check out the [collector's guide on how to review this PR](https://github.com/foolip/mdn-bcd-collector#reviewing-bcd-changes)._

2022-08-19 21:33 UTC, foolip requested changes
These changes look like they're all for new standard APIs, but can you add spec URLs and set them to experimental as necessary?

2022-08-20 12:52 UTC, foolip approved these changes

2022-08-20 12:52 UTC, foolip commented on api/CanvasRenderingContext2D.json
> +            "experimental": false,
```suggestion
            "experimental": true,
```

2022-08-20 12:52 UTC, foolip commented on api/CanvasRenderingContext2D.json
> +            "experimental": false,
```suggestion
            "experimental": true,
```

2022-08-20 12:52 UTC, foolip commented on api/CanvasRenderingContext2D.json
> +            "experimental": false,
```suggestion
            "experimental": true,
```

2022-08-20 12:52 UTC, foolip commented on api/CanvasRenderingContext2D.json
> +            "experimental": false,
```suggestion
            "experimental": true,
```

2022-08-20 12:52 UTC, foolip commented on api/CanvasRenderingContext2D.json
> +            "experimental": false,
```suggestion
            "experimental": true,
```

2022-08-20 12:52 UTC, foolip commented on api/CanvasRenderingContext2D.json
> +            "experimental": false,
```suggestion
            "experimental": true,
```

2022-08-20 12:52 UTC, foolip commented on api/CanvasRenderingContext2D.json
> +            "experimental": false,
```suggestion
            "experimental": true,
```

2022-08-20 12:52 UTC, foolip commented on api/CanvasRenderingContext2D.json
> +            "experimental": false,
```suggestion
            "experimental": true,
```

2022-08-20 12:52 UTC, foolip commented on api/CanvasRenderingContext2D.json
> +            "experimental": false,
```suggestion
            "experimental": true,
```

2022-08-22 08:59 UTC, Elchi3 approved these changes

2022-08-22 08:59 UTC, merged