improve Navigator.vibrate notes
mdn/browser-compat-data pull request #17514
Opened 2022-08-22 09:17 UTC by mildsunrise

2022-08-26 18:12 UTC, queengooborg requested changes
Thank you for your PR, and welcome to BCD!  Let's tweak the wording slightly to make it read a little better:

2022-08-26 18:12 UTC, queengooborg commented on api/Navigator.json
> +                "notes": "Vibration is disabled. If the window is visible, then <code>navigator.vibrate()</code> returns <code>true</code>, but no vibration takes place (regardless of hardware suppor
```suggestion
                "notes": "Vibration is disabled. If the window is visible, then <code>navigator.vibrate()</code> returns <code>true</code>, but no vibration takes place (regardless of hardware support). Originally, the intent was to disable it for cross-origin frames only (<a href='https://bugzil.la/1591113'>bug 1591113</a>), but the feature was not re-enabled due to abuse concerns (<a href='https://bugzil.la/1653318'>bug 1653318</a>)."
```

2022-08-29 07:57 UTC, mildsunrise commented
sorry, this somehow slipped through my notifications. thanks for the input, I've applied the suggestion :)

2022-08-30 05:56 UTC, queengooborg approved these changes
Thank you, this is LGTM!

2022-08-30 05:57 UTC, merged