Consider `outline` not following border-radius a partial implementation
mdn/browser-compat-data pull request #17598
Opened 2022-08-29 15:46 UTC by cpmsmith

#### Summary
This information is currently in the data, but as a note. It's not tagged to specific versions, either, which means when scanning, for instance, the browser compatibility table on MDN, the Safari column looks the same as browsers which have implemented this. Now that the [spec says this should be done](https://www.w3.org/TR/css-ui-3/#ref-for-border-edge), I think it's reasonable to consider it a partial implementation if it isn't done.

<img width="307" alt="image" src="https://user-images.githubusercontent.com/9437625/187239865-f2aec6e1-0381-4c03-867f-161bfc33c8ec.png">

<img width="348" alt="image" src="https://user-images.githubusercontent.com/9437625/187240669-ae1348e5-240b-4044-af9c-d73d702bc66d.png">

#### Test results and supporting details
The WebKit bug in the note got marked as a duplicate of [this bug](https://bugs.webkit.org/show_bug.cgi?id=20807), so I updated the link.

Also note that on the browsers that have fixed it, I didn't put a `version_removed` property on the partial implementations, only a newer support statement. That seems to be valid, and I'm not totally clear on the semantics of having it vs. not having it, so let me know if I should add it.

#### Related issues
Related to mdn/browser-compat-data#12760, Fyrd/caniuse#6099

2022-10-29 17:02 UTC, queengooborg requested changes
Hi there, thank you for your PR and welcome to BCD!

I'm down for converting this from a note to `partial_implementation`; it's a pretty severe caveat.  We should also add a `version_removed` for when the partial implementation no longer applies.

2022-10-29 17:02 UTC, queengooborg commented on css/properties/outline.json
> +                "version_added": "1",
```suggestion
                "version_added": "1",
                "version_removed": "94",
```

2022-10-31 16:58 UTC, cpmsmith commented on css/properties/outline.json
> +                "version_added": "1",
Done!

2022-10-31 17:14 UTC, queengooborg approved these changes
Thank you, LGTM!

2022-10-31 17:15 UTC, merged

2023-07-26 11:56 UTC, kylemh commented
Hello! This needs to be updated to show just for versions below 16.4: https://webkit.org/blog/13966/webkit-features-in-safari-16-4/#:~:text=Outline%20%2B%20Border%20Radius

2023-07-26 21:06 UTC, cpmsmith commented
> Hello! This should be updated to show just for versions below 16.4: https://webkit.org/blog/13966/webkit-features-in-safari-16-4/#:~:text=Outline%20%2B%20Border%20Radius

Good point—opened #20424