CSS(trig) CSS trig functions enabled by default in Fx 108
mdn/browser-compat-data pull request #18178
Opened 2022-11-08 10:00 UTC by bsmth

CSS trig support for functions (`cos()`, `tan()`, etc.) are enabled by default in Fx 108.

Additionally, constants (`e`, `pi` etc.) can be used inside CSS `calc()` function

### Related issues

- [ ] Parent issue: https://github.com/mdn/content/issues/22115

2022-11-08 11:20 UTC, ramiy commented
In addition to `NaN`, please check `infinity`.

2022-11-08 11:25 UTC, bsmth commented
> In addition to `NaN`, please check `infinity`.

Thanks @ramiy, added in https://github.com/mdn/browser-compat-data/pull/18178/commits/315e0498f6b26efadb26d05e96a82f65e4ac9cd9

2022-11-11 11:07 UTC, queengooborg requested changes
LGTM, just one little nit regarding experimental status!

2022-11-11 11:07 UTC, queengooborg commented on css/types/calc-constant.json
> +              "experimental": false,
```suggestion
              "experimental": true,
```

2022-11-11 11:08 UTC, bsmth commented on css/types/calc-constant.json
> +              "experimental": false,
Great, thank you

2022-11-11 11:11 UTC, merged