Ff018 csp script src
mdn/browser-compat-data pull request #18205
Opened 2022-11-14 02:32 UTC by hamishwillee

FF108 ships the CSP HTTP header directives `script-src-elem` and `script-src-attr` - https://bugzilla.mozilla.org/show_bug.cgi?id=1790621.

This changes "preview" release to "108". Also removes the preferenced version from 108.
- I assume it is OK to lose the information that this is enabled by default in Nightly. 
- I left the preference stuff in there. Release isn't until this time next month, so I'd rather leave it in so people can have the preference if they need it.

Other docs work can be tracked in https://github.com/mdn/content/issues/22113

FYI @queengooborg

2022-11-16 06:55 UTC, queengooborg requested changes
Let's remove the flag data while we're here!

2022-11-18 00:45 UTC, hamishwillee commented
@queengooborg To me it doesn't make sense to remove these before the release is out - we should use tooling to sweep the data afterwards. As per Please see my comments on https://github.com/mdn/browser-compat-data/pull/18081#issuecomment-1319374501

2022-11-21 01:54 UTC, hamishwillee commented
@queengooborg Updated as requested. I'm not particularly concerned about this one being pulled out.

2022-11-22 11:49 UTC, queengooborg approved these changes

2022-11-22 11:49 UTC, merged