22118
mdn/browser-compat-data pull request #18426
Opened 2022-12-14 11:26 UTC by dletorey

#### Summary

I have updated the spec_url links to point to draft.csswg.org/

#### Test results and supporting details

N/A

#### Related issues

N/A

2022-12-16 00:21 UTC, dipikabh commented
I don't think we should add `font-variant-emoji` to the font-variant BCD table. Other constituent longhand `font-variant-*` properties are also not part of the table.

2022-12-16 09:16 UTC, dletorey commented
>I don't think we should add font-variant-emoji to the font-variant BCD table. Other constituent longhand font-variant-* properties are also not part of the table. 
@dipikabh I agree and have removed this

2022-12-16 11:55 UTC, sideshowbarker commented on css/properties/font-variant-emoji.json
> +          "spec_url": "https://w3c.github.io/csswg-drafts/css-fonts-4/#font-variant-emoji-prop",
```suggestion
          "spec_url": "https://w3c.github.io/csswg-drafts/css-fonts/#font-variant-emoji-prop",
```

2022-12-16 11:56 UTC, sideshowbarker commented on css/properties/font-variant.json
> +          "spec_url": "https://w3c.github.io/csswg-drafts/css-fonts-4/#font-variant-prop",
```suggestion
          "spec_url": "https://w3c.github.io/csswg-drafts/css-fonts/#font-variant-prop",
```

2022-12-16 11:59 UTC, sideshowbarker requested changes
BCD policy is to use the un-leveled spec URLs rather than the leveled ones — unless the anchor doesn’t exist in the un-leveled spec but does exist in some leveled version.

In this case, the `#font-variant-emoji-prop` anchor does exist in the un-leveled spec. So we should use the un-leveled spec URL unless there’s some other specific reason for the using the leveled spec. Is there such a reason in this case?

2022-12-20 19:44 UTC, queengooborg commented
It looks like there are three different things this PR is doing.  May we split them into separate PRs for easier review and merging, please?

2022-12-21 10:41 UTC, closed without merging