ReadableStream async iteration deno and node
mdn/browser-compat-data pull request #18867
Opened 2023-02-10 06:32 UTC by hamishwillee

Deno and NOdeJS also support ReadableStream await-for-of syntax (according to spec owners and their docs). Version for NodeJS inferred from the docs here: https://nodejs.org/api/webstreams.html#readablestreamvaluesoptions

I can see that deno supports it, but not what version, so have set to `true`: https://deno.land/api@v1.30.2?s=ReadableStream

This is part of https://github.com/mdn/content/issues/23678

2023-02-10 10:52 UTC, queengooborg commented
I'm thinking that this has been supported since Deno v1.0 -- [rolling the docs back to v1.0](https://deno.land/api@v1.0.0?s=ReadableStream), the interface is still documented.

2023-02-10 10:52 UTC, queengooborg commented
CC @lucacasonato, maybe you have some more insight?

2023-02-10 11:57 UTC, lucacasonato commented
Yes, it's been supported since 1.0

2023-02-10 11:57 UTC, queengooborg requested changes

2023-02-10 11:57 UTC, queengooborg commented on api/ReadableStream.json
> +              "version_added": true
Thanks @lucacasonato!

```suggestion
              "version_added": "1.0"
```

2023-02-11 02:06 UTC, hamishwillee commented
Thanks very much @lucacasonato @queengooborg ! Updated.

2023-02-11 02:07 UTC, queengooborg approved these changes
LGTM, thank you!

2023-02-11 02:07 UTC, hamishwillee commented
PS @lucacasonato is there any easy way to check feature introduction points in deno other than asking you? For nodejs I relied on the docs "introduced in" information. For Chrome I use chome status, or various tools that let you map commit hashes to builds.

2023-02-11 02:11 UTC, hamishwillee commented
@queengooborg I'm not allowed to merge stuff here ...

2023-02-11 02:12 UTC, queengooborg commented
No worries, I was waiting for the tests to complete before merging!

2023-02-11 02:12 UTC, merged