FF111 XMLHttpRequest/HTTP channel - strip Authorization  on cross-origin redirect
mdn/browser-compat-data pull request #19092
Opened 2023-03-10 02:55 UTC by hamishwillee

FF111 strips the `Authorization` header added by developers from cross-origin redirects in fetch(), XMLHttpRequest, and more generally theHTTP channel - see: https://bugzilla.mozilla.org/show_bug.cgi?id=1802086. 

The `fetch()` changes were done in #19064 . This duplicates the exactly the same info for XMLHttpRequest and `Authorization`. That makes sense because these build on fetch(), as per response in https://github.com/mdn/content/issues/22533#issuecomment-1458256595
.

Other docs work for this can be tracked in https://github.com/mdn/content/issues/22533

2023-03-13 03:47 UTC, hamishwillee commented
@queengooborg FYI

2023-03-14 08:51 UTC, queengooborg requested changes

2023-03-14 08:51 UTC, queengooborg commented on http/headers/Authorization.json
> +              },
```suggestion
```

2023-03-16 11:20 UTC, queengooborg approved these changes

2023-03-16 11:20 UTC, merged