Update Chromium data for CanvasFilter API
mdn/browser-compat-data pull request #19916
Opened 2023-05-21 09:41 UTC by queengooborg

This PR updates and corrects version values for Chromium (Chrome, Opera, Samsung Internet, WebView Android) for the `CanvasFilter` API. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v9.2.2).

_Check out the [collector's guide on how to review this PR](https://github.com/GooborgStudios/mdn-bcd-collector#reviewing-bcd-changes)._

Tests Used: https://mdn-bcd-collector.gooborg.com/tests/api/CanvasFilter

2023-05-21 10:03 UTC, Elchi3 requested changes
Seems like it wasn't removed but hidden behind a pref: https://source.chromium.org/chromium/chromium/src/+/261e99764f4895065f52c56a1a6c6709b2e0e6f4

2023-05-21 10:04 UTC, Elchi3 reviewed
Also, seems like the spec url anchor doesn't work anymore. Doesn't @sideshowbarker normally detect when this happens? :)

2023-05-22 06:57 UTC, sideshowbarker commented
> Also, seems like the spec url anchor doesn't work anymore. Doesn't @sideshowbarker normally detect when this happens? :)

My stuff completely ignores any feature that doesn’t have an `mdn_url` value. So I would never catch the bad fragment for this unless we were to add an article for it in MDN to document it, and then add the `mdn_url` for that here.

But in this case, it seems we anyway have nothing to document, right? — Because there is actually no `CanvasFilter` object in the current spec. There _was_ one that was added to the spec in https://github.com/whatwg/html/commit/5db6a65108133a743118094f816d0dd6ba949557 about a year and half ago — but that was subsequently removed from the spec in https://github.com/whatwg/html/commit/c7ad0990516bae9d1bc3009145a8bcde523b584d (due to lack of implementor agreement about it).

So the current state of things seems to be that `CanvasFilter` is neither in the spec nor in any current implementations (since it’s been removed from Blink and was never implemented in any other engines).

2023-05-22 09:29 UTC, sideshowbarker commented on api/CanvasFilter.json
>          "spec_url": "https://html.spec.whatwg.org/multipage/canvas.html#canvasfilter",
```suggestion
```

2023-05-22 09:30 UTC, sideshowbarker commented on api/CanvasFilter.json
>            "spec_url": "https://html.spec.whatwg.org/multipage/canvas.html#dom-canvasfilter",
```suggestion
```

2023-05-22 09:37 UTC, Elchi3 approved these changes
Got it, thanks @sideshowbarker!
LGTM, @queengooborg 👍

2023-05-22 09:37 UTC, merged