FF114 HTMLButtonElement/InputElement.popoverTargetAction/Element
mdn/browser-compat-data pull request #19928
Opened 2023-05-22 03:46 UTC by hamishwillee

FF144 supports this API [`HTMLButtonElement.popoverTargetAction`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLButtonElement/popoverTargetAction), [`HTMLButtonElement.popoverTargetElement`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLButtonElement/popoverTargetElement), [`HTMLInputElement.popoverTargetElement`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLInputElement/popoverTargetElement), [`HTMLInputElement.popoverTargetAction`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLInputElement/popoverTargetAction) in https://bugzilla.mozilla.org/show_bug.cgi?id=1823757

Related docs work can be tracked in https://github.com/mdn/content/issues/26694

2023-05-22 09:55 UTC, Elchi3 requested changes
What about updating these?

- api.HTMLElement.toggle_event
- css.selectors.backdrop.popover
- css.selectors.popover-open
- html.global_attributes.popovertarget
- html.global_attributes.popovertargetaction

2023-05-22 09:56 UTC, Elchi3 reviewed
Meant that as a comment, if the rest of the API is not supported then this PR is fine.

2023-05-23 01:58 UTC, hamishwillee commented
Thanks @Elchi3 All added.

TLDR;
- I missed  `api.HTMLElement.toggle_event` because I relied on it being [decorated with  `dom.element.popover.enabled`](https://searchfox.org/mozilla-central/source/dom/webidl/EventHandler.webidl#105). 
- Normally we separate out APIs, HTML, CSS work in an FF release project. But makes sense here as there seem to be no other docs projects for tracking those parts of the API. I have set version as 114 as none of this is useful without that preference enabled and the ability to launch the popup.

2023-05-23 06:48 UTC, Elchi3 approved these changes
Thanks @hamishwillee! 👍 I think this is a prime example for how the https://github.com/web-platform-dx/feature-set project will help us as well to document all features of a thing.

2023-05-23 06:50 UTC, merged

2023-05-23 10:21 UTC, hamishwillee commented
Thank you. That's an ambitious project, with some BCD overlap. Will be interesting to see how it pans out with the partial implementation of things that we often get across browsers. But yes, that will be useful.