docs(relnote): Fx114 - crossorigin attribute for image and feImage elements
mdn/browser-compat-data pull request #19999
Opened 2023-05-31 09:21 UTC by bsmth

Fx 114 supports `crossorigin` attribute on `<image>` and `<feimage>` elements which allow for specifying client behavior for cross-origin resource requests.

```html
<svg width="200" height="200" xmlns="http://www.w3.org/2000/svg">
  <image
    href="https://example.com/mdn_logo_dark.png"
    height="200"
    width="200"
    crossorigin="use-credentials" />
</svg>
```
__Related issues and pull requests:__
- [ ] Parent issue https://github.com/mdn/content/issues/26690
- [ ] content: https://github.com/mdn/content/pull/27065

__Bugzilla:__
- [BUG-1240357](https://bugzilla.mozilla.org/show_bug.cgi?id=1240357)

__Resources:__
* WPT: https://wpt.live/svg/embedded/image-crossorigin.sub.html
* WPT overview: https://wpt.fyi/results/svg/embedded/image-crossorigin.sub.html?label=master&product=chrome%5Bstable%5D&product=edge%5Bstable%5D&product=firefox%5Bexperimental%5D&product=safari%5Bstable%5D&aligned

2023-05-31 11:36 UTC, Elchi3 requested changes
Can you also add `crossorigin` to https://github.com/mdn/browser-compat-data/blob/main/api/SVGImageElement.json and https://github.com/mdn/browser-compat-data/blob/main/api/SVGFEImageElement.json.

2023-05-31 11:46 UTC, bsmth commented
> Can you also add `crossorigin` to https://github.com/mdn/browser-compat-data/blob/main/api/SVGImageElement.json and https://github.com/mdn/browser-compat-data/blob/main/api/SVGFEImageElement.json. 

Will do 👍

2023-05-31 13:02 UTC, Elchi3 commented on api/SVGImageElement.json
> +          "mdn_url": "https://developer.mozilla.org/docs/Web/API/SVGImageElement/crossorigin",
```suggestion
          "mdn_url": "https://developer.mozilla.org/docs/Web/API/SVGImageElement/crossorigin",
          "spec_url": "https://svgwg.org/svg2-draft/embedded.html#__svg__SVGImageElement__crossOrigin"
```

2023-06-02 10:56 UTC, bsmth commented
Thanks @Elchi3 - applied your suggestion if you want to have a look 👀

2023-06-02 11:00 UTC, merged

2023-06-02 11:06 UTC, bsmth commented
Danke dir 🚀