Add BCD data for Secure Payment Confirmation
mdn/browser-compat-data pull request #20583
Opened 2023-08-22 15:18 UTC by stephenmcgruer

#### Summary

Add an `api/` entry for [Secure Payment Confirmation](https://w3c.github.io/secure-payment-confirmation/). It consists of three main sub-features: 

1. PaymentCredentialInstrument, a dictionary (minor)
2. payment-extension, a WebAuthn extension that the SPC spec defines
3. secure-payment-confirmation, a Payment Request payment method that the SPC spec defines

#### Test results and supporting details

Data was written using the author's knowledge of when SPC released on Chrome, and which other browsers inherit from Chrome. Some of this still needs to be manually verified, such as the status on Opera and Samsung Internet Browser.

2023-08-22 15:19 UTC, stephenmcgruer commented
cc @ianbjacobs - Ian, this is what I have so far for BCD data. PTAL and lmk what you think.

2023-08-24 16:23 UTC, ianbjacobs commented
Thank you, @stephenmcgruer. I skimmed it and it seems reasonable. Would you like me to ping some other browser folks to ask for their review?

2023-09-17 06:04 UTC, queengooborg requested changes

2023-09-17 06:04 UTC, queengooborg commented on api/SecurePaymentConfirmation.json
> +        "mdn_url": "https://developer.mozilla.org/docs/TODO",
```suggestion
```

2023-10-18 02:43 UTC, wbamberg commented
As I understand it, BCD deals in concrete web platform features, not abstractions (although the work on [grouping](https://github.com/openwebdocs/project/issues/169) intends to add something like that). So since there isn't such a concrete thing as `SecurePaymentConfirmation`, it shouldn't be a BCD entry.

Perhaps we could have something like:

- a new file "SecurePaymentConfirmationRequest.json" describing compat for the [`SecurePaymentConfirmationRequest`](https://w3c.github.io/secure-payment-confirmation/#sctn-securepaymentconfirmationrequest-dictionary) dictionary (I know we don't usually document dictionaries, but I think we should. ake an exception here).
- a new subfeature under api.CredentialsContainer.create.publicKey_option.extensions, named "`payment`" and describing compat for the `payment` extension
- a new subfeature under api.PaymentRequest.PaymentRequest, called something like "`secure-payment-confirmation` method", describing compat for this value.

?

2023-10-18 03:53 UTC, queengooborg commented
Good catch, @wbamberg!  I hadn't realized that this was trying to document an entire API inside of one file, rather than an interface.

In regards to the dictionary, I still do not think that it should be documented separately, but rather, placed under the interfaces/methods that utilize it as usual.

2023-10-18 17:00 UTC, wbamberg commented
> In regards to the dictionary, I still do not think that it should be documented separately, but rather, placed under the interfaces/methods that utilize it as usual.

Can you elaborate what "placed under the interfaces/methods that utilize it as usual" means? I thought usual practice for dictionaries is to document them inline in the parameter description, is that what you are referring to here?

The reason I suggest documenting`SecurePaymentConfirmationRequest` separately is that https://developer.mozilla.org/en-US/docs/Web/API/PaymentRequest/PaymentRequest is already a complicated constructor with complicated arguments, and `SecurePaymentConfirmationRequest` is [an additional complicated object with a lot to say about it](https://w3c.github.io/secure-payment-confirmation/#sctn-securepaymentconfirmationrequest-dictionary). Trying to document it inline in the `PaymentRequest()` constructor would make this page really unwieldy (and the design of the API is such that we could have additional forms for `data` in future versions, making it even worse.

So documenting `SecurePaymentConfirmationRequest` separately gives us the space to document it properly, without making the `PaymentRequest()` page ridiculously hard to understand.

2023-11-07 11:14 UTC, queengooborg commented
> Trying to document it inline in the `PaymentRequest()` constructor would make this page really unwieldy (and the design of the API is such that we could have additional forms for `data` in future versions, making it even worse).

On the content side, the dictionary could most certainly be documented separately.  On the BCD side, however, it should definitely be folded into the methods/properties that utilize it, as [per our data guidelines](https://github.com/mdn/browser-compat-data/blob/main/docs/data-guidelines/api.md#dictionaries-and-enumerations-enums).  If we document it separately, it will only regress our dictionary removal project and pose a major infrastructure burden on the collector side if we want to update its data automatically..

2023-12-01 17:04 UTC, ianbjacobs commented
Hi all,
Now that the SPC pull request has been merged [1], what are the next steps for incorporating the compat data? Thanks!

[1] https://github.com/mdn/content/pull/30439

2023-12-01 18:40 UTC, wbamberg commented
I'm not really a BCD expert these days, but it seems to me that we could have the second two points of https://github.com/mdn/browser-compat-data/pull/20583#issuecomment-1767526671, that is:

- a new subfeature under api.CredentialsContainer.create.publicKey_option.extensions, named "payment" and describing compat for the payment extension
- a new subfeature under api.PaymentRequest.PaymentRequest, called something like "secure-payment-confirmation method", describing compat for this payment method.

...so for instance, someone looking at https://developer.mozilla.org/en-US/docs/Web/API/PaymentRequest/PaymentRequest#browser_compatibility would see an additional row labelled something like "`secure-payment-confirmation` method".

If you like I am happy to have a go at a PR for this?

2023-12-01 20:42 UTC, ianbjacobs commented
@wbamberg that's a generous offer. Yes, and thank you very much!

2023-12-04 19:01 UTC, closed without merging