Include Opera 60+ support for `Cross-Origin-Resource-Policy`
mdn/browser-compat-data pull request #20643
Opened 2023-09-01 16:30 UTC by 0xedward

#### Summary

Update Opera's compatibility data for `Cross-Origin-Resource-Policy` (CORP)

#### Test results and supporting details

1. Tested by [running WPT tests on Opera](https://wpt.live/html/cross-origin-embedder-policy/reporting-subresource-corp.https.html) and checked devtools console for CORP related error messages (e.g. `Failed to load resource: net::ERR_BLOCKED_BY_RESPONSE.NotSameOrigin`)
2. [Opera 60](https://blogs.opera.com/desktop/2019/04/opera-60-0-3255-56-stable-update/) is based on Chromium 73, which was the version CORP was added to Chromium.

2023-09-05 11:20 UTC, Elchi3 reviewed
Thanks for you PR! I guess we could set it to "mirror" if we derive the version from Chromium.

2023-09-17 06:03 UTC, queengooborg requested changes

2023-09-17 06:03 UTC, queengooborg commented on http/headers/Cross-Origin-Resource-Policy.json
>              },
```suggestion
            "opera": "mirror",
```

2023-09-17 06:03 UTC, queengooborg commented on http/headers/Cross-Origin-Resource-Policy.json
>                "version_added": false
(Same here, but I can't make a suggestion...)

2023-10-17 12:05 UTC, closed without merging