Remove unneeded `createProperties` object to display compat data
mdn/browser-compat-data pull request #20971
Opened 2023-10-17 04:58 UTC by navorite

#### Summary

This removes the nesting of `createProperties` object parameters to display the compatibility data documentation in the `tabs.create` API.

Fixes #20969

2023-10-17 05:08 UTC, Bobain95 approved these changes

2023-10-22 17:38 UTC, rebloor requested changes

2023-10-22 17:38 UTC, rebloor commented on webextensions/api/tabs.json
> +                },
Please amend to show Edge as "mirror"

2023-10-22 17:38 UTC, rebloor commented on webextensions/api/tabs.json
> +                },
Please amend to show Edge as "mirror"

2023-10-22 17:38 UTC, rebloor commented on webextensions/api/tabs.json
> +                },
Please amend to show Edge as "mirror"

2023-10-22 17:38 UTC, rebloor commented on webextensions/api/tabs.json
> +                },
Please amend to show Edge as "mirror"

2023-10-24 16:16 UTC, rebloor approved these changes

2023-10-24 16:17 UTC, merged