Add missing features for text-underline-position CSS property
mdn/browser-compat-data pull request #21022
Opened 2023-10-19 16:40 UTC by queengooborg

This PR is a part of a project to add missing interfaces and interface features to BCD that are from an active spec (including WICG specs) and is supported in at least one browser. This particular PR adds the missing features of the `text-underline-position` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.2.9).

_Check out the [collector's guide on how to review this PR](https://github.com/openwebdocs/mdn-bcd-collector#reviewing-bcd-changes)._

Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/text-underline-position

2023-11-08 11:57 UTC, Elchi3 requested changes
We can have `left` and `right` separately, but then you need to remove the `left_right` entry.

2023-11-09 10:47 UTC, Elchi3 approved these changes

2023-11-09 10:47 UTC, merged

2023-11-10 04:15 UTC, queengooborg commented
I was actually just about to remove the separate entries for `left` and `right` from the collector, since it apparently has both the separate and joined entries!

Should we also do the same for `above_below` and separate them?

2023-11-10 14:20 UTC, Elchi3 commented
Ah sorry that I jumped on this one. I think generally I like separate features more. Happy to review a PR for `above_below`.