Add AccentColor and AccentColorTest
mdn/browser-compat-data pull request #21150
Opened 2023-11-02 14:28 UTC by xaddict

#### Summary

Added AccentColor and AccentColorText browser compat for system colors

#### Test results and supporting details

Used BrowserStack to test browsers. They are not support in current blink without enable-experimental-web-features so I left that out

2023-11-07 11:31 UTC, queengooborg requested changes
Hey there, thank you for your PR, and welcome to BCD!

I've just got a few requests, but this is looking good to me otherwise:
- Let's tweak the description name (see suggestion) for better formatting.
- Since the feature is supported in Chrome behind a flag, we should probably indicate it as such.  We have a `flags` property that can be utilized in this case.
- Could you provide your test code so we may verify the accuracy of the data?

2023-11-07 11:31 UTC, queengooborg commented on css/types/color.json
> +              "description": "AccentColor, AccentColorText",
```suggestion
              "description": "<code>AccentColor</code> and <code>AccentColorText</code>",
```

2023-11-08 12:46 UTC, xaddict commented
> Hey there, thank you for your PR, and welcome to BCD!
> 
> I've just got a few requests, but this is looking good to me otherwise:
> 
>     * Let's tweak the description name (see suggestion) for better formatting.
> 
>     * Since the feature is supported in Chrome behind a flag, we should probably indicate it as such.  We have a `flags` property that can be utilized in this case.
> 
>     * Could you provide your test code so we may verify the accuracy of the data?

1. Description name: Check
2. I'll look into the "flags" property. Is there a defaults doc page that I may have missed? Because I also want to add that all versions of Safari don't support the selected system accent color yet. They default to Safari blue (the AccentColor of Safari in iOS)
3. The test page is here: http://wpt.live/css/css-color/system-color-support.html I wrote this first only to find out that Chrome did support it (almost everything new is behind a flag in that browser). I opened that page in browserstack and flipped through versions of Chrome, Safari and Firefox on macOS and Windows.

2023-11-10 15:26 UTC, Elchi3 commented on css/types/color.json
> +                  "version_added": false
flags can be set like this:

```suggestion
                  "version_added": false,
                  "flags": [
                    {
                      "type": "preference",
                      "name": "#enable-experimental-web-platform-features",
                      "value_to_set": "true"
                    }
                  ]
```

2023-11-13 08:05 UTC, Elchi3 approved these changes
Thank you! 👍

2023-11-13 08:05 UTC, merged

2023-11-13 08:55 UTC, xaddict commented
> Thank you! 👍

:)

Do you know the throughput time before changes show up on MDN or even caniuse?

2023-11-13 09:48 UTC, Elchi3 commented
BCD releases twice a week, dependabot then runs updates, MDN deploys multiple times a week usually as well. I would say it takes a week maximum. Likely similar for caniuse.

2026-01-29 09:08 UTC, yisibl commented
https://issues.chromium.org/issues/40229450