29787 text wrap
mdn/browser-compat-data pull request #21311
Opened 2023-11-21 16:15 UTC by dletorey

#### Summary

Updated the BCD for `text-wrap` to include separate values as different browsers are releasing different values at different times

#### Test results and supporting details

Tested in Firefox Nightly and Chromium browsers

#### Related issues

- [Implement text-wrap:balance](https://github.com/mdn/content/issues/29787)
- [Enable CSS text-wrap: balance for all channels](https://github.com/mdn/content/issues/30338)
- Content PR - Coming next

2023-11-21 17:53 UTC, zfox23 requested changes
suggestions to add anchors to BCD links

2023-11-21 17:53 UTC, zfox23 commented on css/properties/text-wrap.json
> +            "mdn_url": "https://developer.mozilla.org/docs/Web/CSS/text-wrap",
```suggestion
            "mdn_url": "https://developer.mozilla.org/docs/Web/CSS/text-wrap#stable",
```

2023-11-21 17:53 UTC, zfox23 commented on css/properties/text-wrap.json
> +            "mdn_url": "https://developer.mozilla.org/docs/Web/CSS/text-wrap",
```suggestion
            "mdn_url": "https://developer.mozilla.org/docs/Web/CSS/text-wrap#nowrap",
```

2023-11-21 17:53 UTC, zfox23 commented on css/properties/text-wrap.json
> +            "mdn_url": "https://developer.mozilla.org/docs/Web/CSS/text-wrap",
```suggestion
            "mdn_url": "https://developer.mozilla.org/docs/Web/CSS/text-wrap#balance",
```

2023-11-21 17:53 UTC, zfox23 commented on css/properties/text-wrap.json
> +            "mdn_url": "https://developer.mozilla.org/docs/Web/CSS/text-wrap",
```suggestion
            "mdn_url": "https://developer.mozilla.org/docs/Web/CSS/text-wrap#wrap",
```

2023-11-22 09:36 UTC, dletorey commented
> suggestions to add anchors to BCD links

Just added the link for the `pretty` value too

2023-11-22 13:21 UTC, zfox23 approved these changes
ty!

2023-11-22 13:22 UTC, merged