CSS rx and ry not supported in Safari 17
mdn/browser-compat-data pull request #21410
Opened 2023-12-01 18:29 UTC by sidewayss

Safari does not support this feature.  Note the blue `<rect>` element in this codepen: https://codepen.io/sidewayss/pen/GRPgqvG
AFAICT all of the other SVG geometry CSS properties work in all the browsers except `rx` and `ry` in Safari. The codepen tests those two along with `x`, `y` and `r`, `cx`, and `cy` for `<circle>`.

caniuse.com:
https://caniuse.com/?search=rx
https://caniuse.com/?search=ry

There are no MDN docs pages for these as CSS properties, only as SVG attributes. Those pages ([here](https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/rx) and [here](https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/ry)) mention that in SVG 2 the CSS properties exist, but there is no browser support matrix on those pages.

Screenshots of desktop browsers (I tested some mobile browsers too, but didn't take pics):
Safari 17:
![css-r-Safari](https://github.com/mdn/browser-compat-data/assets/15235202/4b4f7d5e-8999-491f-b0fa-aca83c7fb2a5)

Chrome 119:
![css-r-Chrome](https://github.com/mdn/browser-compat-data/assets/15235202/0decdd13-35e8-4e0f-8b24-2b9afe151bfe)

Firefox 120:
![css-r-Firefox](https://github.com/mdn/browser-compat-data/assets/15235202/8e912979-4534-43fc-a8f3-23a711789e1a)

Opera 105:
![css-r-Opera](https://github.com/mdn/browser-compat-data/assets/15235202/6c6b3b98-63f6-4eda-9f15-db3b2e11b87b)

2023-12-10 17:24 UTC, sidewayss commented
fyi - I have created a Webkit bug for this issue:  https://bugs.webkit.org/show_bug.cgi?id=266090

2023-12-11 12:11 UTC, queengooborg requested changes
The mdn-bcd-collector is detecting that these properties are recognized (see https://mdn-bcd-collector.gooborg.com/tests/css/properties/rx), but it's clear that the CSS properties aren't supported.  We should indicate this with a note.

2023-12-11 12:11 UTC, queengooborg commented on css/properties/rx.json
> +              "version_added": false
```suggestion
              "version_added": false,
              "notes": "The value is recognized, but has no effect. This property is only recognized as an attribute applied to the SVG element.  See <a href='https://webkit.org/b/266090'>bug 266090</a>."
```

2023-12-11 12:11 UTC, queengooborg commented on css/properties/ry.json
> +              "version_added": false
```suggestion
              "version_added": false,
              "notes": "The value is recognized, but has no effect. This property is only recognized as an attribute applied to the SVG element.  See <a href='https://webkit.org/b/266090'>bug 266090</a>."
```

2023-12-11 13:05 UTC, sidewayss commented
I committed your suggestions and fixed the double-spaces after the period in the Notes.  I double-space after periods too.  I would think that the linter here would fix that instead of just complaining, but then I don't see a linter in the checks here.

2023-12-11 13:07 UTC, queengooborg approved these changes
Whoops!  Didn't mean to leave double-spaces in there (I definitely prefer double spacing, haha) -- thanks for the quick updates and fixes!

2023-12-11 13:08 UTC, merged

2023-12-14 13:36 UTC, sidewayss commented
fyi - I just found out that the Safari bug got fixed and merged yesterday based on a 8-month old, not as accurate, version of my Webkit bug: https://github.com/WebKit/WebKit/pull/21679

Not sure when it gets released publicly, but I have asked that question and will hopefully receive a response soon.

Oh well, my timing is at times very strange.