add data for Invokers (invoketarget, invokeaction, InvokeEvent)
mdn/browser-compat-data pull request #21542
Opened 2023-12-08 09:58 UTC by keithamus

#### Summary

This PR drafts up the documentation for "Invokers" ([OpenUI explainer](https://open-ui.org/components/invokers.explainer/)). This is a new experimental API for enabling buttons to control interactive elements.

#### Test results and supporting details

- [Chrome Platform Status feature](https://chromestatus.com/feature/5142517058371584)
- [WebKit PR (merged)](https://github.com/WebKit/WebKit/pull/18794)
- [Chromium PR (merged)](https://chromium-review.googlesource.com/c/chromium/src/+/4926471?usp=search)
- [Mozilla PR (merged)](https://phabricator.services.mozilla.com/D189851)

#### Related issues

https://github.com/mdn/content/pull/30829

2023-12-11 10:21 UTC, queengooborg requested changes
Preliminary syntax error fix, will do a full review later!

2023-12-11 10:21 UTC, queengooborg commented on api/HTMLElement.json
> +        "_compat": {
```suggestion
        "__compat": {
```

2023-12-11 11:30 UTC, queengooborg commented
It looks like you've got a number of JSON syntax errors in this PR.  Would you mind fixing those up, and then running `npm run fix` to fix auto-fixable schema/data issues?  (Note: you can run `npm test` to find any errors in the data!)

2023-12-11 11:33 UTC, keithamus commented
Unfortunately `npm t` consumed all my machines ram before it can finish, and then it just hangs.

2023-12-11 11:49 UTC, queengooborg commented
> Unfortunately `npm t` consumes all my machines ram before it can finish, and then it just hangs.

Sorry to hear that!  There's a lot that the linter script does in the project.

If you'd like, I'd be happy to push a commit to fix any remaining issues!

2023-12-11 11:58 UTC, keithamus commented
@queengooborg looks like I managed to get all issues resolved :pray:

2024-03-04 06:57 UTC, queengooborg approved these changes

2024-03-04 06:57 UTC, merged