Reinstate install from Git
mdn/browser-compat-data pull request #21656
Opened 2023-12-18 12:24 UTC by ddbeck

#### Summary

Reinstate the option to install BCD from Git. This is useful to, for example, run analysis against the data of a BCD PR, before it's merged and released. 

#### Test results and supporting details

1. Run `npm install git+https://github.com/mdn/browser-compat-data.git` and attempt to `import` or `require` BCD. 😢 
2. Run `npm install git+https://github.com/ddbeck/browser-compat-data.git#installable-from-HEAD` and attempt to `import` or `require` BCD. 😄

#### Related issues

Regress originated at https://github.com/mdn/browser-compat-data/pull/16593.

2023-12-18 16:09 UTC, queengooborg requested changes
I am a strong -1 on tracking build artifacts in the Git repository, especially a build artifact like `data.json`, for many reasons:

- Including build artifacts means that contributors will have to update the build artifacts in their PR.  This is anther consumer-unfriendly change; consumers would have to use a local checkout or some environment like github.dev, as they could no longer just use the web editor.
  - This requirement would have turned me away from the project when I first started -- and probably would even today.
- If contributors _do_ update the build artifacts in their PRs, `data.json` is a file that would change in quite literally every single PR, and that means that it will always create a merge conflict any time another PR is merged.  This is a very contributor-unfriendly issue to have.
- If a contributor does _not_ update the build artifacts, then we're left with the issue that the build artifacts would get stale, quickly.  This would mean that the next contributor would have to regenerate the build artifacts, which means including changes unrelated to their PR.

---

By the way, you said that the regress of being unable to install BCD from Git occurred in #16593.  I assume you actually meant #16401, which is when build-time transforms were first introduced for mirroring, which instated the difference of contributor schema vs. published schema.

2023-12-18 17:19 UTC, ddbeck commented
@queengooborg I'm very confused by your comment. What build artifacts are being tracked by Git here? I haven't touched `.gitignore` nor have I checked in `data.json`. It's not clear to me how my changes would require such. Could you spell this out for me?

2023-12-18 17:25 UTC, queengooborg commented
Oh...I'm sorry, I misread what file is being touched.  I thought you were updating `.gitignore`, not `.npmignore`.

2023-12-20 17:40 UTC, queengooborg approved these changes
Okay, now that I've properly read what exactly this PR is doing, this is LGTM.  Apologies for the previous review, I panicked because I thought that `.gitignore` was being updated, not `.npmignore`.

Small nit: we could actually probably just remove `.npmignore` altogether?  Since we deploy from the build/ folder, the `.npmignore` doesn't really have any effect.

2023-12-28 01:16 UTC, merged

2024-01-02 13:13 UTC, ddbeck commented
Thanks, @queengooborg!

> Small nit: we could actually probably just remove `.npmignore` altogether? Since we deploy from the build/ folder, the `.npmignore` doesn't really have any effect.

I'll put it on my to do list to experiment with this a bit. IIRC, in the absence of a `.npmignore`, npm uses `.gitignore`. We might still need an _empty_ `.npmignore`, for the changes in this PR to continue to work.