add spec-url for `MerchantValidationEvent`
mdn/browser-compat-data pull request #21738
Opened 2023-12-25 10:41 UTC by skyclouds2001

#### Summary

the spec is at https://w3c.github.io/merchant-validation/, which is deprecated but not remove from standard

#### Test results and supporting details

#### Related issues

2023-12-25 11:24 UTC, teoli2003 approved these changes
👍

2023-12-25 11:25 UTC, teoli2003 requested changes
Prior to land this we have to understand why Merchant-validation is not listed in w3c/browser-specs

2023-12-25 13:54 UTC, teoli2003 commented
I guess we should set the _deprecated_ flag to true and the _standard_ to false. What do you think @queengooborg ?

2023-12-25 15:41 UTC, skyclouds2001 commented
![image](https://github.com/mdn/browser-compat-data/assets/95597335/98751e73-4e88-4abc-93d2-e9f87b6c7a6f)

I check again, I guess this suggest it is intended to suugest that this is not a part of standard anymore

2023-12-26 15:18 UTC, skyclouds2001 commented
see https://github.com/w3c/browser-specs/issues/1162#issuecomment-1869205656 and https://github.com/w3c/browser-specs/pull/1163#issue-2055966690, it seems that this is deprecated, but, still a part of standard

2023-12-27 07:35 UTC, tidoust commented
> but, still a part of standard

Not sure what you would call "a part of standard" and what that status may entail for BCD, but a Note is purely informative and not what W3C would call a standard. The Note merely exists to document how the feature was envisioned before it got removed from the actual standard.

2023-12-27 07:46 UTC, teoli2003 commented
Thanks @tidoust.

I think we shouldn't merge this, but let's have another opinion before. cc/ @Elchi3 @queengooborg

2023-12-28 01:15 UTC, queengooborg commented
Yeah, if you look at the CI test, you'll notice that the spec URL is unknown.  Since we defer definition of what specs are standards track to `browser-specs`, and this spec URL isn't present in `browser-specs`, we shouldn't add them in or call them standard.

2023-12-28 01:15 UTC, closed without merging