Add clonable attribute to ShadowRoot
mdn/browser-compat-data pull request #21948
Opened 2024-01-17 13:02 UTC by pepelsbey

⚠️ In draft because I’m figuring out support in Firefox Nightly

#### Summary

Added new ShadowRoot `clonable` attribute per updated DOM spec:

- Available in Firefox Nightly 122
- Available in Safari TP 186
- Not available yet in Chrome Canary

#### Test results and supporting details

How I tested support in the DevTools console:

```js
const host = document.createElement('div');
const shadowRoot = host.attachShadow({mode: 'open', cloneable: true});
shadowRoot.cloneable
```

- https://github.com/whatwg/dom/pull/1237
- [Bugzilla: Add ShadowRoot::clonable](https://bugzilla.mozilla.org/show_bug.cgi?id=1868428)
- [WebKit: Add ShadowRoot clonable attribute](https://bugs.webkit.org/show_bug.cgi?id=266227)

#### Related issues

- https://github.com/mdn/content/issues/31108

2024-01-19 08:22 UTC, skyclouds2001 commented
specific as an alternate, maybe

2024-01-19 10:23 UTC, pepelsbey commented
> specific as an `alternative_name`, maybe

Nice idea! Still, I’d wait for them to rename it since it won’t be shipped in production.

2024-01-24 10:02 UTC, Elchi3 requested changes
As discussed in the BCD call yesterday

2024-01-24 10:02 UTC, Elchi3 commented on api/ShadowRoot.json
> +              "version_added": false
```suggestion
              "alternative_name": "cloneable",
              "version_added": "preview"
```

2024-01-24 10:41 UTC, pepelsbey commented
> As discussed in the BCD call yesterday

Thanks!

2024-01-24 10:53 UTC, Elchi3 approved these changes
Thanks! 👍

2024-01-24 10:53 UTC, merged