Chromium 125 adds Attribution Reporting API support
mdn/browser-compat-data pull request #23266
Opened 2024-06-05 12:55 UTC by queengooborg

This PR updates and corrects version values for Chromium (Chrome, Opera, Samsung Internet, WebView Android) for the `attributionSrc` member of various APIs. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.10.7).

_Check out the [collector's guide on how to review this PR](https://github.com/openwebdocs/mdn-bcd-collector#reviewing-bcd-changes)._

Tests Used: https://mdn-bcd-collector.gooborg.com/tests/api/HTMLAnchorElement/attributionSrc

2024-06-06 09:31 UTC, Elchi3 requested changes
So 117 was determined in https://github.com/mdn/browser-compat-data/pull/20460 and I think it doesn't make sense to have a subset of the features marked as shipping in 125 now. I think unless @chrisdavidmills or @foolip have other information this should stay 117 and we should have a override in the collect.

2024-06-06 09:33 UTC, queengooborg commented
117 was actually falsely deducted -- see https://github.com/mdn/browser-compat-data/pull/20460#issuecomment-1773690495!

2024-06-06 09:36 UTC, Elchi3 commented
If that would be the case then everything in https://github.com/mdn/browser-compat-data/pull/20460 should be 125. However, I can't find a chromestatus or anything that would confirm 125. In fact there are more than 15 chromestatus entries about this topic for various releases and it is quite confusing to me.

2024-06-10 15:25 UTC, foolip commented
It looks like this was shipped using some other method than the typical ones, because it's still marked as experimental in runtime_enabled_features.json5:

https://source.chromium.org/chromium/chromium/src/+/main:third_party/blink/renderer/platform/runtime_enabled_features.json5;l=340-365;drc=5105d4e0e2d3f5b4570d7a2268820173f476d235

2024-06-19 19:15 UTC, queengooborg commented
In #23267, we decided to go for the version number that the collector reported.  Perhaps we should do the same here?

2024-07-01 03:43 UTC, skyclouds2001 commented
The HTML attribute corresponding to the DOM interface property may need to be consistent, too.

2024-10-09 16:51 UTC, caugner approved these changes
The changes LGTM, based on the following evidence I found:

- [Bug 40219585](https://issues.chromium.org/issues/40219585) appears to set the ground work in Chrome 101, and mentions Real-Time Engagement (RTE) trials and Origin Trials (OT).
- [Bug 40277733](https://issues.chromium.org/issues/40277733) appears to roll out the feature in Chrome 116 (and [not in Chrome 115](https://github.com/mdn/browser-compat-data/pull/20460#issue-1833462291)), obviously still behind an Origin Trial.
- [Bug 324250314](https://issuetracker.google.com/issues/324250314) removes the OT requirement in Chrome 123.
- [Bug 331926920](https://issues.chromium.org/issues/331926920) effectively enables the feature in Chrome 125 via [this commit](https://github.com/chromium/chromium/commit/18e051773b1761aff7aaf43be6cb6287ea047770).

I don't think it's worth mentioning the trial phase in BCD.

2024-10-09 16:55 UTC, caugner requested changes
Looking at it again, we appear to be missing some affected features:

- `api.Request.Request.init_attributionReporting_parameter`
- `api.Window.open.features_parameter_attributionsrc`
- `api.fetch.init_attributionReporting_parameter`

2024-10-09 19:06 UTC, skyclouds2001 commented
And
[html.elements.a.attributionsrc](https://github.com/mdn/browser-compat-data/blob/main/html/elements/a.json#L78)
[html.elements.img.attributionsrc](https://github.com/mdn/browser-compat-data/blob/main/html/elements/img.json#L187)
[html.elements.script.attributionsrc](https://github.com/mdn/browser-compat-data/blob/main/html/elements/script.json#L89)

2024-10-09 22:08 UTC, caugner commented
> And
> [html.elements.a.attributionsrc](https://github.com/mdn/browser-compat-data/blob/main/html/elements/a.json#L78)
> [html.elements.img.attributionsrc](https://github.com/mdn/browser-compat-data/blob/main/html/elements/img.json#L187)
> [html.elements.script.attributionsrc](https://github.com/mdn/browser-compat-data/blob/main/html/elements/script.json#L89)

Indeed, good catch!

2024-11-22 11:13 UTC, caugner approved these changes
Fixed up the remaining featuers, LGTM now:

<img width="439" alt="image" src="https://github.com/user-attachments/assets/34f098ac-2abb-4415-b0fa-54716151fcb1">

2024-11-22 11:15 UTC, merged