DNR properties changes
mdn/browser-compat-data pull request #23400
Opened 2024-06-16 23:40 UTC by rebloor

#### Summary

Adds browser compatibility data in support of [Bug 1894128](https://bugzilla.mozilla.org/show_bug.cgi?id=1894128) 
[DNR] Replace MAX_NUMBER_OF_DYNAMIC_AND_SESSION_RULES including:

- adding a note that MAX_NUMBER_OF_DYNAMIC_AND_SESSION_RULES was deprecated in Firefox 128 (I haven't marked the entire property as deprecated given that Safari hasn't yet made any updates)
- MAX_NUMBER_OF_DYNAMIC_RULES  and MAX_NUMBER_OF_SESSION_RULES - new entries, including documentation links (chrome release number determined from https://chromium.googlesource.com/chromium/src/+/eab7fc99e59b69e929d02e43bdcf8bbd75333869/chrome/VERSION)
- - MAX_NUMBER_OF_UNSAFE_DYNAMIC_RULES  and MAX_NUMBER_OF_UNSAFE_SESSION_RULES - new entries, excluding documentation links as these haven't been been implemented in Firefox yet (to be implemented in [bug 1894119](https://bugzilla.mozilla.org/show_bug.cgi?id=1894119))

#### Related issues

Related changes to MDN content in TBA

2024-06-17 19:31 UTC, dotproto requested changes

2024-06-17 19:31 UTC, dotproto commented on webextensions/api/declarativeNetRequest.json
>                },
I reached out to @oliverdunk about Chrome's support of the old property. It appears that while Chrome did not formally mark this property as deprecated, the intent was to replace it. The fact that `nodoc` was added to `MAX_NUMBER_OF_DYNAMIC_AND_SESSION_RULES` in [the same CL](https://source.chromium.org/chromium/chromium/src/+/cbcff7e25340834b9ef92cdb05e20ab4f3a34564) that removed the `nodoc` flags from the new properties is indicative of Chrome's intent to deprecate this property. 

See also WIP Chromium [CL 5637030](https://chromium-review.googlesource.com/c/chromium/src/+/5637030).

```suggestion
                "note": "Deprecated in Chrome 120"
              },
```

2024-06-18 17:15 UTC, dotproto commented on webextensions/api/declarativeNetRequest.json
>                },
Resolved.

2024-06-18 17:17 UTC, dotproto approved these changes

2024-07-13 17:42 UTC, merged

2024-07-13 18:04 UTC, queengooborg commented
Hi @rebloor -- this PR should not have been merged yet if there was a failing test, as BCD requires CI tests to pass before merging.

2024-07-15 23:23 UTC, rebloor commented
@queengooborg I wasn't aware of the linter behavior regarding the addition of URLs once documentation is published. Where would I have found information about this new behavior? So, from now on, for new docs, I shouldn't include the "mdn_url" but wait for them to be added automatically.

2024-08-01 03:40 UTC, queengooborg commented
Sorry for not responding to this earlier, this got buried in my notifications.

New linter behavior isn't something that we've documented in BCD, as it is an internal change that impacts contributors, not consumers.  (Actually, hardly any specific linter rules are documented; only the ones that were originally non-linted policies are documented.) New linter rules are, however, almost always discussed during the BCD weekly calls and aren't implemented before they receive owner consensus.

The motivation for the new MDN URL linter is to reduce the need for manual updates to MDN URLs when pages are created, moved or deleted.  So far, it's been mostly helpful, though this is a case where it hasn't been quite so helpful (the pages were updated but the linter didn't have the updated information yet -- which is why I brought up the idea of making the URL linter warn instead of error).

---

The important part is just making sure that the CI always returns good before merging a PR, even if the issue will eventually fix itself when dependencies are updated.  This is because unlike MDN content, the CI tests for PRs run on EVERY file, not just the ones that are modified.  Thus, if a PR with a failing test is merged, all other open PRs suddenly have failing tests, which halts all BCD development until the CI passes again!

2024-08-01 09:37 UTC, rebloor commented
@queengooborg thanks for that, should I come across another similar issue I'll check with you first rather than assuming it's an issue that would be otherwise fixed. (Are there minutes from the weekly call? Something I could search if I do come across the situations.)

2024-08-02 09:21 UTC, queengooborg commented
There are meeting notes, yes!  Here they are: https://docs.google.com/document/d/e/2PACX-1vS8QeLHJNMAohmVLDLM0d-6EYo1H5Pw95xz9BFHmkmLWoj80H19XZVJdzYvd2YPig6CaC-8x7lpQm9W/pub