Add Bun to BCD
mdn/browser-compat-data pull request #23440
Opened 2024-06-19 06:49 UTC by queengooborg

This PR is a draft of what it would look like to add Bun and its data to BCD, if we desired to do so.  This draft is meant to be a proof of concept only.

Releases are obtained from Bun's GitHub repository.  Compatibility data is obtained from unjs/runtime-compat.

2024-09-27 19:30 UTC, nektro commented
is there anything needed to push this along/fill out more data? happy to pitch in if it'd help

2024-09-27 19:41 UTC, queengooborg commented
This is just a proof of concept right now, and is awaiting owner consensus to add!

2024-12-10 16:48 UTC, caugner commented
Since Bun is currently [covered by runtime-compat](https://runtime-compat.unjs.io/), I would suggest closing this PR for now.

2024-12-10 19:16 UTC, queengooborg commented
NodeJS and Deno are also covered by runtime-compat, but we include data for both of them in BCD.  I think that it's helpful to include Bun's data in BCD especially as there's been lots of consumer interest, and runtime-compat only obtains the data for the latest versions of each runtime.

I would like to keep this PR open as a draft as a reminder to come to a decision.

2025-04-23 23:44 UTC, connerlphillippi commented
@caugner bumping this, we would really love it if your team added support!

2025-07-02 23:57 UTC, alii commented on api/Response.json
> +                "version_added": false
What does `false` mean here? Only commenting as curious/didn't see it in other cases..

2025-07-02 23:58 UTC, alii commented on api/Response.json
> +                "version_added": false
(bun does support the Fetch API! 😄)

2025-07-03 00:18 UTC, queengooborg commented on api/Response.json
> +                "version_added": false
`false` means that the feature is unsupported -- in this case, this particular feature is whether the `body` property is a readable byte stream. [This is the test that's being run](https://mdn-bcd-collector.gooborg.com/tests/api/Response/body/readable_byte_stream).  The error message is "ReadableStreamBYOBReader needs a ReadableByteStreamController", which seems to indicate that [it's not a byte stream](https://developer.mozilla.org/en-US/docs/Web/API/ReadableStreamBYOBReader#:~:text=An%20instance%20of,type%3A%20%22bytes%22).).

Safari also reports `false` for this.

(Don't worry, it's not saying that the entire `Response` / Fetch API is unsupported!)

2025-07-03 00:44 UTC, alii commented on api/Response.json
> +                "version_added": false
Got it, thanks for the helpful explanation!

2025-07-11 22:53 UTC, alii approved these changes

2025-07-11 22:53 UTC, alii commented
Following up here - is there anything we can do at Bun to help get this merged?

2025-07-13 00:59 UTC, queengooborg commented
Getting your review has been the biggest help already, thanks @alii!

I'll be bringing this up again in the next BCD meeting call (which happens every Tuesday at 2am PT / 10am UK / 11am CET, and is open to anyone who wants to participate) to see where we're at!

2025-07-16 11:13 UTC, queengooborg commented
As discussed in the previous meeting, new features may potentially be introduced in patch releases. I will be updating this PR in the near future to track patch releases, as well as update the documentation regarding patch releases, and have marked this PR as a draft in the meantime.

2025-07-18 10:14 UTC, queengooborg commented
Alright, this PR has now been updated to track patch releases for Bun -- and from the updates to the data, it looks like it's a good thing we did!

2025-07-18 17:10 UTC, alii commented on docs/data-guidelines/index.md
> +Since Bun upgrades the WebKit version in every patch release, which may include new features, BCD tracks patch releases for Bun.
Slight semantics nit on the wording here: While it's true that we do upgrade WebKit versions in patches, it's not _always_ the case that a patch will have a new version.

2025-07-24 13:12 UTC, Elchi3 commented on docs/data-guidelines/index.md
> +Since Bun upgrades the WebKit version in every patch release, which may include new features, BCD tracks patch releases for Bun.
```suggestion
Since Bun upgrades the WebKit version also in patch releases, which may include new features, BCD tracks patch releases for Bun.
```

2025-07-24 13:40 UTC, Elchi3 requested changes
Thanks for your PR and thank you everyone for your work on this! :tada:

Reviewing with my BCD owner's hat on and according to https://github.com/mdn/browser-compat-data/blob/main/docs/data-guidelines/browsers.md#addition-of-browsers.

> BCD's owners may choose to adopt a new browser or engine.

I think this has consensus given discussions in recent BCD calls.

> To add a new browser to BCD, we require machine-readable release information, including version numbers, release dates, links to release notes or changelogs, and (if applicable) underlying engine version numbers.

You've added a new file `browsers/bun.json` that contains this info. What I don't see is automated updates to this file. We need at least a follow-up issue filed for this. This needs a script in `scripts/update-browser-releases/` basically.

> a compelling downstream-consumer story (e.g., MDN or caniuse express an interest in showing the data to developers or someone is planning to do something with the data that might plausibly grow BCD's reach beyond those sites)

As far as I understand, MDN has shown interest to show this data. Not sure where to file the request. There is a new MDN front-end in the making. I think Mozilla will soon open source it and announce where to file feature requests for it.

> a compelling data-automation story (e.g., using mdn-bcd-collector to generate data updates)

I think this is in progress, see https://github.com/openwebdocs/mdn-bcd-collector/pull/2582. How far can this be automated? Would it be possible to make it so that the collector sends automated BCD PRs? I'm not volunteering to run the collector for bun regularly and to create BCD PRs. Is anyone volunteering to do this?

> reviewer capacity (e.g., two or more volunteers with the interest and ability to review data changes relating to new and existing releases, or at least one reviewer acting on behalf of the vendor)

My understanding is that @alii and @nektro will be reviewers and can be bothered with any bun-related BCD review requests.

> documentation (e.g., how to get and test a feature in that browser, links to resources that might help with it, etc.)

- You need to update: browser-compat-data/schemas/compat-data-schema.md and add bun in line 198
- You need to update browser-compat-data/schemas/browsers-schema.md in line 5 and add to the table starting in line 90
- I would be good to provide docs (in the collector repo probably) on how to update bun compat data. Especially if this process is not automated, it should be written down what humans should do and in which frequency.

> Data review:

I haven't reviewed all data this PR is adding. I guess that @alii and @nektro did that already and are happy about it. On a high-level, this adds bun to the `api/`, `javascript/builtins` and `webassembly/` folders for features where there is support in bun (opt-in). It is surprising to me that other `javascript/` folders haven't seen bun additions (statements/operators/grammar/etc.). For features without explicit support, no data is added (that is we are not adding any `version_added: false` statements).

2025-07-29 00:47 UTC, queengooborg commented
> > To add a new browser to BCD, we require machine-readable release information, including version numbers, release dates, links to release notes or changelogs, and (if applicable) underlying engine version numbers.
> 
> You've added a new file `browsers/bun.json` that contains this info. What I don't see is automated updates to this file. We need at least a follow-up issue filed for this. This needs a script in `scripts/update-browser-releases/` basically.

I can file a follow-up issue for this!

> > a compelling data-automation story (e.g., using mdn-bcd-collector to generate data updates)
> 
> I think this is in progress, see [openwebdocs/mdn-bcd-collector#2582](https://github.com/openwebdocs/mdn-bcd-collector/pull/2582). How far can this be automated? Would it be possible to make it so that the collector sends automated BCD PRs? I'm not volunteering to run the collector for bun regularly and to create BCD PRs. Is anyone volunteering to do this?

Running tests is made possible by https://github.com/unjs/runtime-compat, which runs tests on the latest versions of Bun (and other runtimes). The Bun team is currently looking into expanding its capabilities so that it can run on additional versions of Bun (and in exchange, NodeJS and Deno).  In the meantime, I've devised a temporary solution, which was how this PR was created!

2025-08-01 01:11 UTC, alii commented
Thanks Florian for the notes here!

Re/ automation, we'd be happy to set something up to run the necessary scripts in CI and submit a pull request on new releases of Bun.

2025-08-01 09:37 UTC, Elchi3 commented
That would be very useful!

2025-08-13 19:17 UTC, queengooborg commented
> It is surprising to me that other `javascript/` folders haven't seen bun additions (statements/operators/grammar/etc.).

I just found out why this is: it appears that this is an issue with unjs/runtime-compat-data (which is providing the backbone for generating these results).  RCD appears to be isolating only the JavaScript builtins when running tests.  I've [submitted a PR to resolve this upstream](https://github.com/unjs/runtime-compat/pull/207), and am now updating this PR accordingly!

2025-08-14 16:37 UTC, caugner commented
(PR Review Companion is failing, because it uses the release data from the `main` branch. As this is an edge-case, the review companion output wouldn't be that helpful anyways, it probably doesn't justify taking the risk of using the PR release data in the review companion.)

2025-08-14 17:34 UTC, queengooborg commented
With the final updates to the data applied, and a plan to set up automatic results collection (which will also apply to Node.js and Deno) in the near future, are there any other details that need addressing?

2025-08-15 09:22 UTC, Elchi3 commented
I still don't see:

1) A BCD issue that tracks implementing auto-updating browsers/bun.json
2) BCD documentation how to update bun data when there is a new bun release. Or alternatively: an issue on the bun project to implement automation that sends PRs to BCD whenever there is a new bun release impacting compat data.

2025-08-16 15:06 UTC, queengooborg commented
I've opened #27599 for automating the release data for all JavaScript runtimes!

Regarding documentation about updating Bun data, we don't really have that for any runtime that we track in BCD?  I do think that's a good idea since we talk about using the mdn-bcd-collector for browsers, but we don't really talk about using runtime-compat for Node.js and Deno yet, and we should probably hold off on documenting it until RCD has been updated to run on _all_ runtime versions, not just the latest!

2025-08-18 08:56 UTC, Elchi3 commented
> I've opened #27599 for automating the release data for all JavaScript runtimes!

Thanks!

> Regarding documentation about updating Bun data, we don't really have that for any runtime that we track in BCD? I do think that's a good idea since we talk about using the mdn-bcd-collector for browsers, but we don't really talk about using runtime-compat for Node.js and Deno yet, and we should probably hold off on documenting it until RCD has been updated to run on _all_ runtime versions, not just the latest!

Could be that we don't have that for deno and node but the guidelines have become stricter (see https://github.com/mdn/browser-compat-data/pull/27213). The goal here is to not add new runtimes/browsers to BCD anymore that outdate quickly. We still need to fix that for node and deno but for new additions (bun), it makes sense to have a plan from the start.

2025-08-25 10:35 UTC, queengooborg commented
I have just opened an OWD project proposal regarding this, to establish a proper plan for not only automatically testing Bun, but Node.js and Deno as well (since I think that a plan for one is a plan for all): https://github.com/openwebdocs/project/issues/229

2025-08-26 09:57 UTC, queengooborg commented
As we discussed in our weekly meeting, I have pulled the changes from #27625 into this PR, so that everything is added all in one go!

2025-08-26 11:43 UTC, caugner commented on .gitignore
> +.cache
```suggestion

```

2025-08-26 11:51 UTC, caugner commented on .gitignore
> +.DS_Store
```suggestion
.DS_Store

```

2025-08-26 11:55 UTC, merged

2025-08-26 18:05 UTC, alii commented
Thank you everyone! 🎉