FF128 HTTP Priority - RFC9218 Extensible Prioritization Scheme for HTTP
mdn/browser-compat-data pull request #23511
Opened 2024-06-25 06:35 UTC by hamishwillee

FF128 Adds support for [RFC 9218 Extensible Prioritization Scheme for HTTP](https://www.rfc-editor.org/rfc/rfc9218.html#name-the-priority-http-header-fi) in https://bugzilla.mozilla.org/show_bug.cgi?id=1865040.

This delivers a `Priority` header that can be sent in any HTTP version to provide a client hint about the relative priority that a resource should be sent by a server, which is added as a subfeature here. 
This is also supported in Chrome 124, which you can get from https://chromestatus.com/feature/5109106573049856 and the [release notes](https://developer.chrome.com/release-notes/124).
There is no indication of support in Safari or Webkit looking briefly through the release notes and doing a search, so I have put as false.

This is more than just the header as it also adds HTTP/2 and HTTP/3 frames to allow a hop-to-hop update of the priority expectations after the header has been sent. However we don't document these AFAIK so I don't have any way to indicate those are also supported as part of this (if I need to, let me know how).

Related docs work can be tracked in https://github.com/mdn/content/issues/33847

2024-06-25 07:50 UTC, Elchi3 requested changes
Thank you!

2024-06-25 07:50 UTC, Elchi3 commented on http/headers/Priority.json
> +      "Expect": {
```suggestion
      "Priority": {
```

2024-06-25 07:50 UTC, Elchi3 commented on http/headers/Priority.json
> +              "version_added": null
```suggestion
              "version_added": false
```

2024-06-25 08:34 UTC, hamishwillee commented on http/headers/Priority.json
> +      "Expect": {
Doh

2024-06-25 08:35 UTC, hamishwillee commented
@Elchi3 Thank you. Sorry, that was sloppy. Accepted both changes.

2024-06-25 08:46 UTC, Elchi3 commented
I've filed https://github.com/w3c/browser-specs/issues/1383 for the spec issue. Usually specs get added within a few days. If you don't want to wait, you will need to add to the exception list.

2024-06-26 11:53 UTC, Elchi3 commented on http/headers/Priority.json
> +          "mdn_url": "https://developer.mozilla.org/docs/Web/HTTP/Headers/Priority",
Content page does not yet exist and we don't want to generate 404 links for BCD's consumers. I will be added automatically once the docs have been published.

```suggestion
```

2024-06-26 11:57 UTC, merged

2024-06-27 23:03 UTC, hamishwillee commented
Thanks @Elchi3 - clearly disappearing for a few days on other work was beneficial :-)