Add BCD for Gamepad features related to trigger-rumble haptic effect
mdn/browser-compat-data pull request #23530
Opened 2024-06-26 16:14 UTC by chrisdavidmills

#### Summary

The Gamepad API [`"trigger-rumble"`](https://w3c.github.io/gamepad/#dom-gamepadhapticeffecttype-trigger-rumble) haptic effect has been supported since Chrome 126 (see the [ChromeStatus entry](https://chromestatus.com/feature/5162940951953408)).

This PR adds BCD for related features:

- `"trigger-rumble"` as an effect type that can be used in the `GampadHapticActuator.effects` property.
- `"trigger-rumble"` as an effect type that can be used in the `GampadHapticActuator.payEffect()` method. 
- `leftTrigger` and `rightTrigger` as params that can be used in the `GampadHapticActuator.payEffect()` method. 

#### Test results and supporting details

#### Related issues

2024-07-02 02:13 UTC, queengooborg requested changes
Some minor changes to the feature names, as well as separating the new parameter feature into individual parameters for machine readability!

2024-07-02 02:13 UTC, queengooborg commented on api/GamepadHapticActuator.json
> +        "trigger_rumble": {
```suggestion
        "type_trigger-rumble": {
```

2024-07-02 02:13 UTC, queengooborg commented on api/GamepadHapticActuator.json
> +        "trigger_rumble": {
```suggestion
        "type_trigger-rumble": {
```

2024-07-02 02:13 UTC, queengooborg commented on api/GamepadHapticActuator.json
> +            "description": "<code>leftTrigger</code> and <code>rightTrigger</code> params",
```suggestion
        "params_leftTrigger_parameter": {
          "__compat": {
            "description": "<code>params.leftTrigger</code> parameter",
```

2024-07-02 02:13 UTC, queengooborg commented on api/GamepadHapticActuator.json
>          }
```suggestion
        },
        "params_rightTrigger_parameter": {
          "__compat": {
            "description": "<code>params.rightTrigger</code> parameter",
            "spec_url": "https://w3c.github.io/gamepad/#dom-gamepadeffectparameters-righttrigger",
            "support": {
              "chrome": {
                "version_added": "126"
              },
              "chrome_android": "mirror",
              "edge": "mirror",
              "firefox": {
                "version_added": false
              },
              "firefox_android": "mirror",
              "ie": {
                "version_added": false
              },
              "oculus": "mirror",
              "opera": "mirror",
              "opera_android": "mirror",
              "safari": {
                "version_added": false
              },
              "safari_ios": "mirror",
              "samsunginternet_android": "mirror",
              "webview_android": "mirror"
            },
            "status": {
              "experimental": true,
              "standard_track": true,
              "deprecated": false
            }
          }
```

2024-07-08 08:42 UTC, chrisdavidmills commented
Your comments all sound pretty reasonable, so I've accepted them all. Thanks @queengooborg!

2024-07-08 09:18 UTC, chrisdavidmills commented
I also just marked the `type` property as deprecated, on the advice of the Google engineering folks. It no longer appears in the spec, so it makes sense.

2024-07-10 12:32 UTC, queengooborg approved these changes

2024-07-10 12:33 UTC, merged