Safari 18.0 adds support for `writingsuggestions` HTML attribute
mdn/browser-compat-data pull request #23613
Opened 2024-07-01 21:51 UTC by jensimmons

#### Summary

Safari 18.0 adds support for `writingsuggestions` HTML attribute

#### Test results and supporting details

https://webkit.org/blog/15443/news-from-wwdc24-webkit-in-safari-18-beta/#html
(there's a test in the article)

2024-07-02 02:04 UTC, queengooborg requested changes

2024-07-02 02:04 UTC, queengooborg commented on api/HTMLElement.json
> +              "version_added": "18.0"
```suggestion
              "version_added": "18"
```

2024-07-02 16:56 UTC, queengooborg commented
Ah, one last little detail: looks like `experimental` needs to be set to `false`!

2024-07-03 17:52 UTC, closed without merging

2024-07-03 17:52 UTC, jensimmons commented
Created new PR here: https://github.com/mdn/browser-compat-data/pull/23650