Validate spec_urls based on webref ids
mdn/browser-compat-data pull request #23958
Opened 2024-07-26 10:21 UTC by Elchi3

Draft testing PR for @tidoust :)

Based on https://github.com/w3c/webref/issues/1198#issuecomment-2251051277, I wrote a quick test to see if webref ids could be used to (deeply) validate BCD's spec_urls. (that is, we want to check if the fragment ids are valid as well, not just the spec hosts).

It spits out a lot of errors and I would be interested to hear if BCD should be using different fragment ids, or if webref is missing these fragment ids, or if something else is going on. Please see the CI failure for the results.

(This is a draft PR that removes our dependency on web-specs and instead fetches raw webref JSON files, we might not want to fetch the data this way, so consider this PR just a test for now)

2024-07-26 14:15 UTC, tidoust commented
> It spits out a lot of errors and I would be interested to hear if BCD should be using different fragment ids, or if webref is missing these fragment ids, or if something else is going on. Please see the CI failure for the results.

I'd say that the good news is that, in most cases, it seems that "something else is going on" ;)

Main categories of errors I see:

1. Fragments in ids extracts are **percent-encoded**. That does not seem to be the case for URLs used in BCD. If percent-encoding seems wrong, we could perhaps change that (I'm always confused as to when that is needed, or good practice). Otherwise, for comparison purpose, some preprocessing is going to be required, see inline.
2. The URL used in BCD may have the **filename**, e.g., `index.html` in https://webassembly.github.io/spec/js-api/index.html#dom-globaldescriptor-mutable. URLs in the ids extracts don't have the filename. The `index.json` file in Webref contains a `nightly.filename` property for each spec that could be used to create the URL variants with the filename if needed. Alternatively, it could perhaps be a good idea to drop that filename in BCD data?
3. Many URLs in BCD use the **series URL**, whereas ids extracts in Webref are **per specification**. For example, you'll have https://drafts.csswg.org/css-logical/#position-properties in BCD, while you'll find https://drafts.csswg.org/css-logical-1/#position-properties in Webref. To find the right level in Webref, you'll need to look at entries in `index.json` in Webref with the same `series.nightlyUrl` as the URL (without fragment) used in BCD, then select the entry whose `shortname` is equal to `series.currentSpecification`.
4. The code does not handle the case where a spec **does not define any ID**. That does happen for some WebGL extensions referenced by BCD, such as [WebGL EXT_disjoint_timer_query](https://registry.khronos.org/webgl/extensions/EXT_disjoint_timer_query/)
5. For IETF RFCs produced by the HTTP WG, Webref prefers the `httpwg.org` URL because its rendering is slightly more user-friendly, whereas BCD seems to use `www.rfc-editor.org` URLs. The latter URL appears as the canonical `url` in Webref, so it should be relatively easy to find what you want if BCD wants to keep using that origin.

And then there are actual broken links in BCD, such as https://tc39.es/proposal-temporal/#sec-get-temporal.zoneddatetime.prototype.timezone. There are also "outdated" URLs, such as https://tc39.es/ecma262/multipage/additional-ecmascript-features-for-web-browsers.html#sec-object.prototype.__defineGetter__, which redirects to https://tc39.es/ecma262/multipage/fundamental-objects.html#sec-object.prototype.__defineGetter__ that appears in Webref.

There may be a few other error cases to dig into.

2024-07-27 08:50 UTC, Elchi3 commented
Fantastique François!! 🎉 
Thanks for the very useful review comment! I've updated the script :) Now we're down to just 338 problems found! :)

What I see now:

- We should change rfc-editor urls to httpwg urls 
- Filenames should be omitted
- Quite a few legit broken fragment links that need to be fixed in BCD (yay, these are the ones I want to chase with this exercise) 

Something I would like for you to take a look:
- There are about 85 links to HTML multipage fragments and upon spot checking they work. Maybe these are missing in webref or what am I missing?

2024-07-27 15:45 UTC, tidoust commented
> There are about 22 links to HTML multipage fragments and upon spot checking they work. Maybe these are missing in webref or what am I missing?

As far as I can tell, all of them are examples of what I called **outdated links**: they work, but that's because the HTML spec has logic in place to redirect past fragments to their new page. Each time, the content referenced by the link moved to another page of the HTML spec and would better be targeted using the new fragment to avoid a redirect.

For example, clicking on https://html.spec.whatwg.org/multipage/browsing-the-web.html#dom-beforeunloadevent-returnvalue makes you load the `browsing-the-web.html` page, which includes some JavaScript that detects the fragment, knows it no longer exists in that page, and redirects you to the `nav-history-apis.html` page where the content was moved. The final URL is https://html.spec.whatwg.org/multipage/nav-history-apis.html#dom-beforeunloadevent-returnvalue. That final URL appears in Webref. Ideally, BCD would always use such final URLs to avoid redirects that consume a bit of time, bandwidth and energy.

2025-06-26 19:26 UTC, caugner requested changes

2025-06-26 19:26 UTC, caugner commented on lint/linter/test-spec-urls.ts
> +};
Before we merge this, we need to find a solution that avoids these downloads.

I'm not sure if it really makes sense to publish `@w3c/ed` as an NPM package, because that's a lot of data, and we only need the IDs. So we might want to publish something similar to @ddbeck's [mdn-content-inventory](https://github.com/ddbeck/mdn-content-inventory) instead.

2025-06-27 06:37 UTC, Elchi3 commented on lint/linter/test-spec-urls.ts
> +};
Yeah, having something similar to Daniel's inventory might be great! Or we combine them so that is only one daily package for updates that does both? Not sure.

In the meantime, should we land the fixes you identified to spec_urls in a separate PR?

2025-06-27 06:55 UTC, caugner commented on lint/linter/test-spec-urls.ts
> +};
If we combine it with the other package, then it will no longer be auto merged in case of spec URL issues. This is why I think it should be a separate package.

But +1 for landing the fixes separately, I'll draft a PR.

2025-07-04 12:04 UTC, Elchi3 commented
As [discussed yesterday](https://github.com/w3c/webref/issues/1198#issuecomment-3032925937), I took an action to see if BCD could validate against spec dfns and headings only. They are more stable than just any arbitrary ids.

I think this wouldn't work so great, see the validation failures at https://github.com/mdn/browser-compat-data/actions/runs/16073192997/job/45362247010?pr=23958#step:5:25.
From quickly glancing over it, it seems that we link to a lot of sections that are meant for web developers. If I remember correctly, @sideshowbarker actually had a project so that BCD always links to these `#ref-for` or `-dev` sections, so that with his tooling the MDN links and BCD information could appear next to it.

So, it looks like for validating deeply, we would need the full catalog of ids that are present in the specs.

2025-07-04 12:08 UTC, Elchi3 commented
Alternatively, we could try to change to the more officially exported dfns and headings, but I think I want to hear from @sideshowbarker so that we're not breaking anything.

2025-07-04 12:34 UTC, tidoust commented
Interesting. So, the `#ref-for` IDs are the ones I called *dangerous* in https://github.com/w3c/webref/issues/1198#issuecomment-3035918024 because the occurrence they target can change with spec updates without anyone noticing.

The `-dev` ones make sense to me. We could perhaps find a way to extract them as definitions in Reffy so that they end up in Webref as well, e.g., with a specific definition data type. That could actually help validate things further: if a doc reference is made to a concept in HTML for which there exists a `-dev` version, use that version instead.

2025-07-04 12:48 UTC, tidoust commented
Ah, and I see some of the `#ref-for` IDs are actually occurrences of the `-dev` pattern. What would be great is if IDs in `domintro` sections (which seems to be the class used to generate "For web developers" sections) that also define a useful anchor would actually get a `-dev` suffix. At least from a theoretical perspective, it seems wrong to hope that https://dom.spec.whatwg.org/#ref-for-dom-document-documentelement%E2%91%A0 will always target the occurrence in the "For web developers" section. In practice, that probably works because these specs are stable, and the "For web developers" sections are always close to the actual definition (so ref number should be 1 or 2). Anyway, as said above, we can probably find a way to integrate them in definitions extracts.

2025-07-06 20:42 UTC, tidoust reviewed
See inline for a couple of suggestions to take headings into account and decode URL fragments before comparison. Running locally, I end up with a list of 1509 links that do not map to dfns and headings.

With these updates, **1506 links** would fail validation. Running tests locally, adding definitions to Webref within "For web developers" sections would fix more than 1000 of these, leaving **433 links** to look into. Within these:

- ~40 links to CSS specs that should be easy to fix. Some use series URLs instead of the level (seems worth fixing as there's no guarantee that a fragment will remain valid across levels in a given spec series).
- 15 links to sections in RFC specs. They should be easy to fix too.
- 32 links to WEBGL sections that use an alternate ID (the heading has an `id` such as "3.2", but then there's also an anchor with a `name` attribute, which BCD seems to use). We should be able to capture the alternate IDs in the headings extracts if they seem valuable.
- 80 links to SVG2. Reason seems to be that the spec does not fully follow the definitions data model. That is more of a pain but should be fixable within Webref.
- 72 links to ECMAScript that target tables or production rules. In some cases, I wonder about these links. That is, they don't strike me as developer-friendly. Wouldn't targeting the enclosing section be better?
- 22 links to HTML that seem worth looking into.
- 111 links to reference occurrences (using `#ref-for`), inherently brittle and dangerous. Some of these seem due to IDL definitions being in prose whereas BCD links to the IDL block instead. Specs are unfortunately not super consistent.
- And ~60 misc. links to review.

Spec improvements would no doubt be useful to address some of the links in the last few buckets.

2025-07-06 20:42 UTC, tidoust commented on lint/linter/test-spec-urls.ts
> +      }
You're going to need headings too (the headings that you extract from the definitions are just the headings of the sections that contain definitions, but plenty of sections do not contain definitions)

```suggestion
      if (spec.dfns) {
        specDefinitions.push(spec.dfns);
      }
      if (spec.headings) {
        specDefinitions.push(spec.headings);
      }
```

2025-07-06 20:42 UTC, tidoust commented on lint/linter/test-spec-urls.ts
> +      );
See previous comment, headings should be added from headings extracts. Also, as with IDs, fragments for dfns and headings are percent encoded in Webref but not in BCD.

```suggestion
      const type = dfn.match(/^([^\/]+)\//)[1];
      const json = await res.json();
      const dfns = json[type];
      return dfns.map((entry) => {
        const url = new URL(entry.href);
        return url.origin + url.pathname + decodeURIComponent(url.hash);
      });
```

2025-07-11 13:28 UTC, tidoust reviewed
Dfns in Webref now contain production rules from the ECMAScript spec, and links that are "for web developers". The latter requires minor adjustments to the code, see inline.

Running the linter locally, this gets us down to **405 links** that fail validation and that target **319 different fragments**.

This includes 29 new links to ECMAScript proposals that got integrated in the main ECMAScript spec. We've flagged the specs as "discontinued" in browser-specs accordingly and links should be updated in BCD. I guess that shows the merit of running such a validation ;)

I'll look into the 111 `#ref-for` links which, as far as I can tell, all target IDL blocks. I may be able to extend the newly introduced `links` mechanism with these.

I noticed a few RFCs missing from browser-specs and that could probably be added.

I also note that `api.Element.attachShadow` links to https://dom.spec.whatwg.org/#ref-for-dom-element-attachshadow① and... that seems to be a good example of a link that changed without anyone noticing? I suspect the link should rather target https://dom.spec.whatwg.org/#ref-for-dom-element-attachshadow②

2025-07-11 13:28 UTC, tidoust commented on lint/linter/test-spec-urls.ts
> +      });
Dfns extracts now also contain anchors that appear in sections that are "For web developers". The anchors complete the underlying definition under a `links` property. The code needs to be adjusted accordingly to also take them into account. Something like:

```suggestion
      return dfns
        .map((entry) => [entry].concat(entry.links ?? []))
        .flatMap(links => links.map(link => {
          const url = new URL(link.href ?? link);
          return url.origin + url.pathname + decodeURIComponent(url.hash);
        }));
```

2025-07-11 15:04 UTC, tidoust commented
For links to IDL terms, specs may follow two distinct patterns:
1. Definition in the IDL block, referenced by the prose. For example, the definition of `pictureInPictureEnabled` appears in an [IDL block](https://w3c.github.io/picture-in-picture/#dom-document-pictureinpictureenabled), while the "definition" in prose is actually a [reference](https://w3c.github.io/picture-in-picture/#ref-for-dom-document-pictureinpictureenabled).
2. Definition in prose, referenced by the IDL block. For example, the definition of `vendorId` appears in [prose](https://wicg.github.io/webusb/#dom-usbdevice-vendorid), while the IDL block contains a [reference](https://wicg.github.io/webusb/#ref-for-dom-usbdevice-vendorid)

I don't think there's broad agreement on which approach is the *right* one. I note that BCD does not seem to be consistent either, and contains links that target either the IDL block or the prose. Typically, among links that fail validation, there are both:
- links to the prose when first pattern is used, e.g., `api.Document.exitPictureInPicture` targets https://w3c.github.io/picture-in-picture/#ref-for-dom-document-exitpictureinpicture
- links to the IDL block when the second pattern is used, e.g., `api.DeviceOrientationEvent.absolute` targets https://w3c.github.io/deviceorientation/#ref-for-dom-deviceorientationevent-absolute

Question is: from a BCD perspective, what would you like links to target for IDL terms? The IDL block or the prose?

Practically speaking, I can easily extract the reference in the IDL block when the second pattern is used. I do not see an easy way to extract the "main" reference in prose when the first pattern is used. Perhaps a rule such as "first normative occurrence right after the IDL block" could work though.

As usual, targeting references that are not qualified in any way is not fantastic: `api.ShadowRoot.pictureInPictureElement` currently targets https://w3c.github.io/picture-in-picture/#ref-for-dom-documentorshadowroot-pictureinpictureelement①⑤ and I suspect the intended link is rather to https://w3c.github.io/picture-in-picture/#ref-for-dom-documentorshadowroot-pictureinpictureelement①③ (no doubt the spec got updated in the meantime and added two more references before this one). That's not the only case, on top of `attachShadow` that I reported in my previous comment, links to deviceorientation seem mostly bogus at first sight. Did I mention that these reference links are brittle and dangerous already? ;)

2025-07-11 16:18 UTC, tidoust commented on lint/linter/test-spec-urls.ts
> +        .map((entry) => [entry].concat(entry.links ?? []))
Another minor improvement: some RFCs have a main heading ID (à la `sec-XX`) and then an alternate one, which usually is a more readable name. The alternate IDs are stored in an `alternateIds` property, and also need to be taken into account:

```suggestion
        .map((entry) => [entry]
          .concat(entry.links ?? [])
          .concat((entry.alternateIds ?? []).map(altId => {
            const url = new URL(entry.href);
            return url.origin + url.pathname + '#' + altId;
          }))
        )
```

That would fix validation for 5 links.

2025-07-14 16:36 UTC, Elchi3 commented
We usually use anchors in the form of `#dom-interface-member` and not `#ref-for-interface-member(number)`. 

So, https://github.com/mdn/browser-compat-data/pull/23958#issuecomment-3062666104 and ~25% of the failures should get fixed by https://github.com/mdn/browser-compat-data/pull/27293.

2025-07-15 07:57 UTC, tidoust commented
> We usually use anchors in the form of `#dom-interface-member` and not `#ref-for-interface-member(number)`.

Ah, that certainly works for me ;) I assumed that you would want to treat these anchors like the ones that point at "for web developers" sections, meaning that you were more looking at pointing at a specific place than at always following what the underlying spec uses as main definition anchor.

2025-07-15 08:08 UTC, Elchi3 commented
I think it is fine but I would certainly welcome if spec authors could agree on consistency for `#dom-interface-member` anchors as well as recognize the importance of these main definition anchors for projects like BCD.

2025-07-21 12:47 UTC, Elchi3 commented
Down to 207 issues! Seems like lots of problems with SVG and WebGL at this point.

2025-07-23 13:26 UTC, tidoust commented
WebGL1 problems should disappear once a new version of Reffy gets released (that's pending release of a new version of webidl2.js with support for the new `async_iterable` generic type).

For SVG links, the specs need an overhaul. I'm reluctant to spend time in Reffy to try to make sense of IDs in these specs in the meantime (for example, for IDL term definitions, we would need to parse the IDL to make sense of the definitions, but the IDL in SVG Paths is currently invalid, so we would need to patch it first). May I suggest skipping checks for links that target `https://svgwg.org/`? The links look good and the SVG specs don't really change for now.

@Elchi3, the remaining ~100 links seem to be mainly things that need to be reviewed one by one. I see links where specs could perhaps be updated. Others where BCD probably should. There will no doubt be a few ones that need to be handled as exceptions to the rule. I'd be happy to hop on the phone and go through them with you. Feel free to ping me if you would fancy that!

2025-07-24 14:48 UTC, Elchi3 commented
Thanks @tidoust! Now we're down to 53! I will look through them and will probably have questions for you :)

2025-08-06 03:56 UTC, hellotherechaunce approved these changes

2026-05-07 13:01 UTC, Elchi3 commented
9 months later and with a big PR merged today that added `spec_urls` to almost every BCD feature, the number of `spec_urls` that couldn't be validated with webref ids increased to 554: https://github.com/mdn/browser-compat-data/actions/runs/25497035639/job/74819432370?pr=23958#step:5:24

2026-05-15 17:28 UTC, caugner commented
Down to 417 issues:

https://github.com/mdn/browser-compat-data/actions/runs/25931020225/job/76224616101?pr=23958

2026-05-19 19:42 UTC, Elchi3 commented
I switched to the new `@webref/xref` package which is available thanks to @tidoust 🥇 

> 4,277 problems (4,176 errors, 101 warnings, 0 infos):

New analysis needed :) Will take a look into this as soon as I can.

2026-05-20 06:45 UTC, tidoust commented
> New analysis needed :)

Quickly glancing at the list of errors, I think that the surge of new errors is due to the same reasons as those listed in https://github.com/mdn/browser-compat-data/pull/23958#issuecomment-2252868241. The package does not solve any of these, it just provides the same data as before in a package ;)

In particular:

- Fragments are percent-encoded in Webref URLs. Now, that, I can probably handle in the `lookup()` function. I'll look into it.
- Many URLs in BCD use the series URL. The package does not know anything about series URLs (it does not know anything about specs beyond their shortname in practice). I see that you dropped the dependency on web-specs, I was more expecting that code to stay, so that you can get from the series URL to the nightly URL of the current spec in the series. It's also fine to push that logic into the `@webref/xref` package. That's just not yet done.

2026-05-20 13:00 UTC, tidoust commented on lint/linter/test-spec-urls.js
> +    if (specURL.includes('#:~:text=')) {
Note that there seem to be wilder URLs in BCD that combine a `#` fragment and a text fragment. For example:
https://www.w3.org/TR/permissions/#dfn-set-permission-0:~:text=origin,-%3A%20text

At a minimum, this should be amended to avoid returning an error when that happens:

```suggestion
    if (specURL.includes(':~:text=')) {
```

It may be worth checking the anchor part first.

2026-05-20 13:54 UTC, Elchi3 commented
> Fragments are percent-encoded in Webref URLs. Now, that, I can probably handle in the lookup() function. I'll look into it.

Thanks for fixing the encoding, that was the other thing I did here before. I applied your fixes from https://github.com/w3c/webref/pull/1950 locally and it does the trick! Looking forward to the new release.

> Many URLs in BCD use the series URL. The package does not know anything about series URLs (it does not know anything about specs beyond their shortname in practice). I see that you dropped the dependency on web-specs, I was more expecting that code to stay, so that you can get from the series URL to the nightly URL of the current spec in the series. It's also fine to push that logic into the @webref/xref package. That's just not yet done.

Yes, good point. I now have [BCD docs about spec_urls](https://github.com/mdn/browser-compat-data/blob/main/docs/data-guidelines/spec_links.md) and we haven't formulated a rule about series. I think we prefer the URLs without the level as the nightly version seem to be the one that is often the most up-to-date. There are exceptions to this when e.g. only a certain leveled spec contains the definition of a feature at all. So, probably we want both. If you want to push some logic for this in webref/xref, that would be great (and reusable by Daniel) but if not, I can probably implement something here.

2026-05-20 13:56 UTC, Elchi3 commented
With the encoding fixed and with ignoring CSS for the moment, these are the remaining problems: 

Spec URLs - 172 problems (172 errors, 0 warnings, 0 infos):

<details><summary>Details</summary>
<p>
<pre>
  ✖ api.CredentialsContainer.create.publicKey_option.extensions.credProtect - Error → Invalid specification URL found: https://fidoalliance.org/specs/fido-v2.2-ps-20250714/fido-client-to-authenticator-protocol-v2.2-ps-20250714.html#sctn-credProtect-extension. 
  ✖ api.CredentialsContainer.create.publicKey_option.extensions.minPinLength - Error → Invalid specification URL found: https://fidoalliance.org/specs/fido-v2.2-ps-20250714/fido-client-to-authenticator-protocol-v2.2-ps-20250714.html#sctn-minpinlength-extension. 
  ✖ api.Document.rootElement - Error → Invalid specification URL found: https://w3c.github.io/svgwg/svg2-draft/struct.html#__svg__SVGDocument__rootElement. 
  ✖ api.ExtendableCookieChangeEvent.changed.partitioned_property - Error → Invalid specification URL found: https://cookiestore.spec.whatwg.org/#dom-cookielistitem-partitioned. 
  ✖ api.ExtendableCookieChangeEvent.deleted.partitioned_property - Error → Invalid specification URL found: https://cookiestore.spec.whatwg.org/#dom-cookielistitem-partitioned. 
  ✖ api.HTMLAnchorElement.hreflang - Error → Invalid specification URL found: https://html.spec.whatwg.org/multipage/text-level-semantics.html#dom-a-hreflang. 
  ✖ api.HTMLAnchorElement.target - Error → Invalid specification URL found: https://html.spec.whatwg.org/multipage/text-level-semantics.html#dom-a-target. 
  ✖ api.HTMLAnchorElement.type - Error → Invalid specification URL found: https://html.spec.whatwg.org/multipage/text-level-semantics.html#dom-a-type. 
  ✖ api.HTMLAreaElement.target - Error → Invalid specification URL found: https://html.spec.whatwg.org/multipage/image-maps.html#dom-area-target. 
  ✖ api.HTMLElement.accessKey - Error → Invalid specification URL found: https://html.spec.whatwg.org/multipage/interaction.html#dom-accesskey. 
  ✖ api.HTMLEmbedElement.width - Error → Invalid specification URL found: https://html.spec.whatwg.org/multipage/embedded-content-other.html#dom-dim-width. 
  ✖ api.HTMLInputElement.disabled - Error → Invalid specification URL found: https://html.spec.whatwg.org/multipage/form-control-infrastructure.html#dom-fe-disabled. 
  ✖ api.HTMLScriptElement.innerText - Error → Invalid specification URL found: https://w3c.github.io/trusted-types/dist/spec/#dom-htmlscriptelement-innertext. 
  ✖ api.HTMLScriptElement.innerText.enforces_trusted_types - Error → Invalid specification URL found: https://w3c.github.io/trusted-types/dist/spec/#dom-htmlscriptelement-innertext. 
  ✖ api.HTMLScriptElement.src.enforces_trusted_types - Error → Invalid specification URL found: https://w3c.github.io/trusted-types/dist/spec/#dom-htmlscriptelement-src. 
  ✖ api.HTMLScriptElement.text.enforces_trusted_types - Error → Invalid specification URL found: https://w3c.github.io/trusted-types/dist/spec/#dom-htmlscriptelement-text. 
  ✖ api.HTMLScriptElement.textContent - Error → Invalid specification URL found: https://w3c.github.io/trusted-types/dist/spec/#dom-htmlscriptelement-textcontent. 
  ✖ api.HTMLScriptElement.textContent.enforces_trusted_types - Error → Invalid specification URL found: https://w3c.github.io/trusted-types/dist/spec/#dom-htmlscriptelement-textcontent. 
  ✖ api.HTMLSelectElement.disabled - Error → Invalid specification URL found: https://html.spec.whatwg.org/multipage/form-control-infrastructure.html#dom-fe-disabled. 
  ✖ api.IDBObjectStore.getAll - Error → Invalid specification URL found: https://w3c.github.io/IndexedDB/#ref-for-dom-idbobjectstore-getall①. 
  ✖ api.IDBObjectStore.getAllKeys - Error → Invalid specification URL found: https://w3c.github.io/IndexedDB/#ref-for-dom-idbobjectstore-getallkeys①. 
  ✖ api.IDBTransaction.abort - Error → Invalid specification URL found: https://w3c.github.io/IndexedDB/#ref-for-dom-idbtransaction-abort②. 
  ✖ api.LargestContentfulPaint.renderTime - Error → Invalid specification URL found: https://w3c.github.io/largest-contentful-paint/#ref-for-dom-largestcontentfulpaint-rendertime. 
  ✖ api.MLGraphBuilder.reverse - Error → Invalid specification URL found: https://www.w3.org/TR/webnn/#api-mlgraphbuilder-reverse. 
  ✖ api.MathMLElement.autofocus - Error → Invalid specification URL found: https://html.spec.whatwg.org/multipage/interaction.html#dom-fe-autofocus. 
  ✖ api.MediaDevices.getSupportedConstraints.return_object_property_groupId - Error → Invalid specification URL found: https://w3c.github.io/mediacapture-main/#dom-mediatrackconstraintset-groupId. 
  ✖ api.MediaEncryptedEvent - Error → Invalid specification URL found: https://w3c.github.io/encrypted-media/#mediaencryptedevent. 
  ✖ api.MessageEvent.MessageEvent - Error → Invalid specification URL found: https://html.spec.whatwg.org/multipage/comms.html#the-messageevent-interface:dom-event-constructor. 
  ✖ api.MessagePort.message_event - Error → Invalid specification URL found: https://html.spec.whatwg.org/multipage/web-messaging.html#handler-messageport-onmessage. 
  ✖ api.MessagePort.messageerror_event - Error → Invalid specification URL found: https://html.spec.whatwg.org/multipage/web-messaging.html#handler-messageport-onmessageerror. 
  ✖ api.MouseEvent.MouseEvent - Error → Invalid specification URL found: https://w3c.github.io/pointerevents/#dom-mouseevent-mouseevent. 
  ✖ api.Navigator.deviceMemory - Error → Invalid specification URL found: https://www.w3.org/TR/device-memory/#sec-device-memory-js-api. 
  ✖ api.Performance.mark.markOptions_parameter - Error → Invalid specification URL found: https://w3c.github.io/user-timing/#dom-performancemarkoptions. 
  ✖ api.Performance.measure.measureOptions_parameter - Error → Invalid specification URL found: https://w3c.github.io/user-timing/#dom-performancemeasureoptions. 
  ✖ api.PerformanceNavigation - Error → Invalid specification URL found: https://w3c.github.io/navigation-timing/#dom-performancenavigation. 
  ✖ api.PerformanceObserver.PerformanceObserver - Error → Invalid specification URL found: https://w3c.github.io/performance-timeline/#dom-performanceobserver-constructor. 
  ✖ api.PerformanceResourceTiming.serverTiming - Error → Invalid specification URL found: https://w3c.github.io/server-timing/#servertiming-attribute. 
  ✖ api.PerformanceTiming - Error → Invalid specification URL found: https://w3c.github.io/navigation-timing/#dom-performancetiming. 
  ✖ api.PromiseRejectionEvent.PromiseRejectionEvent - Error → Invalid specification URL found: https://html.spec.whatwg.org/multipage/webappapis.html#unhandled-promise-rejections:dom-event-constructor. 
  ✖ api.RTCEncodedVideoFrame.RTCEncodedVideoFrame.options_metadata_dependencies_parameter - Error → Invalid specification URL found: https://w3c.github.io/webrtc-encoded-transform/#dom-rtcencodedframemetadata-dependencies. 
  ✖ api.RTCEncodedVideoFrame.getMetadata.return_object_property_dependencies - Error → Invalid specification URL found: https://w3c.github.io/webrtc-encoded-transform/#dom-rtcencodedframemetadata-dependencies. 
  ✖ api.SVGAElement.download - Error → Invalid specification URL found: https://w3c.github.io/svgwg/svg2-draft/linking.html#__svg__SVGAElement__download. 
  ✖ api.SVGAElement.hreflang - Error → Invalid specification URL found: https://w3c.github.io/svgwg/svg2-draft/linking.html#__svg__SVGAElement__hreflang. 
  ✖ api.SVGAElement.ping - Error → Invalid specification URL found: https://w3c.github.io/svgwg/svg2-draft/linking.html#__svg__SVGAElement__ping. 
  ✖ api.SVGAElement.rel - Error → Invalid specification URL found: https://w3c.github.io/svgwg/svg2-draft/linking.html#__svg__SVGAElement__rel. 
  ✖ api.SVGAElement.relList - Error → Invalid specification URL found: https://w3c.github.io/svgwg/svg2-draft/linking.html#__svg__SVGAElement__relList. 
  ✖ api.SVGAElement.target - Error → Invalid specification URL found: https://w3c.github.io/svgwg/svg2-draft/linking.html#__svg__SV [...]

2026-05-21 16:23 UTC, tidoust reviewed
Testing locally with newly released v1.2.0 and suggested inline update (and re-including CSS specs), I end up with 253 errors. They seem to fall into different buckets:

- URLs that indeed need fixing.
- URLs that use "old" IDs that the spec still has (typically, in an empty span) but that are not captured in Webref. Transitioning away from old IDs would seem a good thing to do from a BCD perspective though
- A few SVG URLs for terms due to the fact that the spec does not yet follow the appropriate conventions
- A few URLs that target value definitions in CSS that are also references to a construct defined in yet another CSS spec. Webref does not record them on purpose to avoid creating duplicate definitions in the xref database. I can understand why BCD might still want to link to them though.
- A few RFC URLs because there are new redirects in place on www.rfc-editor.org since... yesterday, apparently.

2026-05-21 16:23 UTC, tidoust commented on lint/linter/test-spec-urls.js
> +    if (!xref.lookup(specURL).length) {
Starting with v1.2.0, lookup can accept series URL provided you're explicit about it:

```suggestion
    if (!xref.lookup(specURL, { series: true }).length) {
```

You may also filter on the spec's standing at the same time:

```suggestion
    if (!xref.lookup(specURL, { series: true, standing: 'good' }).length) {
```

2026-05-27 16:06 UTC, ddbeck commented on lint/linter/test-spec-urls.js
> +    }
An idea: we could check that there's a valid section ID **before** the fragment delimiter. It wouldn't validate the whole link (the text in the fragment could be bogus), but it might highlight potentially stale fragment links after we've added them.

For example, in the URL `https://drafts.csswg.org/css-view-transitions-2/#scoped-vt:~:text=The%20visualization` we could check the substring `https://drafts.csswg.org/css-view-transitions-2/#scoped-vt` is valid (ignoring `:~:text=The%20visualization`).

2026-06-08 13:05 UTC, Elchi3 commented
With https://github.com/mdn/browser-compat-data/pull/29809 applied, I'm down to 76 issues. Lots of CSS specs that I still need to look into. Plus some missing dfns/headings from RFCs (mostly rfc9842).


```
Spec URLs - 76 problems (76 errors, 0 warnings, 0 infos):
  ✖ css.at-rules.import.layer - Error → Invalid specification URL found: https://drafts.csswg.org/css-cascade-5/#ref-for-typedef-layer-name
  ✖ css.at-rules.media.any-hover - Error → Invalid specification URL found: https://drafts.csswg.org/mediaqueries/#any-input
  ✖ css.at-rules.media.any-pointer - Error → Invalid specification URL found: https://drafts.csswg.org/mediaqueries/#any-input
  ✖ css.at-rules.media.calc - Error → Invalid specification URL found: https://drafts.csswg.org/css-values/#calc-notation
  ✖ css.properties.clip-path.path - Error → Invalid specification URL found: https://drafts.csswg.org/css-masking/#ref-for-typedef-basic-shape%E2%91%A0
  ✖ css.properties.column-gap - Error → Invalid specification URL found: https://drafts.csswg.org/css-align/#column-row-gap
  ✖ css.properties.column-gap.flex_context - Error → Invalid specification URL found: https://drafts.csswg.org/css-align/#column-row-gap
  ✖ css.properties.column-gap.grid_context - Error → Invalid specification URL found: https://drafts.csswg.org/css-align/#column-row-gap
  ✖ css.properties.column-gap.multicol_context - Error → Invalid specification URL found: https://drafts.csswg.org/css-align/#column-row-gap
  ✖ css.properties.column-gap.normal - Error → Invalid specification URL found: https://drafts.csswg.org/css-align/#valdef-row-gap-normal
  ✖ css.properties.font-width.percentage - Error → Invalid specification URL found: https://drafts.csswg.org/css-fonts/#valdef-font-width-percentage-0
  ✖ css.properties.gap - Error → Invalid specification URL found: https://drafts.csswg.org/css-align/#gap-shorthand
  ✖ css.properties.gap.flex_context - Error → Invalid specification URL found: https://drafts.csswg.org/css-align/#gap-shorthand
  ✖ css.properties.gap.grid_context - Error → Invalid specification URL found: https://drafts.csswg.org/css-align/#gap-shorthand
  ✖ css.properties.gap.multicol_context - Error → Invalid specification URL found: https://drafts.csswg.org/css-align/#gap-shorthand
  ✖ css.properties.gap.normal - Error → Invalid specification URL found: https://drafts.csswg.org/css-align/#valdef-row-gap-normal
  ✖ css.properties.grid-template-columns.masonry - Error → Invalid specification URL found: https://drafts.csswg.org/css-grid-3/#masonry-layout
  ✖ css.properties.grid-template-rows.masonry - Error → Invalid specification URL found: https://drafts.csswg.org/css-grid-3/#masonry-layout
  ✖ css.properties.hyphens - Error → Invalid specification URL found: https://drafts.csswg.org/css-text/#hyphens-property
  ✖ css.properties.offset-anchor.bottom - Error → Invalid specification URL found: https://drafts.csswg.org/motion/#valdef-offset-anchor-position
  ✖ css.properties.offset-anchor.center - Error → Invalid specification URL found: https://drafts.csswg.org/motion/#valdef-offset-anchor-position
  ✖ css.properties.offset-anchor.left - Error → Invalid specification URL found: https://drafts.csswg.org/motion/#valdef-offset-anchor-position
  ✖ css.properties.offset-anchor.right - Error → Invalid specification URL found: https://drafts.csswg.org/motion/#valdef-offset-anchor-position
  ✖ css.properties.offset-anchor.top - Error → Invalid specification URL found: https://drafts.csswg.org/motion/#valdef-offset-anchor-position
  ✖ css.properties.offset-path.basic_shape - Error → Invalid specification URL found: https://drafts.csswg.org/motion/#valdef-offset-path-basic-shape
  ✖ css.properties.offset-path.url - Error → Invalid specification URL found: https://drafts.csswg.org/motion/#valdef-offset-path-url
  ✖ css.properties.offset-position.bottom - Error → Invalid specification URL found: https://drafts.csswg.org/motion/#valdef-offset-position-position
  ✖ css.properties.offset-position.center - Error → Invalid specification URL found: https://drafts.csswg.org/motion/#valdef-offset-position-position
  ✖ css.properties.offset-position.left - Error → Invalid specification URL found: https://drafts.csswg.org/motion/#valdef-offset-position-position
  ✖ css.properties.offset-position.right - Error → Invalid specification URL found: https://drafts.csswg.org/motion/#valdef-offset-position-position
  ✖ css.properties.offset-position.top - Error → Invalid specification URL found: https://drafts.csswg.org/motion/#valdef-offset-position-position
  ✖ css.properties.outline.thick - Error → Invalid specification URL found: https://drafts.csswg.org/css-borders-4/#valdef-line-style-thick
  ✖ css.properties.outline.thin - Error → Invalid specification URL found: https://drafts.csswg.org/css-borders-4/#valdef-line-style-thin
  ✖ css.properties.overflow-clip-margin.border-box - Error → Invalid specification URL found: https://drafts.csswg.org/css-overflow/#valdef-overflow-clip-margin-visual-box
  ✖ css.properties.overflow-clip-margin.content-box - Error → Invalid specification URL found: https://drafts.csswg.org/css-overflow/#valdef-overflow-clip-margin-visual-box
  ✖ css.properties.overflow-clip-margin.padding-box - Error → Invalid specification URL found: https://drafts.csswg.org/css-overflow/#valdef-overflow-clip-margin-visual-box
  ✖ css.properties.position-visibility.anchors-valid - Error → Invalid specification URL found: https://drafts.csswg.org/css-anchor-position-1/#valdef-position-visibility-anchors-valid
  ✖ css.properties.position-visibility.anchors-visible - Error → Invalid specification URL found: https://drafts.csswg.org/css-anchor-position-1/#valdef-position-visibility-anchors-visible
  ✖ css.properties.row-gap - Error → Invalid specification URL found: https://drafts.csswg.org/css-align/#column-row-gap
  ✖ css.properties.row-gap.flex_context - Error → Invalid specification URL found: https://drafts.csswg.org/css-align/#column-row-gap
  ✖ css.properties.row-gap.grid_context - Error → Invalid specification URL found: https://drafts.csswg.org/css-align/#column-row-gap
  ✖ css.properties.row-gap.normal - Error → Invalid specification URL found: https://drafts.csswg.org/css-align/#valdef-row-gap-normal
  ✖ css.properties.text-align-last.match-parent - Error → Invalid specification URL found: https://drafts.csswg.org/css-text/#valdef-text-match-parent
  ✖ css.properties.text-emphasis.open - Error → Invalid specification URL found: https://drafts.csswg.org/css-text-decor/#valdef-text-emphasis-style-open
  ✖ css.properties.text-underline-offset.percentage - Error → Invalid specification URL found: https://drafts.csswg.org/css-text-decor-4/#valdef-text-underline-offset-percentage
  ✖ css.properties.vertical-align.middle - Error → Invalid specification URL found: https://drafts.csswg.org/css-inline/#valdef-alignment-baseline-middle
  ✖ css.properties.vertical-align.text-bottom - Error → Invalid specification URL found: https://drafts.csswg.org/css-inline/#valdef-alignment-baseline-text-bottom
  ✖ css.properties.vertical-align.text-top - Error → Invalid specification URL found: https://drafts.csswg.org/css-inline/#valdef-alignment-baseline-text-top
  ✖ css.selectors.future - Error → Invalid specification URL found: https://drafts.csswg.org/selectors/#the-future-pseudo
  ✖ css.selectors.interest-source - Error → Invalid specification URL found: https://drafts.csswg.org/selectors/#selectordef-interest-source
  ✖ css.selectors.interest-target - Error → Invalid specification URL found: https://drafts.csswg.org/selectors/#selectordef-interest-target
  ✖ css.selectors.past - Error → Invalid specification URL found: https://drafts.csswg.org/selectors/#the-past-pseudo
  ✖ css.selectors.target-current - Error → Invalid specification URL found: https://drafts.csswg.org/css-overflow-5/#active-scroll-marker
  ✖ css.selectors.view-transition-group-children - Error → Invalid specification URL found: https://drafts.csswg.org/css-view-trans [...]

2026-06-08 13:22 UTC, tidoust commented
> mostly rfc9842

Quick note that, for this one, browser-specs continues to prefer the [`httpwg.org` URL](https://httpwg.org/specs/rfc9842.html) instead of the [`rfc-editor.org` one](https://www.rfc-editor.org/info/rfc9842/). In other words, it's not that the headings are missing from Webref, it's more that Webref uses another URL for the spec (and note the heading IDs are different in the two renditions of the spec...)

2026-06-11 14:15 UTC, Elchi3 commented
30 more to go.

- The WebTransport ones are being talked about in https://github.com/mdn/browser-compat-data/pull/29810
- Most CSS ones are valdefs where I'm actually not quite sure why these aren't dfns.
- Not sure what changed with CSS random, looks like some things were renamed?
- Drafty RFC specs, maybe I'll need to add these to our exception list

```
Spec URLs - 30 problems (30 errors, 0 warnings, 0 infos):
  ✖ api.WebTransportDatagramDuplexStream.incomingHighWaterMark - Error → Invalid specification URL found: https://w3c.github.io/webtransport/#dom-webtransportdatagramduplexstream-incominghighwatermark
  ✖ api.WebTransportDatagramDuplexStream.outgoingHighWaterMark - Error → Invalid specification URL found: https://w3c.github.io/webtransport/#dom-webtransportdatagramduplexstream-outgoinghighwatermark
  ✖ css.properties.clip-path.path - Error → Invalid specification URL found: https://drafts.csswg.org/css-masking/#ref-for-typedef-basic-shape%E2%91%A0
  ✖ css.properties.font-width.percentage - Error → Invalid specification URL found: https://drafts.csswg.org/css-fonts/#valdef-font-width-percentage-0
  ✖ css.properties.offset-anchor.bottom - Error → Invalid specification URL found: https://drafts.csswg.org/motion/#valdef-offset-anchor-position
  ✖ css.properties.offset-anchor.center - Error → Invalid specification URL found: https://drafts.csswg.org/motion/#valdef-offset-anchor-position
  ✖ css.properties.offset-anchor.left - Error → Invalid specification URL found: https://drafts.csswg.org/motion/#valdef-offset-anchor-position
  ✖ css.properties.offset-anchor.right - Error → Invalid specification URL found: https://drafts.csswg.org/motion/#valdef-offset-anchor-position
  ✖ css.properties.offset-anchor.top - Error → Invalid specification URL found: https://drafts.csswg.org/motion/#valdef-offset-anchor-position
  ✖ css.properties.offset-path.basic_shape - Error → Invalid specification URL found: https://drafts.csswg.org/motion/#valdef-offset-path-basic-shape
  ✖ css.properties.offset-path.url - Error → Invalid specification URL found: https://drafts.csswg.org/motion/#valdef-offset-path-url
  ✖ css.properties.offset-position.bottom - Error → Invalid specification URL found: https://drafts.csswg.org/motion/#valdef-offset-position-position
  ✖ css.properties.offset-position.center - Error → Invalid specification URL found: https://drafts.csswg.org/motion/#valdef-offset-position-position
  ✖ css.properties.offset-position.left - Error → Invalid specification URL found: https://drafts.csswg.org/motion/#valdef-offset-position-position
  ✖ css.properties.offset-position.right - Error → Invalid specification URL found: https://drafts.csswg.org/motion/#valdef-offset-position-position
  ✖ css.properties.offset-position.top - Error → Invalid specification URL found: https://drafts.csswg.org/motion/#valdef-offset-position-position
  ✖ css.properties.overflow-clip-margin.border-box - Error → Invalid specification URL found: https://drafts.csswg.org/css-overflow/#valdef-overflow-clip-margin-visual-box
  ✖ css.properties.overflow-clip-margin.content-box - Error → Invalid specification URL found: https://drafts.csswg.org/css-overflow/#valdef-overflow-clip-margin-visual-box
  ✖ css.properties.overflow-clip-margin.padding-box - Error → Invalid specification URL found: https://drafts.csswg.org/css-overflow/#valdef-overflow-clip-margin-visual-box
  ✖ css.properties.position-visibility.anchors-valid - Error → Invalid specification URL found: https://drafts.csswg.org/css-anchor-position-1/#valdef-position-visibility-anchors-valid
  ✖ css.properties.position-visibility.anchors-visible - Error → Invalid specification URL found: https://drafts.csswg.org/css-anchor-position-1/#valdef-position-visibility-anchors-visible
  ✖ css.properties.text-fit - Error → Invalid specification URL found: https://drafts.csswg.org/css-text-5/#text-fit-property
  ✖ css.properties.text-fit.grow - Error → Invalid specification URL found: https://drafts.csswg.org/css-text-5/#valdef-text-fit-grow
  ✖ css.properties.text-fit.none - Error → Invalid specification URL found: https://drafts.csswg.org/css-text-5/#valdef-text-fit-none
  ✖ css.properties.text-fit.shrink - Error → Invalid specification URL found: https://drafts.csswg.org/css-text-5/#valdef-text-fit-shrink
  ✖ css.types.random.element-shared - Error → Invalid specification URL found: https://drafts.csswg.org/css-values-5/#valdef-random-element-shared
  ✖ css.types.random.step - Error → Invalid specification URL found: https://drafts.csswg.org/css-values-5/#ref-for-typedef-calc-sum①⑧
  ✖ http.headers.Idempotency-Key - Error → Invalid specification URL found: https://datatracker.ietf.org/doc/html/draft-ietf-httpapi-idempotency-key-header/#name-the-idempotency-key-http-re
  ✖ http.headers.Set-Cookie.SameSite.none_requires_secure - Error → Invalid specification URL found: https://httpwg.org/http-extensions/draft-ietf-httpbis-rfc6265bis.html#section-5.7-3.19
  ✖ http.headers.Unencoded-Digest - Error → Invalid specification URL found: https://datatracker.ietf.org/doc/html/draft-ietf-httpbis-unencoded-digest#name-the-unencoded-digest-field
```

2026-06-15 13:55 UTC, Elchi3 commented
OK, I think we're almost at a stage where this PR will pass tests. Final steps:

- Need a review and merge for my fixes to the broken spec_urls in BCD: https://github.com/mdn/browser-compat-data/pull/29809
- Need a resolution and merge to some WebTransport renaming https://github.com/mdn/browser-compat-data/pull/29810
- Need a new web/xref package release that contains https://drafts.csswg.org/css-text-5/.
- Need a spec to be evaluated if it is discontinued (and if so, mark the feature as non-standard) https://github.com/w3c/browser-specs/issues/2536

2026-07-07 09:58 UTC, caugner commented
Remaining four issues:

```
Spec URLs - 4 problems (4 errors, 0 warnings, 0 infos):
  ✖ css.properties.overflow-clip-margin.border-box - Error → Invalid specification URL found: https://drafts.csswg.org/css-overflow/#valdef-overflow-clip-margin-visual-box. Check if:
         - there is a more current specification URL
         - the specification is listed in https://github.com/w3c/browser-specs
         - the specification has a "good" standing
         - the fragment id (#) is valid according to @webref/xref.
  ✖ css.types.random.dashed-ident - Error → Invalid specification URL found: https://drafts.csswg.org/css-values-5/#valdef-random-dashed-ident. Check if:
         - there is a more current specification URL
         - the specification is listed in https://github.com/w3c/browser-specs
         - the specification has a "good" standing
         - the fragment id (#) is valid according to @webref/xref.
  ✖ css.types.random.element-shared - Error → Invalid specification URL found: https://drafts.csswg.org/css-values-5/#valdef-random-element-shared. Check if:
         - there is a more current specification URL
         - the specification is listed in https://github.com/w3c/browser-specs
         - the specification has a "good" standing
         - the fragment id (#) is valid according to @webref/xref.
  ✖ css.types.random.step - Error → Invalid specification URL found: [https://drafts.csswg.org/css-values-5/#ref-for-typedef-calc-sum①⑧](https://drafts.csswg.org/css-values-5/#ref-for-typedef-calc-sum%E2%91%A0%E2%91%A7). Check if:
         - there is a more current specification URL
         - the specification is listed in https://github.com/w3c/browser-specs
         - the specification has a "good" standing
         - the fragment id (#) is valid according to @webref/xref.
```

- `overflow-clip-margin: border-box` seems to have been removed from the spec
- `<dashed-ident>` is only in css-values-4: https://drafts.csswg.org/css-values-4/#typedef-dashed-ident
- `<element-shared>` and `<step>` seem to have been replaced by less semantic `<calc-sum>` values

2026-07-07 10:47 UTC, Elchi3 commented
For `random()`, see https://github.com/mdn/browser-compat-data/issues/29954. The old sub features are now non-standard. The new sub features aren't shipping anywhere yet. 

For `overflow-clip-margin: border-box`, it should use the same link as content-box, padding-box. It comes down to the same type.

2026-07-07 10:48 UTC, Elchi3 commented
This is passing for the first time in almost(!) two years 😄  Marking as ready for review.

2026-07-07 14:28 UTC, caugner approved these changes
LGTM.

PS: I took the liberty of pushing two commits adding full test coverage for the `test-spec-urls` linter.

2026-07-08 10:43 UTC, Elchi3 commented
I'm merging this. Thanks everyone for your help! See https://github.com/mdn/browser-compat-data/blob/main/docs/data-guidelines/spec_links.md for documentation.

2026-07-08 10:43 UTC, merged