Remove nonreal values from the schema
mdn/browser-compat-data pull request #24174
Opened 2024-08-20 10:19 UTC by queengooborg

This PR removes nonreal (`true` and `null`) values from the BCD schema entirely.  This follows the removal of all nonreal values throughout BCD, finalizing the process.

2024-11-27 21:27 UTC, danielhjacobs commented
Fixes https://github.com/mdn/yari/issues/11257 by making it a non-issue.

2024-11-30 08:08 UTC, danielhjacobs commented
> Then again, maybe it's sufficient to use version ranges for that case?

Note that according to https://github.com/mdn/browser-compat-data/pull/24293#issuecomment-2330507981, @queengooborg is working to eliminate ranges too.

2024-11-30 09:33 UTC, queengooborg commented
I think that ranges would be sufficient for any new browsers we add to BCD, as all "true" values can be expressed in ranges already.  There wouldn't be a way to express "null", but our closest option would be to set the feature to "false" and correct it later if we find that the browser does support it.  With the efforts that have gone into the mdn-bcd-collector, the majority of our data would be automatically maintained and updated for new browsers, so I feel we're already set there!

I am working on replacing all ranges with exact version numbers as well, but that's a slow process so it'll be a while before ranges are removed!

2024-12-30 16:27 UTC, danielhjacobs commented
@caugner I don't know if you want to wait for this PR before doing so, but I think https://github.com/mdn/yari/pull/11530 and https://github.com/mdn/yari/issues/11257 can be closed.

2025-01-28 14:19 UTC, caugner reviewed
As long as we don't change this line (which this PR doesn't do), this does not appear to be a breaking change:

https://github.com/mdn/browser-compat-data/blob/2945240c0102d2904c45b34e70b650abd1dd1f4a/scripts/generate-types.ts#L165

/cc @Elchi3 @ddbeck @queengooborg

2025-01-28 15:33 UTC, ddbeck commented
@caugner As a consumer of the types, it's not especially attractive to make this change without changing the types. Removing the nulls without changing the types is still new semantics; the types have a new meaning (I guess that meaning being "`true`s and `null`s are errors"), which still feels like a breaking change to me.

Besides, changing the types makes it much easier to delete the code paths that handle the non-real values.

2025-03-25 12:52 UTC, caugner approved these changes

2025-03-25 13:03 UTC, caugner requested changes

2025-03-25 13:38 UTC, caugner approved these changes

2025-03-25 13:39 UTC, merged