Update Chromium data for history Web Extensions interface
mdn/browser-compat-data pull request #24342
Opened 2024-09-05 07:22 UTC by queengooborg

This PR updates and corrects version values for Chromium (Chrome, Opera, Samsung Internet, WebView Android) for the `history` Web Extensions interface. The data comes from a commit in the browser's source code, mapped to a version number using available tooling or via the commit timestamp.

Commit: https://source.chromium.org/chromium/chromium/src/+/bb0a6a0af3be6d24a5c8f9ebd2e686347a5c882d, https://source.chromium.org/chromium/chromium/src/+/00f1fc22bfcc653b47d62778170af3eee9855720

2024-11-28 11:43 UTC, caugner requested changes

2024-11-28 11:43 UTC, caugner commented on webextensions/api/history.json
> +                "version_added": "6"
:x: https://github.com/chromium/chromium/commit/bb0a6a0af3be6d24a5c8f9ebd2e686347a5c882d in [5.0.368.0](https://github.com/chromium/chromium/releases/tag/5.0.368.0) before 5.0.375.

```suggestion
                "version_added": "5"
```

2024-11-28 11:43 UTC, caugner commented on webextensions/api/history.json
> +                "version_added": "6"
:x: Like `addUrl`:

```suggestion
                "version_added": "5"
```

2024-11-28 11:43 UTC, caugner commented on webextensions/api/history.json
> +                "version_added": "6"
:x: Like `addUrl`:

```suggestion
                "version_added": "5"
```

2024-11-28 11:43 UTC, caugner commented on webextensions/api/history.json
> +                "version_added": "6"
:x: Like `addUrl`:

```suggestion
                "version_added": "5"
```

2024-11-28 11:43 UTC, caugner commented on webextensions/api/history.json
> +                "version_added": "6"
:x: Like `addUrl`:

```suggestion
                "version_added": "5"
```

2024-11-28 11:43 UTC, caugner commented on webextensions/api/history.json
> +                "version_added": "6"
:x: Like `addUrl`:

```suggestion
                "version_added": "5"
```

2024-11-28 11:43 UTC, caugner commented on webextensions/api/history.json
> +                "version_added": "6"
:x: Like `addUrl`:

```suggestion
                "version_added": "5"
```

2024-11-28 11:43 UTC, caugner commented on webextensions/api/history.json
> +                "version_added": "6"
:x: Like `addUrl`:

```suggestion
                "version_added": "5"
```

2024-11-28 11:43 UTC, caugner commented on webextensions/api/history.json
> +                "version_added": "6"
:x: Like `addUrl`:

```suggestion
                "version_added": "5"
```

2024-11-28 11:43 UTC, caugner commented on webextensions/api/history.json
> +                "version_added": "44"
✅ https://github.com/chromium/chromium/commit/00f1fc22bfcc653b47d62778170af3eee9855720 in [44.0.2359.0](https://github.com/chromium/chromium/releases/tag/44.0.2359.0) before 44.0.2403.

2024-11-28 11:43 UTC, caugner commented on webextensions/api/history.json
> +                "version_added": "6"
❌ Like `addUrl`:

```suggestion
                "version_added": "5"
```

2024-11-28 11:43 UTC, caugner commented on webextensions/api/history.json
> +                  "version_added": "6"
:x: Like `addUrl`:

```suggestion
                  "version_added": "5"
```

2024-12-01 09:48 UTC, queengooborg commented on webextensions/api/history.json
> +              "version_added": "6"
```suggestion
              "version_added": "5"
```

2024-12-02 11:52 UTC, caugner approved these changes

2024-12-02 11:53 UTC, merged