Add notes for `Worker` indicating it is not exposed to Shared Worker
mdn/browser-compat-data pull request #24610
Opened 2024-10-02 19:31 UTC by skyclouds2001

#### Summary

the `Worker` interface is not exposed to Shared Worker for chromium-based browsers, and likely will not be fixed recently, so it make sense to add notes to indicating it is not exposed to Shared Worker

Note: I'm not sure if partial_implementation or impl_url key-value should be added

see https://github.com/mdn/content/pull/30880#discussion_r1422009358 and https://issues.chromium.org/issues/40695450

can be test using https://worker-playground.glitch.me/

#### Test results and supporting details

#### Related issues

2024-10-03 12:51 UTC, caugner commented on api/Worker.json
> +            "notes": "Not available in Shared Workers. See <a href='https://crbug.com/40695450'>bug 40695450</a>."
Does the spec indicate that `Worker` should be available in Shared Workers? I can see that there is a separate `SharedWorker` interface.

Can you explain what it is that say Firefox supports here but Chrome doesn't?

2024-10-11 01:01 UTC, skyclouds2001 commented
researches

---

chromium

* add support for dedicated worker

commit https://github.com/chromium/chromium/commit/304237d65a5dbeaca92a2a9a276b4cb903b5ad14
chrome feature entry https://chromestatus.com/feature/6080438103703552
issue https://issues.chromium.org/issues/40340498
code review https://chromium-review.googlesource.com/c/chromium/src/+/953746

local cli test

![image](https://github.com/user-attachments/assets/3689c67e-6e35-4656-90ba-b2b33910858f)

---

firefox

* expose to dedicated worker & shared worker

commit https://github.com/mozilla/gecko-dev/commit/8b59c15d45ed63d4fab0482f3d5b31ef93bda274
issue https://bugzilla.mozilla.org/show_bug.cgi?id=1137398

* expose to worker

commit https://github.com/mozilla/gecko-dev/commit/12b78b96120504ec21e462eb8c99709b075cf965
issue https://bugzilla.mozilla.org/show_bug.cgi?id=1017988

note that service worker only supported via v44, so *expose to worker* is equal to *expose to dedicated worker & shared worker* between v34 to v39

---

safari

commit https://github.com/WebKit/WebKit/commit/48880e342359f100878b1b87373e706db7dfe540
issue https://bugs.webkit.org/show_bug.cgi?id=22723
browser release note https://developer.apple.com/documentation/safari-release-notes/safari-16_4-release-notes

![image](https://github.com/user-attachments/assets/e5d03a8f-cabd-4b2b-a145-50417d1d1abd)

2024-10-14 12:08 UTC, caugner requested changes
Overall LGTM, just one nit.

2024-10-14 12:08 UTC, caugner commented on api/Worker.json
> +            "notes": "Not available in Shared Workers. See <a href='https://crbug.com/40695450'>bug 40695450</a>."
Let's remove this note, as it duplicates the information below:

```suggestion
            "version_added": "2"
```

2024-10-18 14:26 UTC, merged