Add deprecated flag to traverse
mdn/browser-compat-data pull request #24707
Opened 2024-10-14 14:57 UTC by jamesnw

#### Summary

Adds `deprecated` to traverse. 

To limit to only deprecated files-

- `npm run traverse -- --deprecated`
- `npm run traverse -- --dp`
- `npm run traverse -- --deprecated true`

To limit to only non-deprecated files-

- `npm run traverse -- --no-deprecated`
- `npm run traverse -- --no-dp`
- `npm run traverse -- --deprecated false`

Note that if a parent key is deprecated and a child is not, running with `--no-deprecated` will not return the child. I assume non-deprecated children of deprecated parents are a result of bad data, but that could be an incorrect assumption.

#### Related issues

Fixes #24609

2024-10-14 18:12 UTC, queengooborg requested changes
We should also probably add experimental and standard track to the traverse script, would you be down to add those in as well?

2024-10-14 18:12 UTC, queengooborg commented on scripts/traverse.ts
> +          alias: 'dp',
```suggestion
          alias: 'x',
```

Perhaps `-x` would be a bit more fitting?

2024-10-14 20:06 UTC, queengooborg approved these changes
It might be good to merge the parameters if we add any more, but I can't think of any more options to add after this update, so I think that we're alright.

Anyways, this PR is looking good, let's merge it!

2024-10-14 20:06 UTC, merged

2024-10-15 00:47 UTC, jamesnw commented on scripts/traverse.ts
> +  experimental: boolean | undefined,
@caugner I assume the breaking change is changing the parameter order of `iterateFeatures`? I wasn't considering that might be used outside of the test suite. I opened up #24711 to add the new parameter to the end.