Add & fix Safari notes for Permissions-Ploicy
mdn/browser-compat-data pull request #24830
Opened 2024-10-27 02:09 UTC by skyclouds2001

#### Summary

these notes in safari should link to webkit issue, not firefox issue, this might be a bug caused when working on https://github.com/mdn/browser-compat-data/pull/20729

#### Test results and supporting details

#### Related issues

2024-10-27 03:28 UTC, skyclouds2001 commented
close as https://github.com/mdn/browser-compat-data/pull/23470 may fix this issue

2024-10-29 15:45 UTC, caugner requested changes
The bug doesn't seem to be right:

> [Bug 101034](https://bugs.webkit.org/show_bug.cgi?id=101034) - Web Bluetooth API

Or is there a specific comment in the bug we should link to?

2024-10-29 16:36 UTC, skyclouds2001 commented
> The bug doesn't seem to be right:
> 
> > [Bug 101034](https://bugs.webkit.org/show_bug.cgi?id=101034) - Web Bluetooth API
> 
> Or is there a specific comment in the bug we should link to?

Seems I made a mistake of linking to a wrong issue...

2024-10-30 16:55 UTC, caugner approved these changes
Note that https://github.com/mdn/browser-compat-data/pull/23470 will overwrite these changes, but let's fix this anyways.

2024-10-30 16:56 UTC, merged