Add compatibility note addressing teximage2D not supporting video elements on firefox for android and fennec
mdn/browser-compat-data pull request #24849
Opened 2024-10-29 02:13 UTC by FrostKiwi

#### Summary

Reading the doc, I was under the impression, that Firefox on Android and Fennec support video textures, but that turned to be not the case. This was reported in https://bugzilla.mozilla.org/show_bug.cgi?id=1884282 and is unresolved for quite some time. This PR adds a compatibility note with `texImage2D` and `texSubImage2D` to indicate textures from video elements not being supported.

#### Test results and supporting details

#### Related issues

2024-10-30 16:50 UTC, caugner requested changes
LGTM overall, just some notes formatting nits.

PS: Would it be inaccurate to say "Video textures ..." instead of "Textures from video elements ..."?

2024-10-30 16:50 UTC, caugner commented on api/WebGL2RenderingContext.json
> +              "notes": "Textures from video elements not yet supported: https://bugzil.la/1884282"
```suggestion
              "notes": "Textures from video elements are not supported. See (see <a href='https://bugzil.la/1884282'>bug 1884282</a>."
```

2024-10-30 16:50 UTC, caugner commented on api/WebGL2RenderingContext.json
> +              "notes": "Textures from video elements not yet supported: https://bugzil.la/1884282"
```suggestion
              "notes": "Textures from video elements are not supported. See (see <a href='https://bugzil.la/1884282'>bug 1884282</a>."
```

2024-10-30 16:50 UTC, caugner commented on api/WebGLRenderingContext.json
> +              "notes": "Textures from video elements not yet supported: https://bugzil.la/1884282"
```suggestion
              "notes": "Textures from video elements are not supported. See (see <a href='https://bugzil.la/1884282'>bug 1884282</a>."
```

2024-10-30 16:50 UTC, caugner commented on api/WebGLRenderingContext.json
> +              "notes": "Textures from video elements not yet supported: https://bugzil.la/1884282"
```suggestion
              "notes": "Textures from video elements are not supported. See (see <a href='https://bugzil.la/1884282'>bug 1884282</a>."
```

2024-10-31 00:13 UTC, FrostKiwi commented
> PS: Would it be inaccurate to say "Video textures ..." instead of "Textures from video elements ..."?

I thought about exactly that. 🤔
I decided against it, since video textures sound like a special feature with special parameters, but on the API level regarding `texImage2D` and `texSubImage2D` are not. 

Happy to rephrase if desired 👍

2024-11-04 21:52 UTC, caugner approved these changes
LGTM, just some new nits (that I'll fix).

2024-11-04 21:52 UTC, caugner commented on api/WebGL2RenderingContext.json
> +              "notes": "Textures from video elements are not supported. See (see <a href='https://bugzil.la/1884282'>bug 1884282</a>."
```suggestion
              "notes": "Textures from video elements are not supported. See <a href='https://bugzil.la/1884282'>bug 1884282</a>."
```

2024-11-04 21:52 UTC, caugner commented on api/WebGL2RenderingContext.json
> +              "notes": "Textures from video elements are not supported. See (see <a href='https://bugzil.la/1884282'>bug 1884282</a>."
```suggestion
              "notes": "Textures from video elements are not supported. See <a href='https://bugzil.la/1884282'>bug 1884282</a>."
```

2024-11-04 21:52 UTC, caugner commented on api/WebGLRenderingContext.json
> +              "notes": "Textures from video elements are not supported. See (see <a href='https://bugzil.la/1884282'>bug 1884282</a>."
```suggestion
              "notes": "Textures from video elements are not supported. See <a href='https://bugzil.la/1884282'>bug 1884282</a>."
```

2024-11-04 21:52 UTC, caugner commented on api/WebGLRenderingContext.json
> +              "notes": "Textures from video elements are not supported. See (see <a href='https://bugzil.la/1884282'>bug 1884282</a>."
```suggestion
              "notes": "Textures from video elements are not supported. See <a href='https://bugzil.la/1884282'>bug 1884282</a>."
```

2024-11-04 21:55 UTC, merged