Update nodejs data for `Blob` interface
mdn/browser-compat-data pull request #24886
Opened 2024-10-30 19:36 UTC by skyclouds2001

#### Summary

https://nodejs.org/api/globals.html#class-blob
https://nodejs.org/api/buffer.html#class-blob

#### Test results and supporting details

#### Related issues

2024-11-04 21:44 UTC, caugner reviewed
Overall LGTM, just one question.

2024-11-04 21:44 UTC, caugner commented on api/Blob.json
> +              "version_added": "16.7.0"
Good catch!

2024-11-05 06:16 UTC, skyclouds2001 commented on api/Blob.json
> +                "notes": "Before v16.7.0, the <code>endings</code> option use a non-standard implement."
```suggestion
                "notes": "Before v16.7.0, the <code>endings</code> option represents the character encoding to use for string sources, not the line endings in string source parts per the specification."
```

2024-11-05 06:17 UTC, skyclouds2001 commented on api/Blob.json
> +                "notes": "Before v16.7.0, the <code>endings</code> option use a non-standard implement."
https://nodejs.org/docs/v16.17.0/api/buffer.html#new-bufferblobsources-options
https://nodejs.org/docs/v15.7.0/api/buffer.html#buffer_new_buffer_blob_sources_options

2024-11-05 14:33 UTC, caugner submitted a review, later dismissed

2024-11-05 14:33 UTC, caugner commented on api/Blob.json
> +                "notes": "Before v16.7.0, the <code>endings</code> option represents the character encoding to use for string sources, not the line endings in string source parts per the specificatio
I think this isn't quite right. The History in the Node.js docs states:

> v16.7.0: Added the standard `endings` option to replace line-endings, and removed the non-standard `encoding` option.

This states two things:
1. The `endings` option was only added in v16.7.0.
2. Before v16.7.0, a non-standard `encoding` option was supported (but as it's non-standard I wouldn't mention it).

So I would suggest to put `partial_implementation: true` for this range, mentioning that the `endings` option was not supported:

```suggestion
                "notes": "Before v16.7.0, the <code>endings</code> option was not supported."
```

2024-11-07 08:37 UTC, skyclouds2001 commented on browsers/nodejs.json
> +          "engine_version": "12.4"
```suggestion
          "engine_version": "11.8"
```

2024-12-01 10:00 UTC, queengooborg requested changes

2024-12-01 10:00 UTC, queengooborg commented on api/Blob.json
> +                "notes": "Before v16.7.0, the <code>endings</code> option was not supported."
```suggestion
                "notes": "Before v16.7.0, the `endings` option was not supported."
```

2024-12-17 10:08 UTC, queengooborg approved these changes

2024-12-17 10:08 UTC, merged