Add data for the new `options.min` parameter of `ReadableStreamBYOBReader.read()`
mdn/browser-compat-data pull request #24923
Opened 2024-11-03 16:12 UTC by skyclouds2001

#### Summary

see https://github.com/whatwg/streams/pull/1145

the feature has shipped in [node](https://github.com/nodejs/node/issues/50706), and done in [deno](https://github.com/denoland/deno/pull/20849) though seems to be not released, also, [firefox](https://bugzilla.mozilla.org/show_bug.cgi?id=1864406) has implemented it and seems to be shipped in M134

also see https://github.com/mdn/mdn/issues/478

#### Test results and supporting details

#### Related issues

2024-11-04 23:20 UTC, caugner requested changes

2024-11-04 23:20 UTC, caugner commented on api/ReadableStreamBYOBReader.json
> +                "version_added": false,
Based on the resolved bug, it's in Nightly:

```suggestion
                "version_added": "preview",
```

2024-11-04 23:20 UTC, caugner commented on api/ReadableStreamBYOBReader.json
> +            "description": "<code>options.min</code> parameter",
We could try an `impl_url` with a text fragment here:

```suggestion
            "description": "<code>options.min</code> parameter",
            "impl_url: "https://streams.spec.whatwg.org/#:~:text={%20min%20}",
```

2024-11-04 23:20 UTC, caugner commented on browsers/nodejs.json
> +          "release_date": "2024-05-06",
```suggestion
          "release_date": "2024-03-06",
```

2024-11-05 05:58 UTC, skyclouds2001 commented on api/ReadableStreamBYOBReader.json
> +            "impl_url: "https://streams.spec.whatwg.org/#:~:text={%20min%20}",
```suggestion
            "impl_url: "https://streams.spec.whatwg.org/#dom-readablestreambyobreaderreadoptions-min",
```

2024-11-05 05:58 UTC, skyclouds2001 commented on api/ReadableStreamBYOBReader.json
> +                "impl_url": "https://bugzil.la/1864406"
```suggestion
                "version_added": "preview"
```

2024-11-05 14:34 UTC, merged

2024-12-15 05:02 UTC, isker commented
> and done in https://github.com/denoland/deno/pull/20849 though seems to be not released

Why do you say that?  Looks like it's been released for a long time: https://github.com/denoland/deno/releases/tag/v1.39.0

2024-12-15 15:36 UTC, skyclouds2001 commented
> > and done in [denoland/deno#20849](https://github.com/denoland/deno/pull/20849) though seems to be not released
> 
> Why do you say that? Looks like it's been released for a long time: https://github.com/denoland/deno/releases/tag/v1.39.0

Good report!