Unset bind group by passing null to setBindGroup()
mdn/browser-compat-data pull request #24936
Opened 2024-11-04 12:59 UTC by chrisdavidmills

#### Summary

In Chrome 117 onwards, you can pass `null` as the second argument when calling https://developer.mozilla.org/en-US/docs/Web/API/GPUComputePassEncoder/setBindGroup#bindgroup, https://developer.mozilla.org/en-US/docs/Web/API/GPURenderPassEncoder/setBindGroup#bindgroup, and https://developer.mozilla.org/en-US/docs/Web/API/GPURenderBundleEncoder/setBindGroup#bindgroup to unset a previously-set bind group in the specified slot. 

This PR adds data points for this behavior. I copied the compat data from GPURenderBundleEncoder.setVertexBuffer.unset_vertex_buffer, as it was implemented at the same time in Chrome and is very similar behavior, so there is a good chance that other browsers will have implemented it at the same time too. I've not explicitly tested it though.

See https://developer.chrome.com/blog/new-in-webgpu-117#unset_bind_group for evidence of this change.

Note that the above link does not mention [GPUComputePassEncoder/setBindGroup](https://developer.mozilla.org/en-US/docs/Web/API/GPUComputePassEncoder/setBindGroup#bindgroup), but I tested it in Chrome and it works there as well.

#### Test results and supporting details

#### Related issues

Project issue: https://github.com/mdn/content/issues/36375

2024-11-04 13:07 UTC, beaufortfrancois approved these changes

2024-11-05 13:52 UTC, caugner requested changes
Chromium changes LGTM, but Deno/Safari should probably be reset:

Related spec change: https://github.com/gpuweb/gpuweb/pull/3938

2024-11-05 13:52 UTC, caugner commented on api/GPUComputePassEncoder.json
> +                "version_added": "preview"
```suggestion
                "version_added": false
```

2024-11-15 20:53 UTC, caugner approved these changes

2024-11-15 20:55 UTC, merged