Add spec_url for `SVGAnimationElement`
mdn/browser-compat-data pull request #25393
Opened 2024-12-12 14:21 UTC by skyclouds2001

#### Summary

#### Test results and supporting details

#### Related issues

Fixes https://github.com/mdn/browser-compat-data/issues/25384

2024-12-12 16:05 UTC, yashrajbharti requested changes
The "mdn_url" of the respective pages can be added to.
The MDN feature pages are in pr [here](https://github.com/mdn/content/pull/37180) and [here](https://github.com/mdn/content/pull/37182) which is why I raised the issue.

2024-12-12 16:05 UTC, yashrajbharti commented on api/SVGAnimationElement.json
> +          "spec_url": "https://svgwg.org/specs/animations/#__svg__SVGAnimationElement__getCurrentTime",
```suggestion
           "mdn_url": "https://developer.mozilla.org/en-US/docs/Web/API/SVGAnimationElement/getCurrentTime",
          "spec_url": "https://svgwg.org/specs/animations/#__svg__SVGAnimationElement__getCurrentTime",
```

2024-12-12 16:05 UTC, yashrajbharti commented on api/SVGAnimationElement.json
> +          "spec_url": "https://svgwg.org/specs/animations/#__svg__SVGAnimationElement__getSimpleDuration",
```suggestion
          "mdn_url": "https://developer.mozilla.org/en-US/docs/Web/API/SVGAnimationElement/getSimpleDuration",
          "spec_url": "https://svgwg.org/specs/animations/#__svg__SVGAnimationElement__getSimpleDuration",
```

2024-12-12 16:05 UTC, yashrajbharti commented on api/SVGAnimationElement.json
> +          "spec_url": "https://svgwg.org/specs/animations/#__svg__SVGAnimationElement__getStartTime",
```suggestion
          "mdn_url": "https://developer.mozilla.org/en-US/docs/Web/API/SVGAnimationElement/getStartTime",
          "spec_url": "https://svgwg.org/specs/animations/#__svg__SVGAnimationElement__getStartTime",
```

2024-12-12 16:05 UTC, yashrajbharti commented on api/SVGAnimationElement.json
> +          "spec_url": "https://svgwg.org/specs/animations/#__svg__SVGAnimationElement__endElement",
```suggestion
          "mdn_url": "https://developer.mozilla.org/en-US/docs/Web/API/SVGAnimationElement/endElement",
          "spec_url": "https://svgwg.org/specs/animations/#__svg__SVGAnimationElement__endElement",
```

2024-12-12 16:05 UTC, yashrajbharti commented on api/SVGAnimationElement.json
> +          "spec_url": "https://svgwg.org/specs/animations/#__svg__SVGAnimationElement__beginElement",
```suggestion
          "mdn_url": "https://developer.mozilla.org/en-US/docs/Web/API/SVGAnimationElement/beginElement",
          "spec_url": "https://svgwg.org/specs/animations/#__svg__SVGAnimationElement__beginElement",
```

2024-12-13 07:26 UTC, caugner commented
> The "mdn_url" of the respective pages can be added to. The MDN feature pages are in pr [here](https://github.com/mdn/content/pull/37180) and [here](https://github.com/mdn/content/pull/37182) which is why I raised the issue.

The mdn_urls will get added automatically once the pages referencing these BCD keys landed in content, so let's avoid adding those links before the pages exist.

2024-12-13 07:27 UTC, caugner approved these changes

2024-12-13 07:28 UTC, merged

2024-12-13 13:48 UTC, yashrajbharti commented
Thanks!