Update nodejs data for `import.worker_support`
mdn/browser-compat-data pull request #25463
Opened 2024-12-19 07:16 UTC by skyclouds2001

#### Summary

the data should be the same as `import`

#### Test results and supporting details

#### Related issues

2025-01-02 10:01 UTC, caugner requested changes

2025-01-02 10:01 UTC, caugner commented on javascript/operators/import.json
> +              ],
Let's avoid duplicating these notes, as parent notes generally also apply to its children.

```suggestion
              "nodejs": [
                {
                  "version_added": "13.2.0"
                },
                {
                  "version_added": "12.17.0",
                  "version_removed": "13.0.0"
                }
              ],
```

2025-01-02 15:08 UTC, Kristianko666 commented
> #### Summary
> the data should be the same as `import`
> 
> #### Test results and supporting details
> #### Related issues
https://www.google.com/search?q=%5B!%5Bauto-merge%5D(https%3A%2F%2Fgithub.com%2Fmdn%2Fbrowser-compat-data%2Factions%2Fworkflows%2Fauto-merge.yml%2Fbadge.svg)%5D(https%3A%2F%2Fgithub.com%2Fmdn%2Fbrowser-compat-data%2Factions%2Fworkflows%2Fauto-merge.yml)&oq=%5B!%5Bauto-merge%5D(https%3A%2F%2Fgithub.com%2Fmdn%2Fbrowser-compat-data%2Factions%2Fworkflows%2Fauto-merge.yml%2Fbadge.svg)%5D(https%3A%2F%2Fgithub.com%2Fmdn%2Fbrowser-compat-data%2Factions%2Fworkflows%2Fauto-merge.yml)&gs_lcrp=EgZjaHJvbWUyBggAEEUYOdIBCDIyMzFqMGo5qAIAsAIA&client=ms-android-samsung-ss&sourceid=chrome-mobile&ie=UTF-8&chrome_dse_attribution=1

2025-01-02 15:09 UTC, Kristianko666 commented
[2024-12-16_12-53_Export-search-entities.csv](https://github.com/user-attachments/files/18291831/2024-12-16_12-53_Export-search-entities.csv)

2025-01-03 13:51 UTC, caugner approved these changes

2025-01-03 13:52 UTC, merged