Add `Request()` constructor `init.duplex` parameter
mdn/browser-compat-data pull request #25488
Opened 2024-12-22 11:48 UTC by skyclouds2001

#### Summary

data taken from `Request.duplex`

#### Test results and supporting details

#### Related issues

Relates to https://github.com/mdn/content/issues/31735
Depends on https://github.com/mdn/browser-compat-data/pull/25486 and https://github.com/mdn/browser-compat-data/pull/25487

2025-01-02 18:35 UTC, caugner commented on api/Request.json
> +              },
How did you determine this version?

2025-01-02 18:35 UTC, caugner commented on api/Request.json
> +              ],
Can you share links to the PRs/commits?

2025-01-02 18:35 UTC, caugner commented on api/Request.json
> -            "mdn_url": "https://developer.mozilla.org/docs/Web/API/Request/keepalive",
✅ LGTM.

2025-01-04 08:08 UTC, skyclouds2001 commented on api/Request.json
> +              ],
similar to https://github.com/mdn/browser-compat-data/pull/25487, it is added in https://github.com/nodejs/node/commit/216b5a13085f99b9077bb8dd78ce7e64ec09cc02#diff-1548e1d5e2941cd3f8042e4b5bf7f5f985e48bd7aee50f938739f9e067366e8cR476-R480, and https://github.com/nodejs/node/pull/45236, so the version should be 19.1.0, 18.13.0, 16.19.0

2025-01-04 08:23 UTC, skyclouds2001 commented on api/Request.json
> +              },
added in https://github.com/chromium/chromium/commit/b4fc85b816b6e74d4c9ef60572bd66026c44d26a#diff-b20237250664d822b6a53088807fe79e7548b225c6001e555c1ef6389309aba6 via idl file, and confirmed version in https://chromiumdash.appspot.com/commit/b4fc85b816b6e74d4c9ef60572bd66026c44d26a and https://issues.chromium.org/issues/40229369, so the version should be 105

2025-01-13 12:14 UTC, caugner requested changes

2025-01-13 12:14 UTC, caugner commented on api/Request.json
> +                }
I guess we can ignore <18.0.0, because the fetch API was behind a flag?

```suggestion
                }
```

2025-01-13 12:14 UTC, caugner commented on browsers/nodejs.json
> +        },
```suggestion
```

2025-01-13 12:14 UTC, caugner commented on api/Request.json
> +        "init_duplex_parameter": {
I think we want to add the same subfeature on `api.fetch`?!

2025-01-24 16:52 UTC, caugner commented on api/Request.json
> +                }
This will also resolve this problem raised by the linter:

```
Consistency - 1 problem (1 error, 0 warnings):
 ✖ api.Request.Request - Error → Basic support in nodejs was declared implemented in a later version (18.0.0) than the following sub-feature(s):
        → api.Request.Request.init_duplex_parameter: 16.19.0
```

2025-01-25 16:17 UTC, skyclouds2001 commented on api/Request.json
> +                }
yes, mu test in v16.20.0 confirmed that it is not supported in v16

2025-01-25 16:45 UTC, skyclouds2001 commented on api/Request.json
> +        "init_duplex_parameter": {
yes, they has the same versions

2025-01-28 13:41 UTC, caugner approved these changes
Thank you, LGTM!

2025-01-28 13:41 UTC, merged