Add link fix script
mdn/browser-compat-data pull request #5484
Opened 2020-01-13 10:17 UTC by vinyldarkscratch

This PR adds a brand new fix script that I'm proud to introduce!  Following up to my refactoring work for the links tests (#5187), I've put together a fix script to automatically fix issues with links that we lint for.  This takes the errors that come from the linter and performs replacement of the links based upon those errors.

2020-09-17 22:29 UTC, alshamiri5 approved these changes

2022-04-22 06:28 UTC, foolip commented
@queengooborg can you rebase and give an example for how to test that this is working?

2022-04-22 13:15 UTC, queengooborg commented
Of course -- one easy test to perform is to change any MDN URL or bug link to `http://` (rather than `https://`) as it is now.

2022-05-13 16:54 UTC, caugner requested changes
LGTM and works (`npm run fix` after changing `http://` to `https://` in `mdn_url`s or adding `/en-US/` to a url).

Just few nits.

2022-05-13 16:54 UTC, caugner commented on scripts/fix-links.js
> + * @param {Promise<void>} filename
Based on the following, filename is a `string`:

https://github.com/mdn/browser-compat-data/blob/1d4f83058631578fd298b759cfc7ae1cb90c9655/test/linter/test-links.js#L11-L17

```suggestion
 * @param {string} filename
```

2022-05-13 16:54 UTC, caugner commented on scripts/fix-links.js
> +  let original = fs.readFileSync(filename, 'utf-8').trim();
Guess ESLint would complain about this:

```suggestion
  const errors = processData(filename);
  const original = fs.readFileSync(filename, 'utf-8').trim();
```

2022-05-13 16:54 UTC, caugner commented on scripts/fix-links.js
> +  for (let error of errors) {
ditto
```suggestion
  for (const error of errors) {
```

2022-05-13 20:32 UTC, merged