Add chat link
mdn/browser-compat-data pull request #5556
Opened 2020-01-24 10:40 UTC by Elchi3

I'd like to invite the BCD community to get closer to each other and closer to MDN folks. 
Mozilla has replaced its old IRC with matrix chat. We've created an MDN channel there. (I've used the "share room" functionality to get a link to the room).

2020-02-19 23:23 UTC, jmswisher requested changes
The "Share room" link takes you to a landing page that makes you select a Matrix client; even if you know which link to click, it then takes you to riot.im, not c.m.o. You then have to know to change your home server to mozilla.modular.im (not chat.mozilla.org). "Share room" does not actually do what it says. 

https://chat.mozilla.org/#/room/#mdn:mozilla.org is a more readable and usable version of the chat link, which takes you straight to the sign-in page for chat.mozilla.org. It still doesn't take you straight to the room, but at least it gets you to the right server.

2020-02-20 10:11 UTC, Elchi3 commented
Thank you @jmswisher! :+1:  I've updated this.

2020-02-20 14:02 UTC, ddbeck requested changes
The new link works great—I finally managed to join the chat. Some minor edits, but otherwise, this works for me now.

2020-02-20 14:02 UTC, ddbeck commented on docs/contributing.md
> +If you need help with this repository or have any questions, contact the MDN team on [chat.mozilla.org#mdn](https://chat.mozilla.org/#/room/#mdn:mozilla.org) or write us on [discourse](https://discou
```suggestion
If you need help with this repository or have any questions, contact the MDN team on [chat.mozilla.org#mdn](https://chat.mozilla.org/#/room/#mdn:mozilla.org) or write to us on [Discourse](https://discourse.mozilla-community.org/c/mdn).
```

2020-02-20 14:41 UTC, ddbeck approved these changes

2020-02-20 15:13 UTC, Elchi3 commented
Thank you @ddbeck :+1:

2020-02-20 15:13 UTC, merged

2022-02-06 07:11 UTC, redova87 reviewed
>

2026-07-14 19:34 UTC, Kycilak commented
Is the mozilla homeserver dead or are there just issues with certificates? It says to contact the admin but does not provide a contact so I am trying here.
Thanks