Move functions in linters to top-level
mdn/browser-compat-data pull request #5916
Opened 2020-03-31 12:14 UTC by vinyldarkscratch

This PR moves all functions out of specific scopes and into top-level for legibility purposes.

2020-09-17 22:22 UTC, alshamiri5 approved these changes

2022-05-13 17:29 UTC, caugner requested changes
LGTM, just missing JSDoc for new `logger` parameter

2022-05-13 17:29 UTC, caugner commented on test/linter/test-versions.js
> +function findSupport(data, logger, relPath) {
1. logger param is missing in JSDoc
2. Adding `@returns {void}` would also make sense. 🤓 
3. Not sure why `relPath` is in brackets. 🤷

2022-05-13 17:29 UTC, caugner commented on test/linter/test-real-values.js
>   */
Wouldn't hurt to add a `@returns` annotation at the same time.

```suggestion
 * @returns {boolean}
 */
```

2022-05-13 17:29 UTC, caugner commented on test/linter/test-versions.js
>   */
```suggestion
 * @returns {boolean}
 */
```

2022-05-13 17:29 UTC, caugner commented on test/linter/test-real-values.js
> +function findSupport(data, category, logger, relPath) {
Missing JSDoc entry for the new logger param.

2022-05-13 20:09 UTC, merged