Update API compatibility for Firefox for Android 79
mdn/browser-compat-data pull request #6590
Opened 2020-08-28 20:44 UTC by kewisch

With Firefox for Android 79, we're building on a new browser engine. As
such, many WebExtensions APIs needed to be re-implemented from scratch.
With the release of 79 we haven't yet achieved WebExtension API parity,
therefore this changeset is updating API compatibility. We are working
on restoring the remaining APIs. Note also we have added a few APIs that
were not supported before.

Marking this a draft for now, I'd like to get some feedback from the Fenix/GV team first.

2020-08-28 20:48 UTC, agi commented on browsers/firefox_android.json
> +          "status": "esr",
I think should be `retired` too? We don't have any support for 68 at this point.

2020-08-28 20:54 UTC, agi commented on webextensions/api/browsingData.json
>                },
Can't comment directly, but removeLocalStorage a few line below this has a note that says that the API is defined by returns a rejected promise which is not accurate anymore.

2020-08-28 20:55 UTC, agi commented on webextensions/api/browsingData.json
>                },
Also the note for removePasswords is outdated too, as that bug has been closed.

2020-08-31 19:19 UTC, kewisch commented
@chrisdavidmills @ddbeck On our end this is ready to go. We'd appreciate a quick look to make sure things are correct.

2020-09-01 03:46 UTC, vinyldarkscratch commented
Hey @kewisch, thanks for your PR and welcome to BCD!  I noticed that you're also updating the browser data in this PR, and it appears you have a different release date for Fenix 79 than I had obtained.  May I confirm where you obtained the release date?

2020-09-01 08:36 UTC, kewisch commented
Thanks for flagging. I thought I picked it from the release notes, but while double checking it looks like I might have been on the wrong page. I've reverted the release date change in this PR.

2020-09-02 11:04 UTC, ddbeck requested changes
Thanks for this PR! I'm trusting that you're an authoritative source on the data here, so I have only one style suggestion before we merge this.

2020-09-02 11:04 UTC, ddbeck commented on webextensions/api/browsingData.json
> +                "notes": "See <a href='https://bugzil.la/1363010'>bug 1363010</a>. <a href='https://developer.mozilla.org/docs/Mozilla/Add-ons/WebExtensions/API/browsingData/remove'><code>browser.his
```suggestion
                "notes": "See <a href='https://bugzil.la/1363010'>bug 1363010</a>. <a href='https://developer.mozilla.org/docs/Mozilla/Add-ons/WebExtensions/API/browsingData/remove'><code>browser.history.remove(options, {history:true})</code></a> can be used up to Firefox for Android 79 instead.",
```
```suggestion
                "notes": "See <a href='https://bugzil.la/1363010'>bug 1363010</a>. Before Firefox for Android 79, <a href='https://developer.mozilla.org/docs/Mozilla/Add-ons/WebExtensions/API/browsingData/remove'><code>browser.history.remove(options, {history:true})</code></a> can be used instead.",
```

2020-09-09 11:22 UTC, kewisch commented
Thanks @ddbeck , I've made the requested changes. All good to squash and merge when you are ready.

2020-09-09 15:36 UTC, ddbeck approved these changes
Thank you, @kewisch! 🎉

2020-09-09 15:36 UTC, merged