Update intrinsicsize attribute support in Firefox and Chrome
mdn/browser-compat-data pull request #6767
Opened 2020-09-27 21:48 UTC by LegionMammal978

Neither Firefox nor Chrome currently support the `intrinsicsize` attribute on `<img>` or `<video>` elements.

**Firefox:** The `intrinsicsize` attribute was initally described on April 24, 2018. I did an automated search of all versions of `xpcom/ds/nsGkAtomList.h` and `xpcom/ds/StaticAtoms.py` from that date, and I didn't find `intrinsicsize` in any of them. Since all attribute names are contained in this atom list, `intrinsicsize` can never have been an attribute of any HTML element.

**Chrome:** All functionality was removed in version 78; see https://bugs.chromium.org/p/chromium/issues/detail?id=997286 and the [relevant commit](https://chromium.googlesource.com/chromium/src.git/+/d1a6a7200ef9195b6cd701758eddb7a660790942).

It might be a good idea to mark the feature as deprecated, since WICG has since dropped it.

2020-09-28 16:14 UTC, jpmedley commented
Consider this approval for the Chrome material. I'm not qualified to comment on Firefox.

2020-09-29 11:23 UTC, ddbeck requested changes
Hi @LegionMammal978 and welcome to BCD! This is a really good clean up—thank you for investigating it. You're right that we should update the status information. Before we merge, I suggest changing both features' statuses to be:

```
{
 "experimental": false,
 "standard_track": false,
 "deprecated": true
}
```

Since we're here, there are two other changes that follow from the Chromium data. These suggestions are optional, but would make a great addition to the PR:

* Set Edge to `"version_added": false` — since Edge switched to Chromium _after_ this feature was removed.
* Set Opera and Opera for Android to `"version_added": false`. The existing data is wrong. For extra credit, you could map the data from Chrome to the equivalent versions of  Opera and Opera for Android (using the engine data in `browsers/opera*.json`). Either way though, we ought to show that the feature is not currently shipping in Opera either.

Thank you again!

2020-09-29 22:02 UTC, LegionMammal978 commented
To be sure, I installed Opera 60 on a VM and verified that the attribute only worked when the flag was enabled.

2020-09-30 16:18 UTC, ddbeck approved these changes
Excellent. Thank you, @LegionMammal978! 🎉

2020-09-30 16:18 UTC, merged