Force LF line ending for all text files
mdn/browser-compat-data pull request #6808
Opened 2020-10-03 18:27 UTC by saschanaz

A checklist to help your pull request get merged faster:
- [x] Summarize your changes

This prevents prettier failure in environments where CRLF checkout is the default.

2020-10-09 20:47 UTC, ddbeck requested changes
Thanks for this, @saschanaz. One suggestion (in a line a comment) and a question, to better document this change. The change itself seems fine to me.

The question: what does it look like when Prettier fails as a result of not having this configuration change? I trust that line endings are provoking problems, but I'd like to have some more detail about what we're fixing in the PR, to fully document what we're doing.

2020-10-09 20:47 UTC, ddbeck commented on .gitattributes
> +* text=auto eol=lf
If I understand this change correctly, then if we ever add a binary file to the repository (e.g., `something.png`), then we'll have to update this config to _not_ wreck the line endings for that file. That's probably OK, but I'm mentioning the word "binary" so it'll turn up when I search the issues trying to fixing the problem when it happens. But we should probably comment just to be safe

```suggestion
# note: this may affect line endings for binary files and may need to be amended if we ever add one
* text=auto eol=lf
```

2020-10-09 20:51 UTC, saschanaz commented on .gitattributes
> +* text=auto eol=lf
I think `text=auto` automatically excludes such binaries, so maybe not needed?

2020-10-09 21:12 UTC, ddbeck commented on .gitattributes
> +* text=auto eol=lf
You're right and I was mistaken. [This Stack Overflow question](https://stackoverflow.com/questions/29435156/what-will-text-auto-eol-lf-in-gitattributes-do) indicates that I was thinking of an older Git behavior. Reading https://github.com/prettier/prettier/issues/5528 was also instructive, which suggests that we should be using the config you propose in this PR. Perhaps not coincidentally, this is also what Prettier's own `.gitattributes` file looks like.

2020-10-09 21:13 UTC, ddbeck approved these changes
Thanks to https://github.com/mdn/browser-compat-data/pull/6808#discussion_r502673437, I'm withdrawing my earlier question and suggestion and merging as is. This appears to be a best practice for using Prettier. Thank you, @saschanaz! 🎉

2020-10-09 21:14 UTC, merged

2020-10-11 23:04 UTC, Destop-Trang1801 commented
saschanaz:force-lf