update aspect ratio
mdn/browser-compat-data pull request #6903
Opened 2020-10-13 08:55 UTC by rachelandrew

Removing details of internal mapping and adding support only for property.

As discussed in #6786 this PR removes details of the internal mapping to HTML width and height, and instead adds the support for the property. Partial support behind a flag in Firefox, and support behind a flag in Chrome.

2020-10-13 16:18 UTC, ddbeck commented
The `internal-value` feature ought to be replaced in the same PR as one that fixes #6786 (to ensure it's all fixed at once and reflected in the release notes). I'll open a complementary PR for this soon.

2020-10-14 13:40 UTC, ddbeck commented
@rachelandrew I've opened #6918 to relocate the HTML data. If you restore the `internal-value` data in this PR, then I can track the move for the release notes a little more gracefully. Alternatively, I've requested your review on that PR—if we merge that one first, you can rebase this PR on top of it.

2020-10-15 09:26 UTC, rachelandrew commented
@ddbeck sorry I don't understand what the end result is that you want. If you just want it put back then we can close this PR and start over?

2020-10-15 09:37 UTC, ddbeck requested changes

2020-10-15 09:37 UTC, ddbeck commented on css/properties/aspect-ratio.json
> -        },
Sorry, Rachel. I should've been more clear about what I was asking for. I'd like you to undo the changes from this line down. In other words, leave the `internal-value` feature in the file (which will be removed in my PR), but keep the changes from above this line.

2020-10-16 15:51 UTC, rachelandrew commented
@ddbeck hopefully what I've done is right, also added the note about the implementation of support for flex items in Firefox 83.

2020-10-28 15:02 UTC, ddbeck requested changes
One consistency suggestion here, but otherwise this looks really good. Thank you, @rachelandrew!

2020-10-29 12:39 UTC, ddbeck approved these changes
Looks good. Thank you!

To get the tests to pass (and to fix my earlier mistake of asking you to remove the subfeature removal), I'm going to push a merge from master into this branch, so it can appear in today's release. 🚀

2020-10-29 13:08 UTC, ddbeck commented
Travis is stuck again. Merging without it.

2020-10-29 13:08 UTC, merged