Remove never-supported WebExtensions features
mdn/browser-compat-data pull request #6960
Opened 2020-10-16 01:36 UTC by saschanaz

A checklist to help your pull request get merged faster:
- [x] Summarize your changes
- [ ] Data: link to resources that verify support information (such as browser's docs, changelogs, source control, bug trackers, and tests)
- [ ] Data: if you tested something, describe how you tested with details like browser and version
- [ ] Review the results of the linter and fix problems reported (If you need help, please ask in a comment!)
- [x] Link to related issues or pull requests, if any: #6854, #6768

2020-10-28 17:52 UTC, saschanaz commented on webextensions/match_patterns.json
> -                "notes": "See <a href='https://bugzil.la/1463440'>bug 1463440</a>"
(This bug is closed as wontfix.)

2021-02-17 16:57 UTC, ddbeck requested changes
Hi @saschanaz, thanks for your patience while I got to this. I think this is ready to go, since there are no redirects needed on the content side. But it needs a rebase and I think the consequence of that will be that one of these features survives. Thanks again!

2021-02-17 16:57 UTC, ddbeck commented on webextensions/manifest/manifest_version.json
> -        "v3": {
It looks like this feature will survive, after rebasing.

2021-02-25 14:15 UTC, ddbeck approved these changes
Thank you! 🎉

2021-02-25 14:15 UTC, merged