adding math-style
mdn/browser-compat-data pull request #6981
Opened 2020-10-19 08:26 UTC by rachelandrew

I'm working on the CSS updates for Firefox 83 in https://github.com/mdn/sprints/issues/3800

This PR adds BCD for the `math-style` property (I haven't created the page yet). It is behind a flag in Firefox and Chrome.

- Firefox bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1665975
- Chromium: https://chromium-review.googlesource.com/c/chromium/src/+/2100787

(Recently added to WebKit but not in Safari yet https://bugs.webkit.org/show_bug.cgi?id=216702)

2020-11-12 14:43 UTC, ddbeck requested changes
A couple minor suggestions here, to mirror the data for the mobile browsers. Otherwise, this is good. Thank you, @rachelandrew!

2020-11-12 14:43 UTC, ddbeck commented on css/properties/math-style.json
> +              "version_added": false
I don't see anything in the diff which suggests that this has been switched off for Android. Can you copy the data from chrome to chrome_android? Or show me how wrong I am?

2020-11-12 14:43 UTC, ddbeck commented on css/properties/math-style.json
> +              "version_added": false
Likewise for firefox→firefox_android

2020-11-13 12:29 UTC, ddbeck approved these changes
Looks good. Thank you! 🎉

2020-11-13 12:30 UTC, merged

2020-11-27 08:39 UTC, Siilwyn commented
Shouldn't `status.experimental be `true`?