masonry properties and values
mdn/browser-compat-data pull request #7249
Opened 2020-11-03 10:32 UTC by rachelandrew

I am documenting the `masonry` value for `grid-template-columns` and `grid-template-rows` and the associated new properties in CSS Grid 3: https://github.com/mdn/sprints/issues/3836

Much of this is implemented behind a flag in Firefox 77 and it's starting to get author interest.

Related PR for the L3 spec: https://github.com/mdn/kumascript/pull/1437

This PR adds the value for `grid-template-columns` and `grid-template-rows` and adds data for the following new properties, which I'm going to document:

- `masonry-auto-flow`
- `align-tracks`
- `justify-tracks`

2020-12-07 15:56 UTC, chrisdavidmills approved these changes
The data here looks OK to me, thanks @rachelandrew !

@Elchi3 , can you give this a quick sanity check for me before we merge? Thanks!

2020-12-08 10:40 UTC, Elchi3 requested changes

2020-12-08 10:40 UTC, Elchi3 commented on css/properties/justify-tracks.json
> +      "align-tracks": {
```suggestion
      "justify-tracks": {
```

2020-12-09 20:25 UTC, Elchi3 approved these changes

2020-12-09 20:26 UTC, chrisdavidmills commented
@Elchi3 cheers!

2020-12-09 20:26 UTC, merged