CSS "contain-intrinsic-size" property
mdn/browser-compat-data pull request #7318
Opened 2020-11-08 21:16 UTC by ramiy

A checklist to help your pull request get merged faster:
- [x] Summarize your changes
- [x] Data: link to resources that verify support information (such as browser's docs, changelogs, source control, bug trackers, and tests)
- [ ] Data: if you tested something, describe how you tested with details like browser and version
- [ ] Review the results of the linter and fix problems reported (If you need help, please ask in a comment!)
- [x] Link to related issues or pull requests, if any

New CSS property.

**Required for:**

https://developer.mozilla.org/en-US/docs/Web/CSS/contain-intrinsic-size

**Resources:**

https://web.dev/content-visibility/

2020-11-09 10:50 UTC, rachelandrew commented
@ramiy I believe this went into Chrome 83, see: https://www.chromestatus.com/feature/5737051062272000

2020-11-12 17:15 UTC, ddbeck requested changes
Thanks for this PR, @ramiy. A couple suggestions to cascade the Chrome data to the other Chromium-derived browsers. Otherwise, looking good.

2020-11-12 17:15 UTC, ddbeck commented on css/properties/contain-intrinsic-size.json
> +              "version_added": false
```suggestion
              "version_added": "69"
```

2020-11-12 17:15 UTC, ddbeck commented on css/properties/contain-intrinsic-size.json
> +              "version_added": false
```suggestion
              "version_added": "59"
```

2020-11-12 17:15 UTC, ddbeck commented on css/properties/contain-intrinsic-size.json
> +              "version_added": false
```suggestion
              "version_added": "13.0"
```

2020-11-12 17:15 UTC, ddbeck commented on css/properties/contain-intrinsic-size.json
> +              "version_added": false
```suggestion
              "version_added": "83"
```

2020-11-13 13:29 UTC, ddbeck approved these changes
Looks good. Thank you! 🎉

2020-11-13 13:30 UTC, merged