fit content function
mdn/browser-compat-data pull request #7321
Opened 2020-11-09 10:02 UTC by rachelandrew

I am working on splitting out the `fit-content` keyword for width from the `fit-content()` function for width in https://github.com/mdn/sprints/issues/3723

This PR adds the data for the `fit-content()` function for width, which no-one yet supports, however given it is confusing people I think it worth showing that lack of support. As then on the function page I can show that it is well supported for track sizing in grid layout, and not at all for use as a general length, which would have helped the poster of that issue.

2020-11-12 17:21 UTC, ddbeck requested changes
This is a weird one, though I see the logic in it. Is this something that might exist in the future? It might be nice to link to implementation bugs or something, mostly to prevent me from removing the whole feature mistakenly.

One little style nit in a line comment. Thank you!

2020-11-12 17:21 UTC, ddbeck commented on css/properties/width.json
> +        "fit-content-function": {
I don't think we actually document this anywhere, but we typically use underscores for word spaces and dashes literally.

```suggestion
        "fit-content_function": {
```

2020-11-13 06:52 UTC, rachelandrew commented
@ddbeck It's in the level 3 specification, I can't find anyone with an implementation bug. However given it does seem to cause confusion (and the other intrinsic sizes are implemented) I think it worth adding.

2020-11-15 15:32 UTC, saschanaz commented on css/properties/width.json
> +                "version_added": false
Found a tracking bug:

```suggestion
                "version_added": false,
                "notes": "See <a href='https://bugzil.la/1312588'>bug 1312588</a>."
```

2020-11-19 14:00 UTC, ddbeck approved these changes
Thanks, y'all! 🎉

2020-11-19 14:01 UTC, merged