visibilitychange: Safari bug with window.addEventListener
mdn/browser-compat-data pull request #7335
Opened 2020-11-10 21:57 UTC by jakub-g

# Scope

- document a bug in Safari < 14
- fix a typo saying "Edge" instead of Safari

# Source
https://github.com/w3c/page-visibility/issues/68#issuecomment-724981272

2020-11-12 17:32 UTC, ddbeck requested changes
Interesting find, @jakub-g. Some suggestions to improve the notes (since notes are always a challenge). Thank you!

2020-11-12 17:32 UTC, ddbeck commented on api/Document.json
> +                "In Safari < 14.0, the event didn't bubble, so only <code>document.addEventListener('visibilitychange', ...)</code> would work, and not<code>window.addEventListener('visibilitychange'
suggestion: we may as well put the more recently applicable notes earlier and ~make these consistent with each other~ actually, on second thought, this `onvisibilitychange` is not really relevant here (it's captured by the compat data for the attribute itself), so we'll just drop it.

```suggestion
                "Before Safari 14, the event does not bubble, so <code>document.addEventListener('visibilitychange', ...)</code> works, but <code>window.addEventListener('visibilitychange', ...)</code> does not."
```

2020-11-12 17:32 UTC, ddbeck commented on api/Document.json
> +                "In Safari < 14.0, the event didn't bubble, so only <code>document.addEventListener('visibilitychange', ...)</code> would work, and not<code>window.addEventListener('visibilitychange'
Same here

```suggestion
                "Before Safari 14, the event does not bubble, so <code>document.addEventListener('visibilitychange', ...)</code> works, but <code>window.addEventListener('visibilitychange', ...)</code> does not."
```

2020-11-13 21:58 UTC, jakub-g commented
Thanks for review @ddbeck, I committed your suggestions

2020-11-16 14:32 UTC, ddbeck approved these changes
Looks good. Thank you! 🎉

2020-11-16 14:32 UTC, merged