Update scroll-behavior.json
mdn/browser-compat-data pull request #7364
Opened 2020-11-15 13:34 UTC by break-stuff

After updating my Mac OS and testing this feature in Safari 14.0.1, this feature still does not work. I am setting the `version_added` for Safari and iOS to `false`. This is validated [here](https://caniuse.com/css-scroll-behavior).

A checklist to help your pull request get merged faster:
- [x] Summarize your changes
- [x] Data: link to resources that verify support information (such as browser's docs, changelogs, source control, bug trackers, and tests)
- [x] Data: if you tested something, describe how you tested with details like browser and version
- [x] Review the results of the linter and fix problems reported (If you need help, please ask in a comment!)
- [x] Link to related issues or pull requests, if any

2020-11-15 15:57 UTC, saschanaz commented
[Per this post](https://blog.amp.dev/2020/07/06/contributions-to-web-platform-interoperability-first-half-of-2020/) it's behind a flag:

>In WebKit, we began with scroll-behavior, which provides the ability to do smooth scrolling. Based on our previous patch, it has landed and is guarded by an experimental flag “CSSOM View Smooth Scrolling” which is disabled by default.

But I'm not familiar about how to document this here, both Firefox and Chrome has machine-readable flag names but not sure about Safari.

2020-11-16 07:27 UTC, sideshowbarker commented
> [Per this post](https://blog.amp.dev/2020/07/06/contributions-to-web-platform-interoperability-first-half-of-2020/) it's behind a flag:
> 
> > In WebKit, we began with scroll-behavior, which provides the ability to do smooth scrolling. Based on our previous patch, it has landed and is guarded by an experimental flag “CSSOM View Smooth Scrolling” which is disabled by default.

Yeah — and the only way to enable it is from **Develop** > **Experimental Features** menu in the Safari UI:

<img width="1440" alt="Screen Shot 2020-11-16 at 16 19 27" src="https://user-images.githubusercontent.com/194984/99223436-d65a2680-2827-11eb-823c-ab849ec615bd.png">


> But I'm not familiar about how to document this here, both Firefox and Chrome has machine-readable flag names but not sure about Safari.
> 
> Edit: This is the commit https://webkit-search.igalia.com/webkit/commit/f51558c0534a07c1a160e540848e7847db9279c4

https://trac.webkit.org/browser/webkit/trunk/Source/WTF/Scripts/Preferences/WebPreferencesExperimental.yaml#L130 shows the relevant feature’s internal machine-readable flag — which is `CSSOMViewSmoothScrollingEnabled`.

But as far as I know, there’s no way for users to actually set it using that `CSSOMViewSmoothScrollingEnabled` name — instead, the only way that users can toggle it is from the **Develop** > **Experimental Features** menu in the Safari UI.

2020-11-16 07:38 UTC, sideshowbarker requested changes
We should keep `"14"` as the version number, but add a `flags` array, with `CSSOM View Smooth Scrolling` as the relevant flag name (and which, like all Safari experimental flags, is a boolean — so we don’t need to also specify a `value_to_set` for it).

2020-11-16 07:38 UTC, sideshowbarker commented on css/properties/scroll-behavior.json
> +              "version_added": false
```suggestion
              "version_added": "14"
              "flags": [
                {
                  "type": "preference",
                  "name": "CSSOM View Smooth Scrolling"
                }
              ],
```

2020-11-16 07:38 UTC, sideshowbarker commented on css/properties/scroll-behavior.json
> +              "version_added": false
```suggestion
              "version_added": "14"
              "flags": [
                {
                  "type": "preference",
                  "name": "CSSOM View Smooth Scrolling"
                }
              ],
```

2020-11-16 12:48 UTC, sideshowbarker approved these changes

2020-11-16 12:49 UTC, merged

2020-11-16 12:50 UTC, sideshowbarker commented
Thanks much, and welcome to the browser-compat-data project 🎉

2020-11-16 18:40 UTC, break-stuff commented
I'm glad I could contribute a little. 😄

2020-11-18 22:46 UTC, rik commented
https://developer.mozilla.org/en-US/docs/Web/CSS/scroll-behavior still shows a green full support box. Has the data not been synced with the website yet or is there an issue with how those flags are displayed?

2020-11-19 03:21 UTC, sideshowbarker commented
> https://developer.mozilla.org/en-US/docs/Web/CSS/scroll-behavior still shows a green full support box. Has the data not been synced with the website yet or is there an issue with how those flags are displayed?

Just not been synced yet. I think typically it gets synced once a week, at the end of the week.

So at the beginning of next week, it should be showing the correct data.

2020-11-19 11:58 UTC, ddbeck commented
And for even more detail on the publishing process: https://github.com/mdn/browser-compat-data/blob/master/docs/contributing.md#updating-compatibility-tables-on-mdn. I'll put this on my to do list to refresh after today's release though. 😄