Update exportparts HTML attribute
mdn/browser-compat-data pull request #7382
Opened 2020-11-17 12:41 UTC by web-padawan

Mark `exportparts` HTML attribute as supported since Firefox 72. 

Related issues for part forwarding are resolved & fixed: 

https://bugzilla.mozilla.org/show_bug.cgi?id=1559076
https://bugzilla.mozilla.org/show_bug.cgi?id=1594275

2020-11-19 17:10 UTC, ddbeck requested changes
Hi @web-padawan and welcome to BCD! Thank you for this PR. It looks good to me, but I have one suggestion, since I think this made its way to Android as well. Thank you!

2020-12-10 15:51 UTC, ddbeck commented
Hi @web-padawan, do you plan to come back to this PR?

2020-12-10 16:51 UTC, web-padawan commented
@ddbeck Thank you, I missed your previous comment. Updated the PR based on your suggestion.

2020-12-12 18:08 UTC, ddbeck approved these changes
Thank you, @web-padawan!

2020-12-12 18:08 UTC, merged