Register protocol handler
mdn/browser-compat-data pull request #7432
Opened 2020-11-20 15:57 UTC by Rumyra

A checklist to help your pull request get merged faster:
- [ ] Summarize your changes

Adding notes to browsers that have not changed the implementation as per spec, to remove the title arg

- [ ] Data: link to resources that verify support information (such as browser's docs, changelogs, source control, bug trackers, and tests)

Firefox has as per https://bugzilla.mozilla.org/show_bug.cgi?id=1631464 spec is here https://html.spec.whatwg.org/multipage/system-state.html#custom-handlers

- [ ] Data: if you tested something, describe how you tested with details like browser and version

Tested in FF 84, Chrome 86 and Opera 72 on OSX. Third param is needed for Chrome and Opera, made a judgement call it's the same for Edge as well

- [ ] Review the results of the linter and fix problems reported (If you need help, please ask in a comment!)

All good

- [ ] Link to related issues or pull requests, if any

https://github.com/mdn/sprints/issues/3899

2020-12-07 16:52 UTC, chrisdavidmills commented
Can I get a request of this one please @ddbeck ? This is related to the Fx 84 launch (Dec 15). Thanks!

2020-12-08 16:31 UTC, ddbeck requested changes
An editing suggestion in line comments. Thank you!

2020-12-08 16:31 UTC, ddbeck commented on api/Navigator.json
> +                "The third <code>title</code> argument has not been removed and so will still need to be specified when using this method"
suggestion: revise the note to make it a bit more direct about what Web developers need to do with this information

```suggestion
                "The obsolete <code>title</code> argument is required."
```

2020-12-08 16:31 UTC, ddbeck commented on api/Navigator.json
> +                "The third <code>title</code> argument has not been removed and so will still need to be specified when using this method"
```suggestion
                "The obsolete <code>title</code> argument is required."
```

2020-12-08 16:31 UTC, ddbeck commented on api/Navigator.json
> +              "notes": "The third <code>title</code> argument has not been removed and so will still need to be specified when using this method"
```suggestion
              "notes": "The obsolete <code>title</code> argument is required."
```

2020-12-15 17:02 UTC, ddbeck approved these changes
Looks good. Thank you! 🎉

2020-12-15 17:02 UTC, merged