Add `npm run diff`
mdn/browser-compat-data pull request #7486
Opened 2020-11-24 15:36 UTC by saschanaz

A checklist to help your pull request get merged faster:
- [x] Summarize your changes
- [x] Link to related issues or pull requests, if any: #6863 

This intends to succeed what @foolip did in #6862 using git commands. Example:

```
> npm run diff origin/HEAD~4 HEAD

> @mdn/browser-compat-data@2.0.7 diff
> node scripts/diff.js "origin/HEAD~4" "HEAD"

api.HTMLFrameSetElement:
 → status.deprecated is edited (false → true)
api.HTMLFrameSetElement.event_handlers:
 → status.deprecated is edited (false → true)
api.HTMLFrameSetElement.onlanguage:
 → status.deprecated is edited (false → true)
api.HTMLFrameSetElement.onstorage:
 → status.deprecated is edited (false → true)
api.NavigatorConcurrentHardware:
 → support.safari.version_added is edited (null → false)
 → support.safari_ios.version_added is edited (null → false)
api.NavigatorConcurrentHardware.hardwareConcurrency:
 → support.safari.version_added is edited (null → false)
 → support.safari_ios.version_added is edited (null → false)
api.NavigatorConcurrentHardware.worker_support:
 → support.safari.version_added is edited (null → false)
 → support.safari_ios.version_added is edited (null → false)
css.selectors.target-within.json:
 → Newly added
css.selectors.user-invalid.json:
 → Newly added
```

`npm run diff` is a shorthand of `npm run diff origin/HEAD *`, which compares current changes against `origin/HEAD`. The longhand is primarily for debugging and test.

2022-04-20 20:08 UTC, queengooborg commented
Hey @saschanaz, this is LGTM for the most part and I'd love to add it in!  Would you mind rebasing this real quick?

2022-04-20 20:20 UTC, saschanaz commented
Done, but I only have npm 7. Feel free to regenerate package-lock.json.

2022-04-23 23:06 UTC, queengooborg commented
We upgraded to use NodeJS v16, which uses NPM v8 and package-lock v2.  Looks like this one needs another quick rebase!

2022-04-26 05:42 UTC, queengooborg approved these changes
This script is LGTM and I'm excited to integrate it!  I'd like @foolip's review as well though, since this builds upon his work!

2022-05-13 06:51 UTC, queengooborg requested changes
Ah, happened to notice a small thing -- could we use `~` vs. `^` for the version number to maintain consistency between the dependencies?

2022-05-13 06:51 UTC, queengooborg commented on package.json
> +    "deep-diff": "^1.0.2",
```suggestion
    "deep-diff": "~1.0.2",
```

2022-05-13 07:22 UTC, queengooborg commented
Odd, the CI should've failed because `package-lock.json` wasn't updated...  Could you update `package-lock.json` real quickly as well?

2022-05-13 07:23 UTC, saschanaz commented
Could you do that for me, I'm on bed 🤔

2022-05-13 07:26 UTC, queengooborg approved these changes
Done, thank you!  This is LGTM, and essential for some plans Open Web Docs has, so I'll merge this now!

2022-05-13 07:26 UTC, merged

2022-05-13 07:32 UTC, saschanaz commented
What plans, BTW? 👀