update @viewport
mdn/browser-compat-data pull request #7514
Opened 2020-11-27 06:19 UTC by rachelandrew

Updating BCD for deprecated `@viewport` as described in https://github.com/mdn/sprints/issues/3404#issuecomment-712038273

2020-11-27 13:37 UTC, Elchi3 commented
I think reducing this to just the `@viewport` main feature is fine even if the sub features don't yet meet the removal requirements. (not yet 2 years gone per https://github.com/mdn/browser-compat-data/blob/master/docs/data-guidelines.md#removal-of-irrelevant-features)

The only blocking thing would be to do something with the MDN sub pages like
https://developer.mozilla.org/en-US/docs/Web/CSS/@viewport/max-width

Should we redirect these to https://developer.mozilla.org/en-US/docs/Web/CSS/@viewport?

2020-11-27 13:43 UTC, rachelandrew commented
> Should we redirect these to https://developer.mozilla.org/en-US/docs/Web/CSS/@viewport?

that would make sense to me, I don't think I can redirect or I would do it. I can move pages but that's all.

2020-11-27 14:06 UTC, Elchi3 commented
I've put the redirects in place for all sub pages of `@viewport` (there is a button in ckeditor, maybe it requires permissions?)

See https://wiki.developer.mozilla.org/en-US/docs/Web/CSS/@viewport/zoom$compare?locale=en-US&to=1655328&from=1645709 for how the change looks like.

2020-11-27 14:23 UTC, Elchi3 requested changes
It would be nice to also set the removal versions in Edge and Operas to signal that this is really gone, but we can also do that in a follow-up. 

A question about standards track but otherwise LGTM.

2020-11-27 14:23 UTC, Elchi3 commented on css/at-rules/viewport.json
>              "standard_track": true,
I believe this should be `false` now as it is no longer in a spec?

```suggestion
            "standard_track": false,
```

2020-11-30 10:31 UTC, Elchi3 approved these changes
Thanks Rachel! :+1:

2020-11-30 10:32 UTC, merged