Update angle.json
mdn/browser-compat-data pull request #7550
Opened 2020-12-01 07:56 UTC by rudimadima

A checklist to help your pull request get merged faster:
- [ ] Summarize your changes
- [ ] Data: link to resources that verify support information (such as browser's docs, changelogs, source control, bug trackers, and tests)
- [ ] Data: if you tested something, describe how you tested with details like browser and version
- [ ] Review the results of the linter and fix problems reported (If you need help, please ask in a comment!)
- [ ] Link to related issues or pull requests, if any

2020-12-01 18:18 UTC, ddbeck commented
Hi @rudimadima, I see this is your first PR here—welcome to BCD!

Can you provide any more background for these changes? Did you test these yourself or have documentation you could share? We want to make sure that the data that gets into BCD is substantiated.

Thank you!

2020-12-01 19:05 UTC, rudimadima commented
Hello.
I tested CSS-angles in old Opera Presto 12. It works correctly.

2020-12-02 12:14 UTC, vinyldarkscratch commented
Hey @rudimadima, thanks for the response!  Could you elaborate on the details, such as:

- How did you test for support?
- Did you test in older versions as well?

2020-12-12 10:06 UTC, rudimadima commented
Hello.
I tested it only in Opera **12.17**

2020-12-12 10:10 UTC, vinyldarkscratch commented
Okay, if you had only tested it in 12.17, let's set a ranged version, "≤12.1", for both Opera and Opera Android.  Additionally, __how__ did you test for support?

2020-12-12 19:31 UTC, rudimadima commented
By using rotate function
like:
`transform: rotate(-20deg);
transform: rotate(110grad);
transform: rotate(1.2rad);
transform: rotate(0.14turn);
`

2020-12-17 11:22 UTC, ddbeck requested changes
Thanks for the update, @rudimadima. A small adjustment to the version data is needed; a comment in line demonstrates. After these changes are made, we can merge this. Thank you again!

2020-12-17 11:22 UTC, ddbeck commented on css/types/angle.json
> +              "version_added": "12"
This ought to be changed to `"≤12.1"` and applied to all the versions in this diff:

```suggestion
              "version_added": "≤12.1"
```

2021-01-14 12:07 UTC, ddbeck commented
Hi @rudimadima, do you plan to return to this PR?

2021-01-28 15:13 UTC, ddbeck commented
Since this PR has been inactive for a long time, I'm going to close it. If you'd like to eventually come back to this, feel free to open a new PR. Thank you!

2021-01-28 15:13 UTC, closed without merging