Document a public API and SemVer policy
mdn/browser-compat-data pull request #7615
Opened 2020-12-08 16:25 UTC by ddbeck

This recasts the list of data folders as the public API for `@mdn/browser-compat-data` and explicitly names it as such for the purposes of a semantic versioning policy. This fixes #7563.

The diff here is a bit ugly. You may want to use the split or rich diffs to review this one. You can also view the full README [rendered on my fork](https://github.com/ddbeck/browser-compat-data/tree/semver-policy#readme).

2020-12-08 17:35 UTC, Elchi3 requested changes
Thanks Daniel, this captures nicely what we talked about!

I think we ought to explicitly protect the webextensions branches, given there is Mozilla WebExtension tooling that consumes BCD specifically for that.

Looks good to me otherwise.

2020-12-09 01:27 UTC, sideshowbarker commented on README.md
> +You should expect lower-level namespaces, feature data, and browser data to be added, removed, or modified at any time. That said, we strive to communicate changes and preserve backward compatibility
```suggestion
You should expect lower-level namespaces, feature data, and browser data to be added, removed, or modified at any time. That said, we strive to communicate changes and preserve backward compatibility; if you rely on a currently undocumented portion of the package and want SemVer to apply to it, please [open an issue](https://github.com/mdn/browser-compat-data/issues).
```

2020-12-09 01:27 UTC, sideshowbarker commented on README.md
> +Data for [WebDriver](https://developer.mozilla.org/en-US/docs/Web/WebDriver) interfaces features.
```suggestion
Data for [WebDriver](https://developer.mozilla.org/en-US/docs/Web/WebDriver) features.
```

2020-12-09 17:11 UTC, ddbeck commented
Thanks for the eagle-eyed copy edits, @sideshowbarker!

@Elchi3 I've expanded the list for WebExtensions. Good catch!

2020-12-09 17:20 UTC, Elchi3 approved these changes
Well done! :100:

2020-12-09 17:25 UTC, sideshowbarker approved these changes

2020-12-10 11:14 UTC, ddbeck commented
@jpmedley You asked to have a look at this during the editorial meeting. Since I plan to follow this policy for today's release (which will be a semver major release), I plan to merge this before the release today (probably around 8-10am PST). If you don't get a chance to look at this before I merge, I'd still like your feedback. Thank you!

2020-12-10 16:50 UTC, merged

2020-12-10 18:54 UTC, jpmedley commented
It looks fine to me. I should have been clear that I wasn't interested in giving feedback. I was interested in possible consequences to a tool that I built that consumes this data.