Update anchor and area support of target=_blank imply rel=noopener
mdn/browser-compat-data pull request #7642
Opened 2020-12-11 11:31 UTC by mems

- [Chrome 88 supports it](https://bugs.chromium.org/p/chromium/issues/detail?id=898942)
- [Safari 12.1 support it](https://developer.apple.com/documentation/safari-release-notes/safari-12_1-release-notes) (see also [Revision 237144 – WebKit](https://trac.webkit.org/changeset/237144/webkit/))

Fix mdn#7324

Change depreciated flag to false, [it's now a recommendation](https://github.com/whatwg/html/pull/4330).

2020-12-14 11:04 UTC, ddbeck requested changes
Hi @mems and thank you for this PR. I see this is your first to BCD—welcome to the project!

This change looks good, though it looks like this will make it to Edge 88 as well. Would you mind if we included Edge too? Line comments with suggestions.

2020-12-14 11:04 UTC, ddbeck commented on html/elements/a.json
>                  "version_added": false
```suggestion
                "version_added": "88"
```

2020-12-14 11:04 UTC, ddbeck commented on html/elements/area.json
>                  "version_added": false
```suggestion
                "version_added": "88"
```

2020-12-14 12:46 UTC, mems commented
Thanks @ddbeck. I've added the Edge version too as suggested.

But the CI fail with the error:

```
Problems in 1 file:
✖ api/HTMLInputElement.json
  Style – 1 error:
  → Error on line #2699
    Actual:             "mdn_url": "https://developer.mozilla.org/docs/Web/API/HTMLInputElement/width",
    Expected:           "support": {
```

Look like it's related to #7751

2020-12-14 13:02 UTC, vinyldarkscratch commented
Apologies for the failing CI -- I've merged a quick fix to resolve the build failures and re-run the tests for this PR!

2020-12-14 18:21 UTC, mems commented
@vinyldarkscratch Done. Thanks that solve it.

2020-12-17 11:24 UTC, ddbeck approved these changes
Thank you, @mems! 🎉

2020-12-17 11:25 UTC, merged