Update Storage Access API availability on Chrome
mdn/browser-compat-data pull request #7661
Opened 2020-12-11 16:23 UTC by andybons

A checklist to help your pull request get merged faster:
- [x] Summarize your changes
- [x] Data: link to resources that verify support information (such as browser's docs, changelogs, source control, bug trackers, and tests)
- [x] Data: if you tested something, describe how you tested with details like browser and version
- [x] Review the results of the linter and fix problems reported (If you need help, please ask in a comment!)
- [x] Link to related issues or pull requests, if any

This change updates the availability of the Storage Access API

+ [Chrome bug](https://bugs.chromium.org/p/chromium/issues/detail?id=989663)
+ [Chrome Platform Status](https://www.chromestatus.com/feature/5612590694662144)

The [first commit](https://chromium.googlesource.com/chromium/src.git/+/da12cf8726dc8414f0d61624afebff46b83c8f1a) was in [version 78](https://chromium.googlesource.com/chromium/src/+/da12cf8726dc8414f0d61624afebff46b83c8f1a/chrome/VERSION), not 85, and the flag remains off by default.

Fixes #7510

2020-12-16 02:55 UTC, lucalves approved these changes

2020-12-17 12:28 UTC, ddbeck requested changes
Thanks for this PR @andybons. I see that it's your first to the project—welcome to BCD!

The [Edge release notes report](https://docs.microsoft.com/en-us/deployedge/microsoft-edge-relnote-stable-channel#version-85056441-august-27) that this did ship in Edge 85 (but not Chrome), which is unusual, but fine.

There's one more change I'd like to see in this PR before merging, plus a couple of optional ones:

- WebView doesn't support any of Chrome's flags. Please set that value to `false`. We typically try to deal with the Chromes and WebView together.
- (optional) In #6836, the erroneous Chrome data was mirrored to Opera. Desktop Opera should show the same flag as Chrome but with version 65 and Opera for Android should be `false` (because it doesn't expose flags).

Thank you for your help with this!

2020-12-18 22:45 UTC, andybons commented
Sorry for delay, here. Holidays in U.S. are slowing me down 🎄 

Will follow up with those changes!

2020-12-20 03:09 UTC, andybons commented
> WebView doesn't support any of Chrome's flags. Please set that value to false. We typically try to deal with the Chromes and WebView together.

Done

> (optional) In #6836, the erroneous Chrome data was mirrored to Opera. Desktop Opera should show the same flag as Chrome but with version 65 and Opera for Android should be false (because it doesn't expose flags).

Done

2020-12-23 08:26 UTC, ddbeck approved these changes
This is a really nice clean up. Thank you and happy holidays, @andybons!

2020-12-23 08:26 UTC, merged