Remove service_workers_support from api/FileReaderSync
mdn/browser-compat-data pull request #8014
Opened 2020-12-18 05:15 UTC by hamishwillee

There is a [Worker support guideline](https://github.com/mdn/browser-compat-data/blob/master/docs/data-guidelines.md#web-workers-worker_support) so `service_workers_support` is incorrect. This follows on from this discussion:  https://github.com/mdn/browser-compat-data/issues/7849#issuecomment-745445095

@ddbeck The way I have done this  is to just add a note indicating that service workers are not supported (with the version, if known). 

Are there other alternatives? i.e. should/can I do multiple worker supports like this?:
```
 "worker_support": {
        "__compat": {
          "description": "Available in workers",
...

 "worker_support": {
        "__compat": {
          "description": "Available in service workers",
...
````

Or something like this (feels confusing).
```json
 "worker_support": {
        "__compat": {
          "description": "Available in workers",
          "support": {
            "chrome": [
              {
                "version_added": true,
              },
              {
                "version_added": true,
                "version_removed": "59",
                "notes": "Service workers not supported from Chrome 59"
              },
            ],
```

2020-12-18 05:22 UTC, hamishwillee commented
Note, same question for caches. In chrome, for example, support was added for service workers in version 40. In version 43 support was added for other workers. 

So I what is the right way to do this - added in version 40, and a note stating that initially only for service workers. Or two worker_support lines, or one worker support line but with notes about what happened in each version?

2020-12-18 10:33 UTC, ddbeck commented
It's hard to follow the diff for removals and data changes in one commit. Can you put into words the support story you're trying to tell here? The diff and the examples given seem to be telling competing stories. What was supported (and unsupported) and in what versions did support change?

That said, I can rule out one thing: multiple `"worker_support"` features. JSON keys have to be unique, or else we'll just clobber one bit of data with another.

Data like this also seems unlikely:

```
            "chrome": [
              {
                "version_added": true,
              },
              {
                "version_added": true,
                "version_removed": "59",
                "notes": "Service workers not supported from Chrome 59"
              },
            ],
```

The second support statement says support was dropped in version 59. The note is a bit strange, since it reiterates what `"version_removed": "59"` is already saying: from version 59, the feature is unsupported (though the first support statement says that support was reintroduced in some unknown version).

2020-12-30 04:17 UTC, hamishwillee commented
> Can you put into words the support story you're trying to tell here? 

Hi @ddbeck 
All I have done (see diff) is deleted the `service_workers_support` key and captured the version information about service worker support  in a note under `worker_support`.

So to answer your question, this is supposed to say:
- workers, other than service workers are supported
- Info of versions in which there is support for workers
- Info about versions in which there _was_ support for service workers.

This is probably OK for this case but I'm not sure it is the "right way". How would YOU present for chrome  this imaginary case.
- dedicated workers are supported from version 4, 
- shared workers are supported from version 8
- service workers are supported from version 2 to 6. 
- chrome workers are not supported

2021-01-11 09:29 UTC, ddbeck requested changes
Thanks for the update, @hamishwillee.

First, to answer your hypothetical:

> How would YOU present for chrome this imaginary case.
> 
> * dedicated workers are supported from version 4,
> * shared workers are supported from version 8
> * service workers are supported from version 2 to 6.
> * chrome workers are not supported

Right now, given our schema, probably with something like this:

```json
{
  "version_added": "2",
  "notes": [
    "From version 8, shared workers are supported.",
    "From version 4, dedicated workers are supported.",
    "From version 2 to 6, service workers are supported; from version 7, service workers are unsupported."
  ]
}
```

Hypothetical aside, the new diff here makes a lot more sense to me. For example, in Chrome supported initially and generally, then dropped from service workers specifically. Suggests in line comments are just some style and consistency nits.

Also, just so I'm doing my due diligence here: I take it you did some sort of testing to figure out the support data here?

2021-01-11 09:29 UTC, ddbeck commented on api/FileReaderSync.json
> +          "description": "Available in workers (except for service workers)",
The linter won't accept any description but "Available in workers" here (though I appreciate what you're getting at).

```suggestion
          "description": "Available in workers",
```

2021-01-11 09:29 UTC, ddbeck commented on api/FileReaderSync.json
> +              "notes": "Not supported in service workers from Chrome 59"
nit: style

```suggestion
              "notes": "From Chrome 59, not supported in service workers."
```

2021-01-11 09:29 UTC, ddbeck commented on api/FileReaderSync.json
> +              "notes": "Not supported in service workers from Chrome 59"
nit: style

```suggestion
              "notes": "From Chrome 59, not supported in service workers."
```

2021-01-11 09:29 UTC, ddbeck commented on api/FileReaderSync.json
> +              "notes": "Not supported in service workers from FF61"
nit: style

```suggestion
              "notes": "From Firefox 61, not supported in service workers."
```

2021-01-11 09:29 UTC, ddbeck commented on api/FileReaderSync.json
> +              "notes": "Not supported in service workers"
nit

```suggestion
              "notes": "Not supported in service workers."
```

2021-01-11 09:29 UTC, ddbeck commented on api/FileReaderSync.json
> +              "notes": "Not supported in service workers from FF61"
nit: style

```suggestion
              "notes": "Form Firefox 61, not supported in service workers."
```

2021-01-11 09:29 UTC, ddbeck commented on api/FileReaderSync.json
> +              "notes": "Not supported in service workers"
Maybe we should omit this note? If I remember correctly, IE doesn't support service workers in any case (e.g., doesn't implement `navigator.serviceWorker`)

```suggestion
              "version_added": true
```

2021-01-11 09:29 UTC, ddbeck commented on api/FileReaderSync.json
> +              "notes": "Not supported in service workers from Opera 46"
nit: style

```suggestion
              "notes": "From Opera 46, not supported in service workers."
```

2021-01-11 09:29 UTC, ddbeck commented on api/FileReaderSync.json
> +              "notes": "Not supported in service workers from Opera 43"
nit: style

```suggestion
              "notes": "From Opera 43, not supported in service workers."
```

2021-01-11 09:29 UTC, ddbeck commented on api/FileReaderSync.json
> +              "notes": "Service workers not supported"
suggestion: for consistency with other notes in this PR

```suggestion
              "notes": "Not supported in service workers."
```

2021-01-11 09:29 UTC, ddbeck commented on api/FileReaderSync.json
> +              "notes": "Service workers not supported"
suggestion: for consistency with other notes in this PR

```suggestion
              "notes": "Not supported in service workers."
```

2021-01-11 09:29 UTC, ddbeck commented on api/FileReaderSync.json
> +              "notes": "Not supported in service workers from version 7.0"
```suggestion
              "notes": "From version 7.0, not supported in service workers."
```

2021-01-11 09:29 UTC, ddbeck commented on api/FileReaderSync.json
> +              "notes": "Not supported in service workers from version 59"
nit: style

```suggestion
              "notes": "From version 59, not supported in service workers."
```

2021-01-18 03:00 UTC, hamishwillee commented
> Hypothetical aside, the new diff here makes a lot more sense to me. For example, in Chrome supported initially and generally, then dropped from service workers specifically. Suggests in line comments are just some style and consistency nits.

Agree - what you have suggested makes sense for the current data.

NOTE, that support for workers implies support for dedicated workers, shared workers and service workers. It does not imply support for the {FF-only) chrome workers - which I propose we completely ignore.

> Also, just so I'm doing my due diligence here: I take it you did some sort of testing to figure out the support data here?

No. There is no new data in this change - it is just a reformatting of the data that was already present.

2021-01-18 13:04 UTC, ddbeck approved these changes
Looks good. Thank you! 🎉

2021-01-18 13:04 UTC, merged