Add missing features for Window API
mdn/browser-compat-data pull request #8184
Opened 2020-12-23 09:47 UTC by vinyldarkscratch

This PR is a part of a project to add missing interfaces and interface features to BCD that are from an active spec (including WICG specs) and is supported in at least one browser.  This particular PR adds missing features, populating the results using data from the [mdn-bcd-collector](https://mdn-bcd-collector.appspot.com) project (v1.1.7), for the `Window` API.

Spec: https://html.spec.whatwg.org/multipage/window-object.html#window, https://html.spec.whatwg.org/multipage/obsolete.html#Window-partial, https://wicg.github.io/cookie-store/, https://drafts.csswg.org/css-nav-1/, https://drafts.csswg.org/css-nav-1/, https://drafts.csswg.org/cssom-view/, https://w3c.github.io/webappsec-trusted-types/dist/spec/

IDL: https://github.com/w3c/webref/blob/master/ed/idl/html.idl

Tests Used: https://mdn-bcd-collector.appspot.com/tests/api/Window

2020-12-23 15:09 UTC, foolip requested changes

2020-12-23 15:09 UTC, foolip commented on api/Window.json
> +      "navigate": {
I don't think we should add this entry, as it's not in any recent browser release.

2020-12-23 20:14 UTC, foolip commented
@vinyldarkscratch can you check if any of these entries also existing somewhere else in BCD, in particular on WindowOrWorkerGlobalScope?

2020-12-24 00:27 UTC, vinyldarkscratch commented
Before submitting this PR, I had double-checked to make sure that the only entries being added were directly implemented on the `Window` interface!

2020-12-26 20:49 UTC, foolip commented
Okay, in that case let me review properly...

2020-12-26 20:50 UTC, foolip approved these changes

2020-12-26 20:50 UTC, merged