Set Chrome versions for api.CanvasPattern.setTransform.dommatrix
mdn/browser-compat-data pull request #8464
Opened 2020-12-30 14:53 UTC by vinyldarkscratch

This PR sets the Chromium versions for the `setTransform` method's `DOMMatrix` parameter for the `CanvasPattern` API based upon commit history.  It appears that the property was added at the same time as the method itself.

Source: https://source.chromium.org/chromium/chromium/src/+/f7028d961fb1cfd5d0f4abaecb582c61e0231c1f

2020-12-30 18:41 UTC, foolip requested changes
In https://source.chromium.org/chromium/chromium/src/+/f7028d961fb1cfd5d0f4abaecb582c61e0231c1f the argument was `SVGMatrix`, and then https://chromium.googlesource.com/chromium/src/+/26ea97726ef213927ed86a06836dd16a8b33275f (Chrome 68) changed it to the dictionary `DOMMatrix2DInit`, which is per spec.

https://github.com/mdn/browser-compat-data/pull/6365 added this entry to reflect https://bugzilla.mozilla.org/show_bug.cgi?id=1565997 which also changed the parameter from `SVGMatrix` to `DOMMatrix2DInit`. So I think to match that we should set Chrome 68 here.

Maybe the description should also be changed however to better reflect "it's now possible to use anything object which has `DOMMatrix2DInit` members, not just `SVGMatrix`", but I'm not sure how to phrase that. @ddbeck @Elchi3 WDYT?

2021-01-07 12:35 UTC, ddbeck commented
> Maybe the description should also be changed however to better reflect "it's now possible to use anything object which has `DOMMatrix2DInit` members, not just `SVGMatrix`", but I'm not sure how to phrase that. @ddbeck @Elchi3 WDYT?

Maybe something like, `Accepts a <code>DOMMatrix2DInit</code>-like object parameter`?

2021-01-11 10:36 UTC, foolip commented on api/CanvasPattern.json
>              "description": "<code>DOMMatrix</code> parameter supported",
```suggestion
            "description": "Accepts a <code>DOMMatrix2DInit</code>-like object parameter",
```

2021-01-11 10:42 UTC, foolip commented
@ddbeck I've added that as a suggestion. Here are some other cases of dictionary/sequence arguments added later which we might look at for inspiration:

https://github.com/mdn/browser-compat-data/blob/6a10bd073bd46cd2509db0adf9d944036fcbca4c/api/Element.json#L1118

https://github.com/mdn/browser-compat-data/blob/6a10bd073bd46cd2509db0adf9d944036fcbca4c/api/EventTarget.json#L228

https://github.com/mdn/browser-compat-data/blob/6a10bd073bd46cd2509db0adf9d944036fcbca4c/api/URLSearchParams.json#L121

There's not really any consistency and I don't have a suggestion for how to improve the suggestion after looking at these :)

2021-01-14 16:55 UTC, ddbeck commented
Sorry, @foolip, I'm not quite sure what I'm meant to do here.

Are you looking for me to write another version of the description text? I don't think there's an obviously better or more consistent description text to go with here, given the details. So we can go with my suggestion or with a reasonable-sounding alternative. I'm not particularly opinionated on this one.

Or were you looking for a general review? Because this looks fine, though we ought to adopt _some_ change of the description text.

2021-01-14 17:56 UTC, foolip commented
@ddbeck I just wanted to show the existing forms and see if that would make you want to match some aspects of those other wordings. Since neither of us have a suggested improvement to the wording, I'll apply it and merge.

2021-01-14 18:01 UTC, foolip approved these changes

2021-01-14 18:01 UTC, merged

2021-01-14 18:13 UTC, foolip commented
I've also fixed the Safari versions in https://github.com/mdn/browser-compat-data/pull/8755.