updating Safari data.
mdn/browser-compat-data pull request #8662
Opened 2021-01-06 09:34 UTC by rachelandrew

Fixes: https://github.com/mdn/content/issues/984

BCD indicated that `::marker` was fully supported in Safari, where in fact only a subset of properties are supported.

2021-01-12 08:59 UTC, ddbeck requested changes
Thanks, @rachelandrew. I made some very minor style suggestions in line comments.

2021-01-12 08:59 UTC, ddbeck commented on css/selectors/marker.json
> +              "notes": "Safari support is limited to color and font-size. See: <a href='https://webkit.org/b/204163'>#204163</a>"
nit: style

```suggestion
              "notes": "Safari support is limited to <code>color</code> and <code>font-size</code>. See <a href='https://webkit.org/b/204163'>bug 204163</a>"
```

2021-01-12 08:59 UTC, ddbeck commented on css/selectors/marker.json
> +              "notes": "Safari support is limited to color and font-size. See: <a href='https://webkit.org/b/204163'>#204163</a>"
nit: style

```suggestion
              "notes": "Safari support is limited to <code>color</code> and <code>font-size</code>. See <a href='https://webkit.org/b/204163'>bug 204163</a>"
```

2021-01-13 09:14 UTC, rachelandrew commented
@ddbeck thanks :)

2021-01-13 09:47 UTC, ddbeck approved these changes
Thank you! 🎉

2021-01-13 09:47 UTC, merged