Update use.json
mdn/browser-compat-data pull request #8691
Opened 2021-01-09 16:49 UTC by Zearin

Edited `notes` to use terser language (and note the version that fixed the bug at the beginning).

----

A checklist to help your pull request get merged faster:
- [x] Summarize your changes

----

(Other checklist items omitted, as they are not applicable.)

2021-01-12 08:40 UTC, ddbeck requested changes
Hi @Zearin and thank your for this PR. I see that it's your first to BCD—welcome to the project!

This is a really good edit. I put in a couple suggestions below to tighten up the language even more.

2021-01-12 08:40 UTC, ddbeck commented on svg/elements/use.json
> +              "notes": "Firefox versions prior to 56 suffered from a bug where they didn't completely follow the <code>use</code> cascading rules (see <a href='https://bugzil.la/265894'>bug 265894</a
```suggestion
              "notes": "Before version 56, Firefox does not completely follow the <code>use</code> cascading rules (see <a href='https://bugzil.la/265894'>bug 265894</a>). A fix is <a href='https://stackoverflow.com/questions/27866893/svg-fill-not-being-applied-in-firefox/27872310#27872310'>documented by Amelia Bellamy-Royds on StackOverflow</a>."
```

2021-01-12 08:40 UTC, ddbeck commented on svg/elements/use.json
> +              "notes": "Firefox versions prior to 56 suffered from a bug where they didn't completely follow the <code>use</code> cascading rules (see <a href='https://bugzil.la/265894'>bug 265894</a
```suggestion
              "notes": "Before version 56, Firefox does not completely follow the <code>use</code> cascading rules (see <a href='https://bugzil.la/265894'>bug 265894</a>). A fix is <a href='https://stackoverflow.com/questions/27866893/svg-fill-not-being-applied-in-firefox/27872310#27872310'>documented by Amelia Bellamy-Royds on StackOverflow</a>."
```

2021-01-25 15:53 UTC, Zearin commented
Thanks, @ddbeck !  Suggestions committed.

2021-01-25 15:54 UTC, ddbeck approved these changes
Thank you! 🎉

2021-01-25 15:55 UTC, merged