adding overflow-clip margin and support for clip
mdn/browser-compat-data pull request #8803
Opened 2021-01-20 08:59 UTC by rachelandrew

Chrome is shipping `overflow:clip` and the new `overflow-clip-margin` property in 89. Adding data for these (I'm going to document `overflow-clip-margin`). Also removing experimental flag for `overflow: clip` as Firefox already implements it so that is two engines. 

https://www.chromestatus.com/feature/5638444178997248

2021-01-28 16:29 UTC, ddbeck requested changes
One little fix to make before merging. Thank you, @rachelandrew!

2021-01-28 16:29 UTC, ddbeck commented on css/properties/overflow-clip-margin.json
> +            "experimental": false,
```suggestion
            "experimental": true,
```

2021-02-03 07:56 UTC, rachelandrew commented
@ddbeck done :)

2021-02-04 14:13 UTC, ddbeck approved these changes
Thank you! 🎉

2021-02-04 14:13 UTC, merged