Remove Chromium 89 from String.at.
mdn/browser-compat-data pull request #8869
Opened 2021-01-26 22:29 UTC by jpmedley

The `String.at()` function did not make the cut for Chrome 89. I set the value to `false`. Even though it will probably be in 90, we won't know for sure for as six weeks.

2021-01-27 09:48 UTC, Elchi3 requested changes
You probably also want to change `Array.at` and `TypedArray.at`, right?

2021-01-28 11:45 UTC, ddbeck commented
Related previous PR: #8721

2021-02-01 14:56 UTC, jpmedley commented
@Elchi3 Done.

2021-02-01 14:58 UTC, Elchi3 approved these changes
@jpmedley most excellent 👍

2021-02-01 14:59 UTC, merged