CanvasRenderingContext2d createConicGradient
mdn/browser-compat-data pull request #8886
Opened 2021-01-28 11:39 UTC by Rumyra

A checklist to help your pull request get merged faster:
- [ ] Summarize your changes

Adding data for `CanvasRenderingContext2d.createConicGradient()`

- [ ] Data: link to resources that verify support information (such as browser's docs, changelogs, source control, bug trackers, and tests)

https://bugs.chromium.org/p/chromium/issues/detail?id=1097034&q=1097034&can=2
https://bugzilla.mozilla.org/show_bug.cgi?id=1627014

- [ ] Data: if you tested something, describe how you tested with details like browser and version

Works in both Chrome & FF for me (FF 86 with canvas.createConicGradient.enabled. Does not work in latest Opera or Safari desktop

- [ ] Review the results of the linter and fix problems reported (If you need help, please ask in a comment!)

No errors

- [ ] Link to related issues or pull requests, if any

https://github.com/mdn/content/issues/1724

2021-02-04 15:40 UTC, ddbeck requested changes
[Bug 1097034](https://bugs.chromium.org/p/chromium/issues/detail?id=1097034) says this is implemented behind a flag in Chrome too (I couldn't get it to work in Chrome by default, too). Could you update this with the flag data? Thank you!

2021-02-08 13:08 UTC, Rumyra commented
Oh I'm so sorry I missed that 😬 I've added the flag (still checking syntax every time ☺️ hope this is correct)

2021-02-08 13:15 UTC, chandonglee commented
no problem

2021-02-08 14:38 UTC, ddbeck requested changes
Looks really good, but there's one tiny nit for consistency. Thank you!

2021-02-08 14:38 UTC, ddbeck commented on api/CanvasRenderingContext2D.json
> +                  "name": "new-canvas-2d-api"
```suggestion
                  "name": "#new-canvas-2d-api"
```

2021-02-08 14:38 UTC, ddbeck commented on api/CanvasRenderingContext2D.json
> +                  "name": "new-canvas-2d-api"
```suggestion
                  "name": "#new-canvas-2d-api"
```

2021-02-08 16:02 UTC, ddbeck approved these changes
Thank you! 🎉

2021-02-08 16:02 UTC, merged