Update windows.create BCD to indicate focused:false is currently ignored
mdn/browser-compat-data pull request #8898
Opened 2021-01-29 19:02 UTC by caitmuenster

Fixes https://github.com/mdn/content/issues/1723 by adding a note to the BCD table in https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/windows/create that `focused:false` is currently ignored.

2021-01-29 20:50 UTC, Rob--W approved these changes
LGTM

Could have been a separate property to mark the level of support for `focused:true` by Firefox version, but I don't really mind the current approach.

2021-01-29 20:55 UTC, caitmuenster commented
Thanks Rob!

2021-02-03 14:42 UTC, ddbeck requested changes

2021-02-03 14:42 UTC, ddbeck commented on webextensions/api/windows.json
> +                  "Firefox currently ignores the 'focused:false' option."
Thanks for this PR, @caitmuenster. I trust the other review here on the substance of the note, but I do have a couple of style concerns.

- "Currently" is a bit of a moving target and difficult to maintain (we don't reconfirm every note for every release). Can we constrain this information at all? For example, if this is a new behavior, can it be anchored to a specific version number (e.g., "From version X, Firefox ignores the `focused: false` option."). Or if it's been true from inception, can we drop the word "currently"?
- I think it'd be nice to put the quoted text in code format (even though the other notes didn't do that)

```suggestion
                  "Firefox currently ignores the <code>focused: false</code> option."
```

2021-02-03 18:08 UTC, caitmuenster commented
Thanks @ddbeck! Just pushed a commit with your suggestions.

2021-02-04 15:40 UTC, ddbeck approved these changes
Looks good. Thank you! 🎉

2021-02-04 15:41 UTC, merged