Demix NavigatorConcurrentHardware
mdn/browser-compat-data pull request #9079
Opened 2021-02-12 23:21 UTC by foolip

Part of https://github.com/mdn/browser-compat-data/issues/8929

2021-02-12 23:24 UTC, foolip commented
This is simply splitting the entry without changes. I checked the data against mdn-bcd-collector results and didn't find any differences for Worker. For WorkerNavigator there was a proposed change, but it doesn't look legit, I filed https://github.com/foolip/mdn-bcd-collector/issues/960.

2021-02-12 23:25 UTC, foolip commented
@Elchi3 changes like this will require a lot of fixes on MDN. I'd like to not volunteer for that, but is it useful for me to send PRs like this one?

2021-02-14 10:53 UTC, Elchi3 requested changes

2021-02-14 10:53 UTC, Elchi3 commented on api/Navigator.json
> +          "mdn_url": "https://developer.mozilla.org/docs/Web/API/WorkerNavigator/hardwareConcurrency",
```suggestion
          "mdn_url": "https://developer.mozilla.org/docs/Web/API/Navigator/hardwareConcurrency",
```

2021-02-14 10:53 UTC, Elchi3 commented
> @Elchi3 changes like this will require a lot of fixes on MDN. I'd like to not volunteer for that, but is it useful for me to send PRs like this one?

I'm trying to burn through all mixins on BCD and on MDN. Any help is useful :)

2021-02-14 16:02 UTC, foolip commented on api/Navigator.json
> +          "mdn_url": "https://developer.mozilla.org/docs/Web/API/WorkerNavigator/hardwareConcurrency",
Oops, thanks!

2021-02-14 16:15 UTC, foolip commented
Before this is merged I want to note that `WorkerNavigator` and `WorkerLocation` are odd cases and it's not obvious how MDN/BCD should represent them. These interfaces predate the use of `[Exposed=(Window,Worker)]` and are subset copies of `Navigator` and `Location`.

The thing is that even though these interfaces are real, web developers just use `navigator.language` or `location.href` in both window and worker scripts. I'm skeptical that it makes sense to document them separately, and am unsure if spitting them on BCD is the right thing.

2021-02-14 16:18 UTC, foolip commented
Or rather I should say I could see us changing this later to use the same mechanism for representing global scope exposure as for interfaces and global methods, assuming a single method for that emerges after `WindowOrWorkerGlobalScope` demixing.

2021-02-14 17:21 UTC, Elchi3 commented
hm, I see. Can we file a separate issue that discusses options for the whole Window/Worker problem with mixins? We can wait to merge this PR until we have had that discussion if you like.

2021-02-15 09:42 UTC, foolip commented
I've filed https://github.com/mdn/browser-compat-data/issues/9125 for this specific issue, and https://github.com/mdn/browser-compat-data/issues/9127 for `WindowOrWorkerGlobalScope`.

2021-06-07 07:59 UTC, foolip commented
I've rebased this now but I don't like it. It's a similar issue to demixing `WindowOrWorkerGlobalScope`, where web developers can use the same code in windows and workers, and splitting it into two entries seems unhelpful. Finding a way to represent this as one entry meaning `navigator.hardwareConcurrency` and using notes or `partial_implementation` if it doesn't work in workers seems better.

2021-06-09 10:04 UTC, Elchi3 commented
Thanks Philip! I propose we sort out all other mixins first and then look at everything that touches the window and worker problematic.

2021-07-08 09:28 UTC, Elchi3 commented
This was done in https://github.com/mdn/browser-compat-data/pull/11413

2021-07-12 17:56 UTC, closed without merging