Add Edge versions for AudioParam API
mdn/browser-compat-data pull request #9083
Opened 2021-02-13 07:04 UTC by vinyldarkscratch

This PR adds real values for Microsoft Edge for the `AudioParam` API, based upon results from the [mdn-bcd-collector](https://mdn-bcd-collector.appspot.com) project (v1.3.1).  Results are manually confirmed for accuracy.

Tests Used: https://mdn-bcd-collector.appspot.com/tests/api/AudioParam

2021-02-16 09:45 UTC, foolip requested changes
I think https://mdn-bcd-collector.appspot.com/tests/api/AudioParam is probably a broken test, the results are all false in both current Chrome and in Edge 18.

2021-02-16 10:49 UTC, foolip commented
I fixed these tests in https://github.com/foolip/mdn-bcd-collector/pull/973, which should be deployed soon.

2021-02-19 07:18 UTC, vinyldarkscratch commented
Looks like the results are the same for this PR as in collector v1.3.3 (which has the updated tests).

2021-02-19 09:32 UTC, foolip approved these changes
I've looked at https://mdn-bcd-collector.appspot.com/tests/api/AudioParam in Edge 18 and 80 and indeed this looks right.

2021-02-19 09:33 UTC, merged