feImage note: doesn't work with doc fragments on Firefox
mdn/browser-compat-data pull request #9135
Opened 2021-02-16 01:59 UTC by hamishwillee

Firefox does not support document fragments in `feImage` - as per bug https://bugzilla.mozilla.org/show_bug.cgi?id=455986

What this means is that you can reference a png, svg or other document from an external source, but not a fragment - e.g. a path or circle you define in the doc. It's an irritating limitation.

I'm still confirming whether this just affects xlink:href or also href - see https://bugzilla.mozilla.org/show_bug.cgi?id=455986#c25

2021-02-25 14:01 UTC, ddbeck commented
@hamishwillee Is there any help we can give here, to get this out of draft status?

2021-02-26 00:23 UTC, hamishwillee commented
@ddbeck Good to review now. 

An "associated" question though. I have documented this FF limitation for the `feImage`, but this also affects [SVGFEImageElement](https://developer.mozilla.org/en-US/docs/Web/API/SVGFEImageElement), which inherits the same href and xlink:href values from [SVGURIReference](https://developer.mozilla.org/en-US/docs/Web/API/SVGURIReference). So the question is, how should this be documented in SVGFEImageElement/SVGURIReference given that SVGURIReference is kind of a mixin? Or should this just be ignored because SVGFEImageElement reflects feImge?

2021-02-26 13:24 UTC, ddbeck commented
> how should this be documented in SVGFEImageElement/SVGURIReference given that SVGURIReference is kind of a mixin? Or should this just be ignored because SVGFEImageElement reflects feImge?

Let's just ignore it. Two points in favor doing so:

1. It's reflection, so I think it's fair to regard the noted issue is a problem of the underlying element rather than the API.
2. For `SVGURIReference` specifically, the data will soon go away. It is a true mixin and it's on the list of interfaces to demix in https://github.com/mdn/browser-compat-data/issues/8929#issuecomment-778502425.

I'll start my actual review now. 😃

2021-02-26 13:35 UTC, ddbeck requested changes
A little idea before merging in line comments. Thank you, @hamishwillee!

2021-02-26 13:35 UTC, ddbeck commented on svg/elements/feImage.json
> +                "notes": "Document fragments (including references to fragments in current document) are not supported (see <a href='https://bugzil.la/455986'>bug 455986</a>)."
nit: I think it reads better with a definite article here. Sorry, this is a very small one

```suggestion
                "notes": "Document fragments (including references to fragments in the current document) are not supported (see <a href='https://bugzil.la/455986'>bug 455986</a>)."
```

2021-02-26 13:35 UTC, ddbeck commented on svg/elements/feImage.json
> +                "notes": "Document fragments (including references to fragments in current document) are not supported (see <a href='https://bugzil.la/455986'>bug 455986</a>)."
```suggestion
                "notes": "Document fragments (including references to fragments in the current document) are not supported (see <a href='https://bugzil.la/455986'>bug 455986</a>)."
```

2021-02-26 13:35 UTC, ddbeck commented on svg/elements/feImage.json
> +                "notes": "Document fragments (including references to fragments in current document) are not supported (see <a href='https://bugzil.la/455986'>bug 455986</a>)."
```suggestion
                "notes": "Document fragments (including references to fragments in the current document) are not supported (see <a href='https://bugzil.la/455986'>bug 455986</a>)."
```

2021-02-26 13:35 UTC, ddbeck commented on svg/elements/feImage.json
> +                "notes": "Document fragments (including references to fragments in current document) are not supported (see <a href='https://bugzil.la/455986'>bug 455986</a>)."
```suggestion
                "notes": "Document fragments (including references to fragments in the current document) are not supported (see <a href='https://bugzil.la/455986'>bug 455986</a>)."
```

2021-02-28 22:39 UTC, hamishwillee commented
Thanks @ddbeck . Makes sense. I merged your change.

2021-03-02 14:30 UTC, ddbeck approved these changes
Thank you! 🎉

2021-03-02 14:30 UTC, merged