Mark Intl.NumberFormat support partial in Safari
mdn/browser-compat-data pull request #9371
Opened 2021-03-07 04:33 UTC by sideshowbarker

Code examination of https://trac.webkit.org/changeset/266031/webkit indicates that support for `compactDisplay`, `currencySign`, `notation`, `signDisplay`, `unit`, `unitDisplay`, `currencyDisplay: 'narrowSymbol'`, and `style: 'unit'`" wasn’t added until 2020-08-22 — and didn’t make it into Safari 14 (confirmed by testing), which was released 2020-09-16.

Fixes https://github.com/mdn/browser-compat-data/issues/9319

2021-03-08 02:18 UTC, lucalves approved these changes

2021-03-17 14:15 UTC, Elchi3 commented
hm, so this talks about features that are also sub features in the data. I think this makes the table quite inconsistent. Like, we don't usually mark the main feature as partial_support when there are additional features below that indicate the support for what you talk about in partial support. Do I make sense?

2021-03-19 07:37 UTC, sideshowbarker commented
> hm, so this talks about features that are also sub features in the data. I think this makes the table quite inconsistent. Like, we don't usually mark the main feature as partial_support when there are additional features below that indicate the support for what you talk about in partial support. Do I make sense?

Yup — make sense; I’ve amended the patch accordingly

2021-03-19 10:59 UTC, Elchi3 requested changes
Description would be good for consistency with the other sub features. LGTM otherwise!

2021-03-19 10:59 UTC, Elchi3 commented on javascript/builtins/intl/NumberFormat.json
> +                "support": {
```suggestion
                "description": "<code>currencyDisplay</code> option",
                "support": {
```

2021-03-19 12:47 UTC, Elchi3 approved these changes

2021-03-19 12:47 UTC, merged