Updates chrome to version 90
mdn/browser-compat-data pull request #9894
Opened 2021-04-17 06:59 UTC by lucalves

Hello everyone, everything good?

In that PR, I updated the docs to version 90 of Chrome.

According to [Chrome Status](https://www.chromestatus.com/features/schedule), 92 is the nightly version.

😉

2021-04-17 23:19 UTC, vinyldarkscratch commented
Looks like you've got some syntax errors in your PR.  Can you resolve them?

2021-04-18 20:57 UTC, lucalves commented
I was unable to identify which line the syntax error, @vinyldarkscratch. Would you help me?

2021-04-19 00:34 UTC, vinyldarkscratch requested changes

2021-04-19 00:34 UTC, vinyldarkscratch commented on browsers/chrome.json
> +          "engine_version": "92"
```suggestion
          "engine_version": "92"
        }
```

2021-04-19 00:34 UTC, vinyldarkscratch commented on browsers/chrome_android.json
> +          "engine_version": "92"
```suggestion
          "engine_version": "92"
        }
```

2021-04-19 00:34 UTC, vinyldarkscratch commented on browsers/webview_android.json
> +      }
```suggestion
        }
```

2021-04-19 01:10 UTC, lucalves commented
I solved your suggestions, @vinyldarkscratch! Thanks.

2021-04-19 07:48 UTC, vinyldarkscratch commented on browsers/chrome.json
> +          "release_date": "2021-04-14",
```suggestion
          "release_date": "2021-04-13",
```

2021-04-19 07:51 UTC, vinyldarkscratch approved these changes
Alrighty, everything's looking good to me, thank you for the PR!  I'll merge once the checks have passed!

2021-04-19 07:51 UTC, merged