Remove irrelevant Firefox flag data for text-combine-upright CSS property
mdn/browser-compat-data pull request #9948
Opened 2021-04-19 16:32 UTC by vinyldarkscratch

This PR removes irrelevant flag data for Firefox and Firefox Android for the `text-combine-upright` CSS property as per the corresponding [data guidelines](https://github.com/mdn/browser-compat-data/blob/main/docs/data-guidelines.md#removal-of-irrelevant-flag-data).

This PR was created from results of a [script](https://github.com/vinyldarkscratch/browser-compat-data/blob/scripts/remove-redundant-flags/scripts/remove-redundant-flags.js) designed to remove irrelevant flags.

2021-04-21 19:43 UTC, foolip requested changes

2021-04-21 19:43 UTC, foolip commented on css/properties/text-combine-upright.json
>                  "notes": "Before version 48, Firefox did not implement layout support for tate-chū-yoko."
This note end up being pointless with the flag data removed.

2021-05-05 20:23 UTC, foolip reviewed
Looking at this again, I think the entries for 81 should also be removed. If being animatable is a bug it's the earliest entry that should have a note and `partial_implementation`, but I think it's more like the feature was too supported.

Since the current behavior is more restricted than the historical, pointing it out isn't really helpful. (When the feature has gotten bigger in some sense, it's different.)

But I'd want @ddbeck to weigh in here.

2021-05-06 15:47 UTC, ddbeck commented
@foolip I think it makes sense to have a note because it's possible that some web developers have relied on the buggy behavior. But I'd probably fold it into one support statement: added at 48, with a note saying, "Before version 81…".

(Though this note will be increasingly uninteresting as time goes on—might be nice to figure out an irrelevant note guideline someday.)

2021-05-21 13:42 UTC, foolip approved these changes

2021-05-21 13:43 UTC, foolip commented
Oops, lint is failing.

2021-05-21 13:56 UTC, foolip approved these changes

2021-05-21 13:56 UTC, merged