Fix data for bading API.
mdn/browser-compat-data pull request #9988
Opened 2021-04-20 18:57 UTC by jpmedley

I had a email exchange with one of the Chrome engineers who worked on this. 

>It shipped in 83. That was on Windows and Mac. It has never shipped on Linux, Android or Chrome OS (due to lack of support for badging for native apps on those platforms). It is coming to Chrome OS in 91.

2021-04-22 15:28 UTC, ddbeck commented
Two questions on this:

1. Have you tried this? Is the API not exposed on the unsupported platforms? Or is it only non-functional?
2. Do you have any idea how this impacts the other Chromium browsers? The Edge, Opera Android, and Samsung Internet data looks a bit suspect, in light of this change.

2021-05-05 14:48 UTC, ddbeck commented
Hi @jpmedley, do you plan to come back to this PR?

2021-05-05 17:51 UTC, jpmedley commented
I have not tried it. I don't see the need to since the engineer who implemented told me it was not supported.

I don't have any idea how this impacts other Chromium browsers. If the choice is between having one value that's flat out wrong and one that's suspect, I choose suspect.

2021-05-19 15:51 UTC, ddbeck requested changes
Thanks, Joe. A few of the entries need `"partial_implementation": true` per https://github.com/mdn/browser-compat-data/blob/main/docs/data-guidelines.md#operating-system-limitations-imply-partial_implementation. Then this will be ready.

2021-05-19 15:51 UTC, ddbeck commented on api/Navigator.json
> +              "version_added": "83",
```suggestion
              "version_added": "83",
              "partial_implementation": true,
```

2021-05-19 15:51 UTC, ddbeck commented on api/Navigator.json
> +              "version_added": "83",
```suggestion
              "version_added": "83",
              "partial_implementation": true,
```

2021-05-19 15:51 UTC, ddbeck commented on api/Navigator.json
> +              "version_added": "83",
```suggestion
              "version_added": "83",
              "partial_implementation": true,
```

2021-05-19 17:47 UTC, jpmedley commented
Done.

2021-05-20 11:06 UTC, ddbeck approved these changes
Thank you! 🎉

2021-05-20 11:06 UTC, merged